from .base import VKMethod
from .docs import DocsGetMessagesUploadServer, DocsSave
from .groups import GroupsGetById, GroupsGetLongPollServer, GroupsGetMembers
from .messages import (
    MessagesAddChatUser,
    MessagesAllowMessagesFromGroup,
    MessagesCreateChat,
    MessagesDelete,
    MessagesDeleteChatPhoto,
    MessagesDeleteConversation,
    MessagesDenyMessagesFromGroup,
    MessagesEdit,
    MessagesEditChat,
    MessagesGetByConversationMessageId,
    MessagesGetById,
    MessagesGetChat,
    MessagesGetChatPreview,
    MessagesGetConversationMembers,
    MessagesGetConversations,
    MessagesGetHistory,
    MessagesGetHistoryAttachments,
    MessagesGetImportantMessages,
    MessagesGetInviteLink,
    MessagesGetLastActivity,
    MessagesGetLongPollHistory,
    MessagesGetPeersSubscriptions,
    MessagesJoinChatByInviteLink,
    MessagesMarkAsImportant,
    MessagesMarkAsRead,
    MessagesPin,
    MessagesRemoveChatUser,
    MessagesRestore,
    MessagesSearch,
    MessagesSearchConversations,
    MessagesSend,
    MessagesSendEventAnswer,
    MessagesSetActivity,
    MessagesSetChatPhoto,
    MessagesUnpin,
)
from .photos import PhotosGetMessagesUploadServer, PhotosSaveMessagesPhoto
from .users import UsersGet, UsersSearch
from .wall import WallGet, WallGetById, WallPost

# registry: VK method string → typed VKMethod class
# used by _APICallable to route dynamic calls through Pydantic
_REGISTRY: dict[str, type[VKMethod]] = {
    # messages
    "messages.send": MessagesSend,
    "messages.delete": MessagesDelete,
    "messages.edit": MessagesEdit,
    "messages.pin": MessagesPin,
    "messages.unpin": MessagesUnpin,
    "messages.markAsRead": MessagesMarkAsRead,
    "messages.getHistory": MessagesGetHistory,
    "messages.setActivity": MessagesSetActivity,
    "messages.getById": MessagesGetById,
    "messages.getConversations": MessagesGetConversations,
    "messages.sendMessageEventAnswer": MessagesSendEventAnswer,
    "messages.search": MessagesSearch,
    "messages.getChat": MessagesGetChat,
    "messages.createChat": MessagesCreateChat,
    "messages.editChat": MessagesEditChat,
    "messages.addChatUser": MessagesAddChatUser,
    "messages.removeChatUser": MessagesRemoveChatUser,
    "messages.getChatPreview": MessagesGetChatPreview,
    "messages.getInviteLink": MessagesGetInviteLink,
    "messages.joinChatByInviteLink": MessagesJoinChatByInviteLink,
    "messages.denyMessagesFromGroup": MessagesDenyMessagesFromGroup,
    "messages.allowMessagesFromGroup": MessagesAllowMessagesFromGroup,
    "messages.setChatPhoto": MessagesSetChatPhoto,
    "messages.deleteChatPhoto": MessagesDeleteChatPhoto,
    "messages.searchConversations": MessagesSearchConversations,
    "messages.getConversationMembers": MessagesGetConversationMembers,
    "messages.deleteConversation": MessagesDeleteConversation,
    "messages.restore": MessagesRestore,
    "messages.getByConversationMessageId": MessagesGetByConversationMessageId,
    "messages.getLastActivity": MessagesGetLastActivity,
    "messages.getHistoryAttachments": MessagesGetHistoryAttachments,
    "messages.getImportantMessages": MessagesGetImportantMessages,
    "messages.markAsImportant": MessagesMarkAsImportant,
    "messages.getLongPollHistory": MessagesGetLongPollHistory,
    "messages.getPeersSubscriptions": MessagesGetPeersSubscriptions,
    # users
    "users.get": UsersGet,
    "users.search": UsersSearch,
    # groups
    "groups.getLongPollServer": GroupsGetLongPollServer,
    "groups.getById": GroupsGetById,
    "groups.getMembers": GroupsGetMembers,
    # wall
    "wall.post": WallPost,
    "wall.get": WallGet,
    "wall.getById": WallGetById,
    # photos
    "photos.getMessagesUploadServer": PhotosGetMessagesUploadServer,
    "photos.saveMessagesPhoto": PhotosSaveMessagesPhoto,
    # docs
    "docs.getMessagesUploadServer": DocsGetMessagesUploadServer,
    "docs.save": DocsSave,
}

__all__ = [
    "VKMethod",
    "_REGISTRY",
    # messages
    "MessagesSend",
    "MessagesDelete",
    "MessagesEdit",
    "MessagesPin",
    "MessagesUnpin",
    "MessagesMarkAsRead",
    "MessagesGetHistory",
    "MessagesSetActivity",
    "MessagesGetById",
    "MessagesGetConversations",
    "MessagesSendEventAnswer",
    "MessagesSearch",
    "MessagesGetChat",
    "MessagesCreateChat",
    "MessagesEditChat",
    "MessagesAddChatUser",
    "MessagesRemoveChatUser",
    "MessagesGetChatPreview",
    "MessagesGetInviteLink",
    "MessagesJoinChatByInviteLink",
    "MessagesDenyMessagesFromGroup",
    "MessagesAllowMessagesFromGroup",
    "MessagesSetChatPhoto",
    "MessagesDeleteChatPhoto",
    "MessagesSearchConversations",
    "MessagesGetConversationMembers",
    "MessagesDeleteConversation",
    "MessagesRestore",
    "MessagesGetByConversationMessageId",
    "MessagesGetLastActivity",
    "MessagesGetHistoryAttachments",
    "MessagesGetImportantMessages",
    "MessagesMarkAsImportant",
    "MessagesGetLongPollHistory",
    "MessagesGetPeersSubscriptions",
    # users
    "UsersGet",
    "UsersSearch",
    # groups
    "GroupsGetById",
    "GroupsGetLongPollServer",
    "GroupsGetMembers",
    # wall
    "WallPost",
    "WallGet",
    "WallGetById",
    # photos
    "PhotosGetMessagesUploadServer",
    "PhotosSaveMessagesPhoto",
    # docs
    "DocsGetMessagesUploadServer",
    "DocsSave",
]
