"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from . import account as account
from . import ads as ads
from . import appWidgets as appWidgets
from . import apps as apps
from . import auth as auth
from . import board as board
from . import bugtracker as bugtracker
from . import calls as calls
from . import database as database
from . import docs as docs
from . import donut as donut
from . import downloadedGames as downloadedGames
from . import execute as execute
from . import fave as fave
from . import friends as friends
from . import gifts as gifts
from . import groups as groups
from . import leadForms as leadForms
from . import likes as likes
from . import market as market
from . import messages as messages
from . import newsfeed as newsfeed
from . import notes as notes
from . import notifications as notifications
from . import orders as orders
from . import pages as pages
from . import photos as photos
from . import podcasts as podcasts
from . import polls as polls
from . import prettyCards as prettyCards
from . import search as search
from . import secure as secure
from . import stats as stats
from . import status as status
from . import storage as storage
from . import store as store
from . import stories as stories
from . import streaming as streaming
from . import translations as translations
from . import users as users
from . import utils as utils
from . import video as video
from . import wall as wall
from . import widgets as widgets

GENERATED_REGISTRY: dict[str, type] = {}
GENERATED_REGISTRY.update(account.REGISTRY)
GENERATED_REGISTRY.update(ads.REGISTRY)
GENERATED_REGISTRY.update(appWidgets.REGISTRY)
GENERATED_REGISTRY.update(apps.REGISTRY)
GENERATED_REGISTRY.update(auth.REGISTRY)
GENERATED_REGISTRY.update(board.REGISTRY)
GENERATED_REGISTRY.update(bugtracker.REGISTRY)
GENERATED_REGISTRY.update(calls.REGISTRY)
GENERATED_REGISTRY.update(database.REGISTRY)
GENERATED_REGISTRY.update(docs.REGISTRY)
GENERATED_REGISTRY.update(donut.REGISTRY)
GENERATED_REGISTRY.update(downloadedGames.REGISTRY)
GENERATED_REGISTRY.update(execute.REGISTRY)
GENERATED_REGISTRY.update(fave.REGISTRY)
GENERATED_REGISTRY.update(friends.REGISTRY)
GENERATED_REGISTRY.update(gifts.REGISTRY)
GENERATED_REGISTRY.update(groups.REGISTRY)
GENERATED_REGISTRY.update(leadForms.REGISTRY)
GENERATED_REGISTRY.update(likes.REGISTRY)
GENERATED_REGISTRY.update(market.REGISTRY)
GENERATED_REGISTRY.update(messages.REGISTRY)
GENERATED_REGISTRY.update(newsfeed.REGISTRY)
GENERATED_REGISTRY.update(notes.REGISTRY)
GENERATED_REGISTRY.update(notifications.REGISTRY)
GENERATED_REGISTRY.update(orders.REGISTRY)
GENERATED_REGISTRY.update(pages.REGISTRY)
GENERATED_REGISTRY.update(photos.REGISTRY)
GENERATED_REGISTRY.update(podcasts.REGISTRY)
GENERATED_REGISTRY.update(polls.REGISTRY)
GENERATED_REGISTRY.update(prettyCards.REGISTRY)
GENERATED_REGISTRY.update(search.REGISTRY)
GENERATED_REGISTRY.update(secure.REGISTRY)
GENERATED_REGISTRY.update(stats.REGISTRY)
GENERATED_REGISTRY.update(status.REGISTRY)
GENERATED_REGISTRY.update(storage.REGISTRY)
GENERATED_REGISTRY.update(store.REGISTRY)
GENERATED_REGISTRY.update(stories.REGISTRY)
GENERATED_REGISTRY.update(streaming.REGISTRY)
GENERATED_REGISTRY.update(translations.REGISTRY)
GENERATED_REGISTRY.update(users.REGISTRY)
GENERATED_REGISTRY.update(utils.REGISTRY)
GENERATED_REGISTRY.update(video.REGISTRY)
GENERATED_REGISTRY.update(wall.REGISTRY)
GENERATED_REGISTRY.update(widgets.REGISTRY)

GENERATED_NAMESPACES = (
    "account",
    "ads",
    "appWidgets",
    "apps",
    "auth",
    "board",
    "bugtracker",
    "calls",
    "database",
    "docs",
    "donut",
    "downloadedGames",
    "execute",
    "fave",
    "friends",
    "gifts",
    "groups",
    "leadForms",
    "likes",
    "market",
    "messages",
    "newsfeed",
    "notes",
    "notifications",
    "orders",
    "pages",
    "photos",
    "podcasts",
    "polls",
    "prettyCards",
    "search",
    "secure",
    "stats",
    "status",
    "storage",
    "store",
    "stories",
    "streaming",
    "translations",
    "users",
    "utils",
    "video",
    "wall",
    "widgets",
)

__all__ = [
    "account",
    "ads",
    "appWidgets",
    "apps",
    "auth",
    "board",
    "bugtracker",
    "calls",
    "database",
    "docs",
    "donut",
    "downloadedGames",
    "execute",
    "fave",
    "friends",
    "gifts",
    "groups",
    "leadForms",
    "likes",
    "market",
    "messages",
    "newsfeed",
    "notes",
    "notifications",
    "orders",
    "pages",
    "photos",
    "podcasts",
    "polls",
    "prettyCards",
    "search",
    "secure",
    "stats",
    "status",
    "storage",
    "store",
    "stories",
    "streaming",
    "translations",
    "users",
    "utils",
    "video",
    "wall",
    "widgets",
    "GENERATED_REGISTRY",
    "GENERATED_NAMESPACES",
]
