"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class AccountBan(VKMethod[int]):
    """VK API method account.ban."""

    __returning__ = int
    __api_method__ = "account.ban"

    owner_id: int | None = None


class AccountChangePassword(VKMethod[dict]):
    """Changes a user password after access is successfully restored with the [vk.com/dev/auth.restore|auth.restore] method."""

    __returning__ = dict
    __api_method__ = "account.changePassword"

    new_password: str
    change_password_hash: str | None = None
    old_password: str | None = None
    restore_sid: str | None = None


class AccountGetActiveOffers(VKMethod[dict]):
    """Returns a list of active ads (offers) which executed by the user will bring him/her respective number of votes to his balance in the application."""

    __returning__ = dict
    __api_method__ = "account.getActiveOffers"

    count: int = 100
    offset: int = 0


class AccountGetAppPermissions(VKMethod[int]):
    """Gets settings of the user in this application."""

    __returning__ = int
    __api_method__ = "account.getAppPermissions"

    user_id: int | None = None


class AccountGetBanned(VKMethod[dict]):
    """Returns a user's blacklist."""

    __returning__ = dict
    __api_method__ = "account.getBanned"

    count: int = 20
    fields: list[str] | None = None
    offset: int | None = None


class AccountGetCounters(VKMethod[dict]):
    """Returns non-null values of user counters."""

    __returning__ = dict
    __api_method__ = "account.getCounters"

    filter: list[str] | None = None


class AccountGetInfo(VKMethod[dict]):
    """Returns current account info."""

    __returning__ = dict
    __api_method__ = "account.getInfo"

    fields: list[str] | None = None


class AccountGetProfileInfo(VKMethod[dict]):
    """Returns the current account info."""

    __returning__ = dict
    __api_method__ = "account.getProfileInfo"


class AccountGetPushSettings(VKMethod[dict]):
    """Gets settings of push notifications."""

    __returning__ = dict
    __api_method__ = "account.getPushSettings"

    device_id: str | None = None


class AccountRegisterDevice(VKMethod[int]):
    """Subscribes an iOS/Android/Windows Phone-based device to receive push notifications"""

    __returning__ = int
    __api_method__ = "account.registerDevice"

    device_id: str
    token: str
    device_model: str | None = None
    device_year: int | None = None
    pushes_granted: bool | None = None
    sandbox: bool = False
    settings: str | None = None
    system_version: str | None = None


class AccountSaveProfileInfo(VKMethod[dict]):
    """Edits current profile info."""

    __returning__ = dict
    __api_method__ = "account.saveProfileInfo"

    bdate: str | None = None
    bdate_visibility: int | None = None
    cancel_request_id: int | None = None
    city_id: int | None = None
    country_id: int | None = None
    first_name: str | None = None
    home_town: str | None = None
    last_name: str | None = None
    maiden_name: str | None = None
    relation: int | None = None
    relation_partner_id: int | None = None
    screen_name: str | None = None
    sex: int | None = None
    status: str | None = None


class AccountSetInfo(VKMethod[int]):
    """Allows to edit the current account info."""

    __returning__ = int
    __api_method__ = "account.setInfo"

    name: str | None = None
    value: str | None = None


class AccountSetOffline(VKMethod[int]):
    """Marks a current user as offline."""

    __returning__ = int
    __api_method__ = "account.setOffline"


class AccountSetOnline(VKMethod[int]):
    """Marks the current user as online for 15 minutes."""

    __returning__ = int
    __api_method__ = "account.setOnline"

    voip: bool | None = None


class AccountSetPushSettings(VKMethod[int]):
    """Change push settings."""

    __returning__ = int
    __api_method__ = "account.setPushSettings"

    device_id: str
    key: str | None = None
    settings: str | None = None
    value: list[str] | None = None


class AccountSetSilenceMode(VKMethod[int]):
    """Mutes push notifications for the set period of time."""

    __returning__ = int
    __api_method__ = "account.setSilenceMode"

    device_id: str | None = None
    peer_id: int | None = None
    sound: int | None = None
    time: int | None = None


class AccountUnban(VKMethod[int]):
    """VK API method account.unban."""

    __returning__ = int
    __api_method__ = "account.unban"

    owner_id: int | None = None


class AccountUnregisterDevice(VKMethod[int]):
    """Unsubscribes a device from push notifications."""

    __returning__ = int
    __api_method__ = "account.unregisterDevice"

    device_id: str | None = None
    sandbox: bool = False



REGISTRY: dict[str, type[VKMethod]] = {
    "account.ban": AccountBan,
    "account.changePassword": AccountChangePassword,
    "account.getActiveOffers": AccountGetActiveOffers,
    "account.getAppPermissions": AccountGetAppPermissions,
    "account.getBanned": AccountGetBanned,
    "account.getCounters": AccountGetCounters,
    "account.getInfo": AccountGetInfo,
    "account.getProfileInfo": AccountGetProfileInfo,
    "account.getPushSettings": AccountGetPushSettings,
    "account.registerDevice": AccountRegisterDevice,
    "account.saveProfileInfo": AccountSaveProfileInfo,
    "account.setInfo": AccountSetInfo,
    "account.setOffline": AccountSetOffline,
    "account.setOnline": AccountSetOnline,
    "account.setPushSettings": AccountSetPushSettings,
    "account.setSilenceMode": AccountSetSilenceMode,
    "account.unban": AccountUnban,
    "account.unregisterDevice": AccountUnregisterDevice,
}

__all__ = ["AccountBan", "AccountChangePassword", "AccountGetActiveOffers", "AccountGetAppPermissions", "AccountGetBanned", "AccountGetCounters", "AccountGetInfo", "AccountGetProfileInfo", "AccountGetPushSettings", "AccountRegisterDevice", "AccountSaveProfileInfo", "AccountSetInfo", "AccountSetOffline", "AccountSetOnline", "AccountSetPushSettings", "AccountSetSilenceMode", "AccountUnban", "AccountUnregisterDevice"]
