"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class AdsAddOfficeUsers(VKMethod[list]):
    """Adds managers and/or supervisors to advertising account."""

    __returning__ = list
    __api_method__ = "ads.addOfficeUsers"

    account_id: int
    data: str


class AdsCheckLink(VKMethod[dict]):
    """Allows to check the ad link."""

    __returning__ = dict
    __api_method__ = "ads.checkLink"

    account_id: int
    link_type: str
    link_url: str
    campaign_id: int | None = None


class AdsCreateAds(VKMethod[list]):
    """Creates ads."""

    __returning__ = list
    __api_method__ = "ads.createAds"

    account_id: int
    data: str


class AdsCreateCampaigns(VKMethod[list]):
    """Creates advertising campaigns."""

    __returning__ = list
    __api_method__ = "ads.createCampaigns"

    account_id: int
    data: str


class AdsCreateClients(VKMethod[list]):
    """Creates clients of an advertising agency."""

    __returning__ = list
    __api_method__ = "ads.createClients"

    account_id: int
    data: str


class AdsCreateLookalikeRequest(VKMethod[dict]):
    """VK API method ads.createLookalikeRequest."""

    __returning__ = dict
    __api_method__ = "ads.createLookalikeRequest"

    account_id: int
    source_type: str
    client_id: int | None = None
    retargeting_group_id: int | None = None


class AdsCreateTargetGroup(VKMethod[dict]):
    """Creates a group to re-target ads for users who visited advertiser's site (viewed information about the product, registered, etc.)."""

    __returning__ = dict
    __api_method__ = "ads.createTargetGroup"

    account_id: int
    lifetime: int
    name: str
    client_id: int | None = None
    target_pixel_id: int | None = None
    target_pixel_rules: str | None = None


class AdsCreateTargetPixel(VKMethod[dict]):
    """VK API method ads.createTargetPixel."""

    __returning__ = dict
    __api_method__ = "ads.createTargetPixel"

    account_id: int
    category_id: int
    name: str
    client_id: int | None = None
    domain: str | None = None


class AdsDeleteAds(VKMethod[list]):
    """Archives ads."""

    __returning__ = list
    __api_method__ = "ads.deleteAds"

    account_id: int
    ids: str


class AdsDeleteCampaigns(VKMethod[list]):
    """Archives advertising campaigns."""

    __returning__ = list
    __api_method__ = "ads.deleteCampaigns"

    account_id: int
    ids: str


class AdsDeleteClients(VKMethod[list]):
    """Archives clients of an advertising agency."""

    __returning__ = list
    __api_method__ = "ads.deleteClients"

    account_id: int
    ids: str


class AdsDeleteTargetGroup(VKMethod[int]):
    """Deletes a retarget group."""

    __returning__ = int
    __api_method__ = "ads.deleteTargetGroup"

    account_id: int
    target_group_id: int
    client_id: int | None = None


class AdsDeleteTargetPixel(VKMethod[dict]):
    """VK API method ads.deleteTargetPixel."""

    __returning__ = dict
    __api_method__ = "ads.deleteTargetPixel"

    account_id: int
    target_pixel_id: int
    client_id: int | None = None


class AdsGetAccounts(VKMethod[list]):
    """Returns a list of advertising accounts."""

    __returning__ = list
    __api_method__ = "ads.getAccounts"


class AdsGetAds(VKMethod[list]):
    """Returns number of ads."""

    __returning__ = list
    __api_method__ = "ads.getAds"

    account_id: int
    ad_ids: str | None = None
    campaign_ids: str | None = None
    client_id: int | None = None
    include_deleted: bool | None = None
    limit: int | None = None
    offset: int | None = None
    only_deleted: bool | None = None


class AdsGetAdsLayout(VKMethod[list]):
    """Returns descriptions of ad layouts."""

    __returning__ = list
    __api_method__ = "ads.getAdsLayout"

    account_id: int
    ad_ids: str | None = None
    campaign_ids: str | None = None
    client_id: int | None = None
    include_deleted: bool | None = None
    limit: int | None = None
    offset: int | None = None
    only_deleted: bool | None = None


class AdsGetAdsTargeting(VKMethod[list]):
    """Returns ad targeting parameters."""

    __returning__ = list
    __api_method__ = "ads.getAdsTargeting"

    account_id: int
    ad_ids: str | None = None
    campaign_ids: str | None = None
    client_id: int | None = None
    include_deleted: bool | None = None
    limit: int | None = None
    offset: int | None = None
    only_deleted: bool | None = None


class AdsGetBudget(VKMethod[dict]):
    """Returns current budget of the advertising account."""

    __returning__ = dict
    __api_method__ = "ads.getBudget"

    account_id: int


class AdsGetCampaigns(VKMethod[list]):
    """Returns a list of campaigns in an advertising account."""

    __returning__ = list
    __api_method__ = "ads.getCampaigns"

    account_id: int
    campaign_ids: str | None = None
    client_id: int | None = None
    fields: list[str] | None = None
    include_deleted: bool | None = None


class AdsGetCategories(VKMethod[dict]):
    """Returns a list of possible ad categories."""

    __returning__ = dict
    __api_method__ = "ads.getCategories"

    lang: str | None = None


class AdsGetClients(VKMethod[list]):
    """Returns a list of advertising agency's clients."""

    __returning__ = list
    __api_method__ = "ads.getClients"

    account_id: int


class AdsGetDemographics(VKMethod[list]):
    """Returns demographics for ads or campaigns."""

    __returning__ = list
    __api_method__ = "ads.getDemographics"

    account_id: int
    date_from: str
    date_to: str
    ids: str
    ids_type: str
    period: str


class AdsGetFloodStats(VKMethod[dict]):
    """Returns information about current state of a counter - number of remaining runs of methods and time to the next counter nulling in seconds."""

    __returning__ = dict
    __api_method__ = "ads.getFloodStats"

    account_id: int


class AdsGetLookalikeRequests(VKMethod[dict]):
    """VK API method ads.getLookalikeRequests."""

    __returning__ = dict
    __api_method__ = "ads.getLookalikeRequests"

    account_id: int
    client_id: int | None = None
    limit: int = 10
    offset: int = 0
    requests_ids: str | None = None
    sort_by: str = 'id'


class AdsGetMusicians(VKMethod[dict]):
    """VK API method ads.getMusicians."""

    __returning__ = dict
    __api_method__ = "ads.getMusicians"

    artist_name: str


class AdsGetMusiciansByIds(VKMethod[dict]):
    """VK API method ads.getMusiciansByIds."""

    __returning__ = dict
    __api_method__ = "ads.getMusiciansByIds"

    ids: list[int]


class AdsGetOfficeUsers(VKMethod[list]):
    """Returns a list of managers and supervisors of advertising account."""

    __returning__ = list
    __api_method__ = "ads.getOfficeUsers"

    account_id: int


class AdsGetPostsReach(VKMethod[list]):
    """Returns detailed statistics of promoted posts reach from campaigns and ads."""

    __returning__ = list
    __api_method__ = "ads.getPostsReach"

    account_id: int
    ids: str
    ids_type: str


class AdsGetRejectionReason(VKMethod[dict]):
    """Returns a reason of ad rejection for pre-moderation."""

    __returning__ = dict
    __api_method__ = "ads.getRejectionReason"

    account_id: int
    ad_id: int


class AdsGetStatistics(VKMethod[list]):
    """Returns statistics of performance indicators for ads, campaigns, clients or the whole account."""

    __returning__ = list
    __api_method__ = "ads.getStatistics"

    account_id: int
    date_from: str
    date_to: str
    ids: str
    ids_type: str
    period: str
    stats_fields: list[str] | None = None


class AdsGetSuggestions(VKMethod[list]):
    """Returns a set of auto-suggestions for various targeting parameters."""

    __returning__ = list
    __api_method__ = "ads.getSuggestions"

    section: str
    cities: str | None = None
    country: int | None = None
    ids: str | None = None
    lang: str | None = None
    q: str | None = None


class AdsGetTargetGroups(VKMethod[list]):
    """Returns a list of target groups."""

    __returning__ = list
    __api_method__ = "ads.getTargetGroups"

    account_id: int
    client_id: int | None = None
    extended: bool | None = None


class AdsGetTargetPixels(VKMethod[list]):
    """VK API method ads.getTargetPixels."""

    __returning__ = list
    __api_method__ = "ads.getTargetPixels"

    account_id: int
    client_id: int | None = None


class AdsGetTargetingStats(VKMethod[dict]):
    """Returns the size of targeting audience, and also recommended values for CPC and CPM."""

    __returning__ = dict
    __api_method__ = "ads.getTargetingStats"

    account_id: int
    link_url: str
    ad_format: int | None = None
    ad_id: int | None = None
    ad_platform: str | None = None
    ad_platform_no_ad_network: str | None = None
    ad_platform_no_wall: str | None = None
    client_id: int | None = None
    criteria: str | None = None
    impressions_limit_period: int | None = None
    link_domain: str | None = None
    need_precise: bool | None = None
    publisher_platforms: str | None = None


class AdsGetUploadURL(VKMethod[dict]):
    """Returns URL to upload an ad photo to."""

    __returning__ = dict
    __api_method__ = "ads.getUploadURL"

    ad_format: int
    icon: int | None = None


class AdsGetVideoUploadURL(VKMethod[dict]):
    """Returns URL to upload an ad video to."""

    __returning__ = dict
    __api_method__ = "ads.getVideoUploadURL"


class AdsImportTargetContacts(VKMethod[int]):
    """Imports a list of advertiser's contacts to count VK registered users against the target group."""

    __returning__ = int
    __api_method__ = "ads.importTargetContacts"

    account_id: int
    contacts: str
    target_group_id: int
    client_id: int | None = None


class AdsRemoveOfficeUsers(VKMethod[list]):
    """Removes managers and/or supervisors from advertising account."""

    __returning__ = list
    __api_method__ = "ads.removeOfficeUsers"

    account_id: int
    ids: str


class AdsRemoveTargetContacts(VKMethod[dict]):
    """VK API method ads.removeTargetContacts."""

    __returning__ = dict
    __api_method__ = "ads.removeTargetContacts"

    account_id: int
    contacts: str
    target_group_id: int
    client_id: int | None = None


class AdsSaveLookalikeRequestResult(VKMethod[dict]):
    """VK API method ads.saveLookalikeRequestResult."""

    __returning__ = dict
    __api_method__ = "ads.saveLookalikeRequestResult"

    account_id: int
    level: int
    request_id: int
    client_id: int | None = None


class AdsShareTargetGroup(VKMethod[dict]):
    """VK API method ads.shareTargetGroup."""

    __returning__ = dict
    __api_method__ = "ads.shareTargetGroup"

    account_id: int
    target_group_id: int
    client_id: int | None = None
    share_with_client_id: int | None = None


class AdsUpdateAds(VKMethod[list]):
    """Edits ads."""

    __returning__ = list
    __api_method__ = "ads.updateAds"

    account_id: int
    data: str


class AdsUpdateCampaigns(VKMethod[list]):
    """Edits advertising campaigns."""

    __returning__ = list
    __api_method__ = "ads.updateCampaigns"

    account_id: int
    data: str


class AdsUpdateClients(VKMethod[list]):
    """Edits clients of an advertising agency."""

    __returning__ = list
    __api_method__ = "ads.updateClients"

    account_id: int
    data: str


class AdsUpdateOfficeUsers(VKMethod[list]):
    """Adds managers and/or supervisors to advertising account."""

    __returning__ = list
    __api_method__ = "ads.updateOfficeUsers"

    account_id: int
    data: str


class AdsUpdateTargetGroup(VKMethod[int]):
    """Edits a retarget group."""

    __returning__ = int
    __api_method__ = "ads.updateTargetGroup"

    account_id: int
    lifetime: int
    name: str
    target_group_id: int
    client_id: int | None = None
    domain: str | None = None
    target_pixel_id: int | None = None
    target_pixel_rules: str | None = None


class AdsUpdateTargetPixel(VKMethod[dict]):
    """VK API method ads.updateTargetPixel."""

    __returning__ = dict
    __api_method__ = "ads.updateTargetPixel"

    account_id: int
    category_id: int
    name: str
    target_pixel_id: int
    client_id: int | None = None
    domain: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "ads.addOfficeUsers": AdsAddOfficeUsers,
    "ads.checkLink": AdsCheckLink,
    "ads.createAds": AdsCreateAds,
    "ads.createCampaigns": AdsCreateCampaigns,
    "ads.createClients": AdsCreateClients,
    "ads.createLookalikeRequest": AdsCreateLookalikeRequest,
    "ads.createTargetGroup": AdsCreateTargetGroup,
    "ads.createTargetPixel": AdsCreateTargetPixel,
    "ads.deleteAds": AdsDeleteAds,
    "ads.deleteCampaigns": AdsDeleteCampaigns,
    "ads.deleteClients": AdsDeleteClients,
    "ads.deleteTargetGroup": AdsDeleteTargetGroup,
    "ads.deleteTargetPixel": AdsDeleteTargetPixel,
    "ads.getAccounts": AdsGetAccounts,
    "ads.getAds": AdsGetAds,
    "ads.getAdsLayout": AdsGetAdsLayout,
    "ads.getAdsTargeting": AdsGetAdsTargeting,
    "ads.getBudget": AdsGetBudget,
    "ads.getCampaigns": AdsGetCampaigns,
    "ads.getCategories": AdsGetCategories,
    "ads.getClients": AdsGetClients,
    "ads.getDemographics": AdsGetDemographics,
    "ads.getFloodStats": AdsGetFloodStats,
    "ads.getLookalikeRequests": AdsGetLookalikeRequests,
    "ads.getMusicians": AdsGetMusicians,
    "ads.getMusiciansByIds": AdsGetMusiciansByIds,
    "ads.getOfficeUsers": AdsGetOfficeUsers,
    "ads.getPostsReach": AdsGetPostsReach,
    "ads.getRejectionReason": AdsGetRejectionReason,
    "ads.getStatistics": AdsGetStatistics,
    "ads.getSuggestions": AdsGetSuggestions,
    "ads.getTargetGroups": AdsGetTargetGroups,
    "ads.getTargetPixels": AdsGetTargetPixels,
    "ads.getTargetingStats": AdsGetTargetingStats,
    "ads.getUploadURL": AdsGetUploadURL,
    "ads.getVideoUploadURL": AdsGetVideoUploadURL,
    "ads.importTargetContacts": AdsImportTargetContacts,
    "ads.removeOfficeUsers": AdsRemoveOfficeUsers,
    "ads.removeTargetContacts": AdsRemoveTargetContacts,
    "ads.saveLookalikeRequestResult": AdsSaveLookalikeRequestResult,
    "ads.shareTargetGroup": AdsShareTargetGroup,
    "ads.updateAds": AdsUpdateAds,
    "ads.updateCampaigns": AdsUpdateCampaigns,
    "ads.updateClients": AdsUpdateClients,
    "ads.updateOfficeUsers": AdsUpdateOfficeUsers,
    "ads.updateTargetGroup": AdsUpdateTargetGroup,
    "ads.updateTargetPixel": AdsUpdateTargetPixel,
}

__all__ = ["AdsAddOfficeUsers", "AdsCheckLink", "AdsCreateAds", "AdsCreateCampaigns", "AdsCreateClients", "AdsCreateLookalikeRequest", "AdsCreateTargetGroup", "AdsCreateTargetPixel", "AdsDeleteAds", "AdsDeleteCampaigns", "AdsDeleteClients", "AdsDeleteTargetGroup", "AdsDeleteTargetPixel", "AdsGetAccounts", "AdsGetAds", "AdsGetAdsLayout", "AdsGetAdsTargeting", "AdsGetBudget", "AdsGetCampaigns", "AdsGetCategories", "AdsGetClients", "AdsGetDemographics", "AdsGetFloodStats", "AdsGetLookalikeRequests", "AdsGetMusicians", "AdsGetMusiciansByIds", "AdsGetOfficeUsers", "AdsGetPostsReach", "AdsGetRejectionReason", "AdsGetStatistics", "AdsGetSuggestions", "AdsGetTargetGroups", "AdsGetTargetPixels", "AdsGetTargetingStats", "AdsGetUploadURL", "AdsGetVideoUploadURL", "AdsImportTargetContacts", "AdsRemoveOfficeUsers", "AdsRemoveTargetContacts", "AdsSaveLookalikeRequestResult", "AdsShareTargetGroup", "AdsUpdateAds", "AdsUpdateCampaigns", "AdsUpdateClients", "AdsUpdateOfficeUsers", "AdsUpdateTargetGroup", "AdsUpdateTargetPixel"]
