"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from pydantic import Field

from ..base import VKMethod


class AppsAddSnippet(VKMethod[dict]):
    """VK API method apps.addSnippet."""

    __returning__ = dict
    __api_method__ = "apps.addSnippet"

    button: str | None = None
    description: str | None = None
    group_id: list[int] | None = None
    hash: list[str] | None = None
    image_url: str | None = None
    small_image_url: str | None = None
    snippet_id: int | None = None
    title: str | None = None
    vk_ref: list[str] | None = None


class AppsAddUsersToTestingGroup(VKMethod[int]):
    """VK API method apps.addUsersToTestingGroup."""

    __returning__ = int
    __api_method__ = "apps.addUsersToTestingGroup"

    group_id: int
    user_ids: list[int]


class AppsDeleteAppRequests(VKMethod[int]):
    """Deletes all request notifications from the current app."""

    __returning__ = int
    __api_method__ = "apps.deleteAppRequests"


class AppsDeleteSnippet(VKMethod[int]):
    """VK API method apps.deleteSnippet."""

    __returning__ = int
    __api_method__ = "apps.deleteSnippet"

    id: int | None = None


class AppsGet(VKMethod[dict]):
    """Returns applications data."""

    __returning__ = dict
    __api_method__ = "apps.get"

    app_fields: list[str] | None = None
    app_id: int | None = None
    app_ids: list[int] | None = None
    extended: bool = False
    fields: list[str] | None = None
    name_case: str | None = None
    platform: str = 'web'
    return_friends: bool = False


class AppsGetCatalog(VKMethod[dict]):
    """Returns a list of applications (apps) available to users in the App Catalog."""

    __returning__ = dict
    __api_method__ = "apps.getCatalog"

    count: int = 100
    extended: bool | None = None
    fields: list[str] | None = None
    filter: str | None = None
    genre_id: int | None = None
    name_case: str | None = None
    offset: int | None = None
    platform: str | None = None
    q: str | None = None
    return_friends: bool | None = None
    sort: str | None = None


class AppsGetFriendsList(VKMethod[dict]):
    """Creates friends list for requests and invites in current app."""

    __returning__ = dict
    __api_method__ = "apps.getFriendsList"

    count: int = 20
    extended: bool = False
    fields: list[str] | None = None
    offset: int = 0
    query: str | None = None
    type: str = 'invite'


class AppsGetLeaderboard(VKMethod[dict]):
    """Returns players rating in the game."""

    __returning__ = dict
    __api_method__ = "apps.getLeaderboard"

    type: str
    extended: bool = False
    global_: bool = Field(default=True, alias='global')


class AppsGetMiniAppPolicies(VKMethod[dict]):
    """Returns policies and terms given to a mini app."""

    __returning__ = dict
    __api_method__ = "apps.getMiniAppPolicies"

    app_id: int


class AppsGetScopes(VKMethod[dict]):
    """Returns scopes for auth"""

    __returning__ = dict
    __api_method__ = "apps.getScopes"

    type: str = 'user'


class AppsGetScore(VKMethod[int]):
    """Returns user score in app"""

    __returning__ = int
    __api_method__ = "apps.getScore"

    user_id: int | None = None


class AppsGetSnippets(VKMethod[dict]):
    """VK API method apps.getSnippets."""

    __returning__ = dict
    __api_method__ = "apps.getSnippets"


class AppsGetTestingGroups(VKMethod[list]):
    """VK API method apps.getTestingGroups."""

    __returning__ = list
    __api_method__ = "apps.getTestingGroups"

    group_id: int | None = None


class AppsIsNotificationsAllowed(VKMethod[dict]):
    """VK API method apps.isNotificationsAllowed."""

    __returning__ = dict
    __api_method__ = "apps.isNotificationsAllowed"

    user_id: int | None = None


class AppsPromoHasActiveGift(VKMethod[int]):
    """VK API method apps.promoHasActiveGift."""

    __returning__ = int
    __api_method__ = "apps.promoHasActiveGift"

    promo_id: int
    user_id: int | None = None


class AppsPromoUseGift(VKMethod[int]):
    """VK API method apps.promoUseGift."""

    __returning__ = int
    __api_method__ = "apps.promoUseGift"

    promo_id: int
    user_id: int | None = None


class AppsRemoveTestingGroup(VKMethod[int]):
    """VK API method apps.removeTestingGroup."""

    __returning__ = int
    __api_method__ = "apps.removeTestingGroup"

    group_id: int


class AppsRemoveUsersFromTestingGroups(VKMethod[int]):
    """VK API method apps.removeUsersFromTestingGroups."""

    __returning__ = int
    __api_method__ = "apps.removeUsersFromTestingGroups"

    user_ids: list[int]


class AppsSendRequest(VKMethod[int]):
    """Sends a request to another user in an app that uses VK authorization."""

    __returning__ = int
    __api_method__ = "apps.sendRequest"

    user_id: int
    key: str | None = None
    name: str | None = None
    separate: bool | None = None
    text: str | None = None
    type: str = 'request'


class AppsUpdateMetaForTestingGroup(VKMethod[dict]):
    """VK API method apps.updateMetaForTestingGroup."""

    __returning__ = dict
    __api_method__ = "apps.updateMetaForTestingGroup"

    name: str
    platforms: list[str]
    webview: str
    group_id: int | None = None
    user_ids: list[int] | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "apps.addSnippet": AppsAddSnippet,
    "apps.addUsersToTestingGroup": AppsAddUsersToTestingGroup,
    "apps.deleteAppRequests": AppsDeleteAppRequests,
    "apps.deleteSnippet": AppsDeleteSnippet,
    "apps.get": AppsGet,
    "apps.getCatalog": AppsGetCatalog,
    "apps.getFriendsList": AppsGetFriendsList,
    "apps.getLeaderboard": AppsGetLeaderboard,
    "apps.getMiniAppPolicies": AppsGetMiniAppPolicies,
    "apps.getScopes": AppsGetScopes,
    "apps.getScore": AppsGetScore,
    "apps.getSnippets": AppsGetSnippets,
    "apps.getTestingGroups": AppsGetTestingGroups,
    "apps.isNotificationsAllowed": AppsIsNotificationsAllowed,
    "apps.promoHasActiveGift": AppsPromoHasActiveGift,
    "apps.promoUseGift": AppsPromoUseGift,
    "apps.removeTestingGroup": AppsRemoveTestingGroup,
    "apps.removeUsersFromTestingGroups": AppsRemoveUsersFromTestingGroups,
    "apps.sendRequest": AppsSendRequest,
    "apps.updateMetaForTestingGroup": AppsUpdateMetaForTestingGroup,
}

__all__ = ["AppsAddSnippet", "AppsAddUsersToTestingGroup", "AppsDeleteAppRequests", "AppsDeleteSnippet", "AppsGet", "AppsGetCatalog", "AppsGetFriendsList", "AppsGetLeaderboard", "AppsGetMiniAppPolicies", "AppsGetScopes", "AppsGetScore", "AppsGetSnippets", "AppsGetTestingGroups", "AppsIsNotificationsAllowed", "AppsPromoHasActiveGift", "AppsPromoUseGift", "AppsRemoveTestingGroup", "AppsRemoveUsersFromTestingGroups", "AppsSendRequest", "AppsUpdateMetaForTestingGroup"]
