"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class AppWidgetsGetAppImageUploadServer(VKMethod[dict]):
    """Returns a URL for uploading a photo to the community collection for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.getAppImageUploadServer"

    image_type: str


class AppWidgetsGetAppImages(VKMethod[dict]):
    """Returns an app collection of images for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.getAppImages"

    count: int = 20
    image_type: str | None = None
    offset: int | None = None


class AppWidgetsGetGroupImageUploadServer(VKMethod[dict]):
    """Returns a URL for uploading a photo to the community collection for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.getGroupImageUploadServer"

    image_type: str


class AppWidgetsGetGroupImages(VKMethod[dict]):
    """Returns a community collection of images for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.getGroupImages"

    count: int = 20
    image_type: str | None = None
    offset: int | None = None


class AppWidgetsGetImagesById(VKMethod[list]):
    """Returns an image for community app widgets by its ID"""

    __returning__ = list
    __api_method__ = "appWidgets.getImagesById"

    images: list[str]


class AppWidgetsSaveAppImage(VKMethod[dict]):
    """Allows to save image into app collection for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.saveAppImage"

    hash: str
    image: str


class AppWidgetsSaveGroupImage(VKMethod[dict]):
    """Allows to save image into community collection for community app widgets"""

    __returning__ = dict
    __api_method__ = "appWidgets.saveGroupImage"

    hash: str
    image: str


class AppWidgetsUpdate(VKMethod[int]):
    """Allows to update community app widget"""

    __returning__ = int
    __api_method__ = "appWidgets.update"

    code: str
    type: str



REGISTRY: dict[str, type[VKMethod]] = {
    "appWidgets.getAppImageUploadServer": AppWidgetsGetAppImageUploadServer,
    "appWidgets.getAppImages": AppWidgetsGetAppImages,
    "appWidgets.getGroupImageUploadServer": AppWidgetsGetGroupImageUploadServer,
    "appWidgets.getGroupImages": AppWidgetsGetGroupImages,
    "appWidgets.getImagesById": AppWidgetsGetImagesById,
    "appWidgets.saveAppImage": AppWidgetsSaveAppImage,
    "appWidgets.saveGroupImage": AppWidgetsSaveGroupImage,
    "appWidgets.update": AppWidgetsUpdate,
}

__all__ = ["AppWidgetsGetAppImageUploadServer", "AppWidgetsGetAppImages", "AppWidgetsGetGroupImageUploadServer", "AppWidgetsGetGroupImages", "AppWidgetsGetImagesById", "AppWidgetsSaveAppImage", "AppWidgetsSaveGroupImage", "AppWidgetsUpdate"]
