"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class AuthRestore(VKMethod[dict]):
    """Allows to restore account access using a code received via SMS. " This method is only available for apps with [vk.com/dev/auth_direct|Direct authorization] access. " """

    __returning__ = dict
    __api_method__ = "auth.restore"

    last_name: str
    phone: str



REGISTRY: dict[str, type[VKMethod]] = {
    "auth.restore": AuthRestore,
}

__all__ = ["AuthRestore"]
