"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class BoardAddTopic(VKMethod[int]):
    """Creates a new topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.addTopic"

    group_id: int
    title: str
    attachments: list[str] | None = None
    from_group: bool | None = None
    text: str | None = None


class BoardCloseTopic(VKMethod[int]):
    """Closes a topic on a community's discussion board so that comments cannot be posted."""

    __returning__ = int
    __api_method__ = "board.closeTopic"

    group_id: int
    topic_id: int


class BoardCreateComment(VKMethod[int]):
    """Adds a comment on a topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.createComment"

    group_id: int
    topic_id: int
    attachments: list[str] | None = None
    from_group: bool | None = None
    guid: str | None = None
    message: str | None = None
    sticker_id: int | None = None


class BoardDeleteComment(VKMethod[int]):
    """Deletes a comment on a topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.deleteComment"

    comment_id: int
    group_id: int
    topic_id: int


class BoardDeleteTopic(VKMethod[int]):
    """Deletes a topic from a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.deleteTopic"

    group_id: int
    topic_id: int


class BoardEditComment(VKMethod[int]):
    """Edits a comment on a topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.editComment"

    comment_id: int
    group_id: int
    topic_id: int
    attachments: list[str] | None = None
    message: str | None = None


class BoardEditTopic(VKMethod[int]):
    """Edits the title of a topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.editTopic"

    group_id: int
    title: str
    topic_id: int


class BoardFixTopic(VKMethod[int]):
    """Pins a topic (fixes its place) to the top of a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.fixTopic"

    group_id: int
    topic_id: int


class BoardGetComments(VKMethod[dict]):
    """Returns a list of comments on a topic on a community's discussion board."""

    __returning__ = dict
    __api_method__ = "board.getComments"

    group_id: int
    topic_id: int
    count: int = 20
    extended: bool | None = None
    need_likes: bool | None = None
    offset: int | None = None
    sort: str | None = None
    start_comment_id: int | None = None


class BoardGetTopics(VKMethod[dict]):
    """Returns a list of topics on a community's discussion board."""

    __returning__ = dict
    __api_method__ = "board.getTopics"

    group_id: int
    count: int = 40
    extended: bool | None = None
    offset: int | None = None
    order: int | None = None
    preview: int | None = None
    preview_length: int = 90
    topic_ids: list[int] | None = None


class BoardOpenTopic(VKMethod[int]):
    """Re-opens a previously closed topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.openTopic"

    group_id: int
    topic_id: int


class BoardRestoreComment(VKMethod[int]):
    """Restores a comment deleted from a topic on a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.restoreComment"

    comment_id: int
    group_id: int
    topic_id: int


class BoardUnfixTopic(VKMethod[int]):
    """Unpins a pinned topic from the top of a community's discussion board."""

    __returning__ = int
    __api_method__ = "board.unfixTopic"

    group_id: int
    topic_id: int



REGISTRY: dict[str, type[VKMethod]] = {
    "board.addTopic": BoardAddTopic,
    "board.closeTopic": BoardCloseTopic,
    "board.createComment": BoardCreateComment,
    "board.deleteComment": BoardDeleteComment,
    "board.deleteTopic": BoardDeleteTopic,
    "board.editComment": BoardEditComment,
    "board.editTopic": BoardEditTopic,
    "board.fixTopic": BoardFixTopic,
    "board.getComments": BoardGetComments,
    "board.getTopics": BoardGetTopics,
    "board.openTopic": BoardOpenTopic,
    "board.restoreComment": BoardRestoreComment,
    "board.unfixTopic": BoardUnfixTopic,
}

__all__ = ["BoardAddTopic", "BoardCloseTopic", "BoardCreateComment", "BoardDeleteComment", "BoardDeleteTopic", "BoardEditComment", "BoardEditTopic", "BoardFixTopic", "BoardGetComments", "BoardGetTopics", "BoardOpenTopic", "BoardRestoreComment", "BoardUnfixTopic"]
