"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class BugtrackerAddCompanyGroupsMembers(VKMethod[dict]):
    """VK API method bugtracker.addCompanyGroupsMembers."""

    __returning__ = dict
    __api_method__ = "bugtracker.addCompanyGroupsMembers"

    company_group_ids: list[int]
    company_id: int
    user_ids: list[int]


class BugtrackerAddCompanyMembers(VKMethod[dict]):
    """VK API method bugtracker.addCompanyMembers."""

    __returning__ = dict
    __api_method__ = "bugtracker.addCompanyMembers"

    company_id: int
    user_ids: list[int]


class BugtrackerChangeBugreportStatus(VKMethod[int]):
    """VK API method bugtracker.changeBugreportStatus."""

    __returning__ = int
    __api_method__ = "bugtracker.changeBugreportStatus"

    bugreport_id: int
    comment: str | None = None
    from_statuses: list[int] | None = None
    not_in_statuses: list[int] | None = None
    status: int | None = None


class BugtrackerCreateComment(VKMethod[dict]):
    """Creates the comment to bugreport"""

    __returning__ = dict
    __api_method__ = "bugtracker.createComment"

    bugreport_id: int
    force: bool | None = None
    hidden: bool | None = None
    hidden_attachments: bool | None = None
    text: str | None = None


class BugtrackerGetBugreportById(VKMethod[dict]):
    """Returns extended bugreport data"""

    __returning__ = dict
    __api_method__ = "bugtracker.getBugreportById"

    bugreport_id: int
    extended: bool | None = None
    fields: list[str] | None = None


class BugtrackerGetCompanyGroupMembers(VKMethod[dict]):
    """VK API method bugtracker.getCompanyGroupMembers."""

    __returning__ = dict
    __api_method__ = "bugtracker.getCompanyGroupMembers"

    company_group_id: int
    company_id: int
    count: int = 10
    extended: bool | None = None
    fields: list[str] | None = None
    filter_name: str = ''
    offset: int = 0


class BugtrackerGetCompanyMembers(VKMethod[dict]):
    """VK API method bugtracker.getCompanyMembers."""

    __returning__ = dict
    __api_method__ = "bugtracker.getCompanyMembers"

    company_id: int
    count: int = 10
    extended: bool | None = None
    extra: bool = False
    fields: list[str] | None = None
    filter_member_ids: list[int] | None = None
    filter_name: str = ''
    filter_not_group: int = 0
    filter_role: int | None = None
    offset: int = 0


class BugtrackerGetDownloadVersionUrl(VKMethod[dict]):
    """VK API method bugtracker.getDownloadVersionUrl."""

    __returning__ = dict
    __api_method__ = "bugtracker.getDownloadVersionUrl"

    product_id: int
    version_id: int
    ttl: int = 600


class BugtrackerGetProductBuildUploadServer(VKMethod[dict]):
    """VK API method bugtracker.getProductBuildUploadServer."""

    __returning__ = dict
    __api_method__ = "bugtracker.getProductBuildUploadServer"

    product_id: int


class BugtrackerRemoveCompanyGroupMember(VKMethod[int]):
    """VK API method bugtracker.removeCompanyGroupMember."""

    __returning__ = int
    __api_method__ = "bugtracker.removeCompanyGroupMember"

    company_group_id: int
    company_id: int
    user_id: int


class BugtrackerRemoveCompanyMember(VKMethod[int]):
    """VK API method bugtracker.removeCompanyMember."""

    __returning__ = int
    __api_method__ = "bugtracker.removeCompanyMember"

    company_id: int
    user_id: int


class BugtrackerSaveProductVersion(VKMethod[int]):
    """VK API method bugtracker.saveProductVersion."""

    __returning__ = int
    __api_method__ = "bugtracker.saveProductVersion"

    title: str
    product_id: int | None = None
    release_notes: str | None = None
    set_rft: bool = False
    version_id: int = 0
    visible: bool | None = None


class BugtrackerSetCompanyMemberRole(VKMethod[int]):
    """VK API method bugtracker.setCompanyMemberRole."""

    __returning__ = int
    __api_method__ = "bugtracker.setCompanyMemberRole"

    company_id: int
    role: int
    user_id: int


class BugtrackerSetProductIsOver(VKMethod[int]):
    """VK API method bugtracker.setProductIsOver."""

    __returning__ = int
    __api_method__ = "bugtracker.setProductIsOver"

    product_id: int
    is_over: bool | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "bugtracker.addCompanyGroupsMembers": BugtrackerAddCompanyGroupsMembers,
    "bugtracker.addCompanyMembers": BugtrackerAddCompanyMembers,
    "bugtracker.changeBugreportStatus": BugtrackerChangeBugreportStatus,
    "bugtracker.createComment": BugtrackerCreateComment,
    "bugtracker.getBugreportById": BugtrackerGetBugreportById,
    "bugtracker.getCompanyGroupMembers": BugtrackerGetCompanyGroupMembers,
    "bugtracker.getCompanyMembers": BugtrackerGetCompanyMembers,
    "bugtracker.getDownloadVersionUrl": BugtrackerGetDownloadVersionUrl,
    "bugtracker.getProductBuildUploadServer": BugtrackerGetProductBuildUploadServer,
    "bugtracker.removeCompanyGroupMember": BugtrackerRemoveCompanyGroupMember,
    "bugtracker.removeCompanyMember": BugtrackerRemoveCompanyMember,
    "bugtracker.saveProductVersion": BugtrackerSaveProductVersion,
    "bugtracker.setCompanyMemberRole": BugtrackerSetCompanyMemberRole,
    "bugtracker.setProductIsOver": BugtrackerSetProductIsOver,
}

__all__ = ["BugtrackerAddCompanyGroupsMembers", "BugtrackerAddCompanyMembers", "BugtrackerChangeBugreportStatus", "BugtrackerCreateComment", "BugtrackerGetBugreportById", "BugtrackerGetCompanyGroupMembers", "BugtrackerGetCompanyMembers", "BugtrackerGetDownloadVersionUrl", "BugtrackerGetProductBuildUploadServer", "BugtrackerRemoveCompanyGroupMember", "BugtrackerRemoveCompanyMember", "BugtrackerSaveProductVersion", "BugtrackerSetCompanyMemberRole", "BugtrackerSetProductIsOver"]
