"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class CallsForceFinish(VKMethod[int]):
    """VK API method calls.forceFinish."""

    __returning__ = int
    __api_method__ = "calls.forceFinish"

    call_id: str


class CallsStart(VKMethod[dict]):
    """VK API method calls.start."""

    __returning__ = dict
    __api_method__ = "calls.start"

    group_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "calls.forceFinish": CallsForceFinish,
    "calls.start": CallsStart,
}

__all__ = ["CallsForceFinish", "CallsStart"]
