"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class DatabaseGetChairs(VKMethod[dict]):
    """Returns list of chairs on a specified faculty."""

    __returning__ = dict
    __api_method__ = "database.getChairs"

    faculty_id: int
    count: int = 100
    offset: int | None = None


class DatabaseGetCities(VKMethod[dict]):
    """Returns a list of cities."""

    __returning__ = dict
    __api_method__ = "database.getCities"

    count: int = 100
    fields: list[str] | None = None
    need_all: bool | None = None
    offset: int | None = None
    q: str | None = None
    region_id: int | None = None


class DatabaseGetCitiesById(VKMethod[list]):
    """Returns information about cities by their IDs."""

    __returning__ = list
    __api_method__ = "database.getCitiesById"

    city_ids: list[int] | None = None
    fields: list[str] | None = None


class DatabaseGetCountries(VKMethod[dict]):
    """Returns a list of countries."""

    __returning__ = dict
    __api_method__ = "database.getCountries"

    code: str | None = None
    count: int = 100
    need_all: bool | None = None
    offset: int | None = None


class DatabaseGetCountriesById(VKMethod[list]):
    """Returns information about countries by their IDs."""

    __returning__ = list
    __api_method__ = "database.getCountriesById"

    country_ids: list[int] | None = None


class DatabaseGetFaculties(VKMethod[dict]):
    """Returns a list of faculties (i.e., university departments)."""

    __returning__ = dict
    __api_method__ = "database.getFaculties"

    university_id: int
    count: int = 100
    offset: int | None = None


class DatabaseGetMetroStations(VKMethod[dict]):
    """Get metro stations by city"""

    __returning__ = dict
    __api_method__ = "database.getMetroStations"

    city_id: int
    count: int = 100
    extended: bool = False
    offset: int | None = None


class DatabaseGetMetroStationsById(VKMethod[list]):
    """Get metro station by his id"""

    __returning__ = list
    __api_method__ = "database.getMetroStationsById"

    station_ids: list[int] | None = None


class DatabaseGetRegions(VKMethod[dict]):
    """Returns a list of regions."""

    __returning__ = dict
    __api_method__ = "database.getRegions"

    count: int = 100
    offset: int | None = None
    q: str | None = None


class DatabaseGetSchoolClasses(VKMethod[list]):
    """Returns a list of school classes specified for the country."""

    __returning__ = list
    __api_method__ = "database.getSchoolClasses"

    country_id: int | None = None


class DatabaseGetSchools(VKMethod[dict]):
    """Returns a list of schools."""

    __returning__ = dict
    __api_method__ = "database.getSchools"

    city_id: int
    count: int = 100
    offset: int | None = None
    q: str | None = None


class DatabaseGetUniversities(VKMethod[dict]):
    """Returns a list of higher education institutions."""

    __returning__ = dict
    __api_method__ = "database.getUniversities"

    city_id: int | None = None
    count: int = 100
    offset: int | None = None
    q: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "database.getChairs": DatabaseGetChairs,
    "database.getCities": DatabaseGetCities,
    "database.getCitiesById": DatabaseGetCitiesById,
    "database.getCountries": DatabaseGetCountries,
    "database.getCountriesById": DatabaseGetCountriesById,
    "database.getFaculties": DatabaseGetFaculties,
    "database.getMetroStations": DatabaseGetMetroStations,
    "database.getMetroStationsById": DatabaseGetMetroStationsById,
    "database.getRegions": DatabaseGetRegions,
    "database.getSchoolClasses": DatabaseGetSchoolClasses,
    "database.getSchools": DatabaseGetSchools,
    "database.getUniversities": DatabaseGetUniversities,
}

__all__ = ["DatabaseGetChairs", "DatabaseGetCities", "DatabaseGetCitiesById", "DatabaseGetCountries", "DatabaseGetCountriesById", "DatabaseGetFaculties", "DatabaseGetMetroStations", "DatabaseGetMetroStationsById", "DatabaseGetRegions", "DatabaseGetSchoolClasses", "DatabaseGetSchools", "DatabaseGetUniversities"]
