"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class DocsAdd(VKMethod[int]):
    """Copies a document to a user's or community's document list."""

    __returning__ = int
    __api_method__ = "docs.add"

    doc_id: int
    owner_id: int
    access_key: str | None = None


class DocsDelete(VKMethod[int]):
    """Deletes a user or community document."""

    __returning__ = int
    __api_method__ = "docs.delete"

    doc_id: int
    owner_id: int


class DocsEdit(VKMethod[int]):
    """Edits a document."""

    __returning__ = int
    __api_method__ = "docs.edit"

    doc_id: int
    title: str
    owner_id: int | None = None
    tags: list[str] | None = None


class DocsGet(VKMethod[dict]):
    """Returns detailed information about user or community documents."""

    __returning__ = dict
    __api_method__ = "docs.get"

    count: int | None = None
    offset: int | None = None
    owner_id: int | None = None
    return_tags: bool = False
    type: int = 0


class DocsGetById(VKMethod[list]):
    """Returns information about documents by their IDs."""

    __returning__ = list
    __api_method__ = "docs.getById"

    docs: list[str]
    return_tags: bool = False


class DocsGetMessagesUploadServer(VKMethod[dict]):
    """Returns the server address for document upload."""

    __returning__ = dict
    __api_method__ = "docs.getMessagesUploadServer"

    peer_id: int | None = None
    type: str = 'doc'


class DocsGetTypes(VKMethod[dict]):
    """Returns documents types available for current user."""

    __returning__ = dict
    __api_method__ = "docs.getTypes"

    owner_id: int | None = None


class DocsGetUploadServer(VKMethod[dict]):
    """Returns the server address for document upload."""

    __returning__ = dict
    __api_method__ = "docs.getUploadServer"

    group_id: int | None = None


class DocsGetWallUploadServer(VKMethod[dict]):
    """Returns the server address for document upload onto a user's or community's wall."""

    __returning__ = dict
    __api_method__ = "docs.getWallUploadServer"

    group_id: int | None = None


class DocsRestore(VKMethod[int]):
    """VK API method docs.restore."""

    __returning__ = int
    __api_method__ = "docs.restore"

    doc_id: int
    owner_id: int


class DocsSave(VKMethod[dict]):
    """Saves a document after [vk.com/dev/upload_files_2|uploading it to a server]."""

    __returning__ = dict
    __api_method__ = "docs.save"

    file: str
    return_tags: bool = False
    tags: str | None = None
    title: str | None = None


class DocsSearch(VKMethod[dict]):
    """Returns a list of documents matching the search criteria."""

    __returning__ = dict
    __api_method__ = "docs.search"

    count: int = 20
    offset: int | None = None
    q: str | None = None
    return_tags: bool | None = None
    search_own: bool | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "docs.add": DocsAdd,
    "docs.delete": DocsDelete,
    "docs.edit": DocsEdit,
    "docs.get": DocsGet,
    "docs.getById": DocsGetById,
    "docs.getMessagesUploadServer": DocsGetMessagesUploadServer,
    "docs.getTypes": DocsGetTypes,
    "docs.getUploadServer": DocsGetUploadServer,
    "docs.getWallUploadServer": DocsGetWallUploadServer,
    "docs.restore": DocsRestore,
    "docs.save": DocsSave,
    "docs.search": DocsSearch,
}

__all__ = ["DocsAdd", "DocsDelete", "DocsEdit", "DocsGet", "DocsGetById", "DocsGetMessagesUploadServer", "DocsGetTypes", "DocsGetUploadServer", "DocsGetWallUploadServer", "DocsRestore", "DocsSave", "DocsSearch"]
