"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class DonutGetFriends(VKMethod[dict]):
    """VK API method donut.getFriends."""

    __returning__ = dict
    __api_method__ = "donut.getFriends"

    owner_id: int
    count: int = 10
    fields: list[str] | None = None
    offset: int = 0


class DonutGetSubscription(VKMethod[dict]):
    """VK API method donut.getSubscription."""

    __returning__ = dict
    __api_method__ = "donut.getSubscription"

    owner_id: int


class DonutGetSubscriptions(VKMethod[dict]):
    """Returns a list of user's VK Donut subscriptions."""

    __returning__ = dict
    __api_method__ = "donut.getSubscriptions"

    count: int = 10
    fields: list[str] | None = None
    offset: int = 0


class DonutIsDon(VKMethod[int]):
    """VK API method donut.isDon."""

    __returning__ = int
    __api_method__ = "donut.isDon"

    owner_id: int



REGISTRY: dict[str, type[VKMethod]] = {
    "donut.getFriends": DonutGetFriends,
    "donut.getSubscription": DonutGetSubscription,
    "donut.getSubscriptions": DonutGetSubscriptions,
    "donut.isDon": DonutIsDon,
}

__all__ = ["DonutGetFriends", "DonutGetSubscription", "DonutGetSubscriptions", "DonutIsDon"]
