"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class DownloadedGamesGetPaidStatus(VKMethod[dict]):
    """VK API method downloadedGames.getPaidStatus."""

    __returning__ = dict
    __api_method__ = "downloadedGames.getPaidStatus"

    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "downloadedGames.getPaidStatus": DownloadedGamesGetPaidStatus,
}

__all__ = ["DownloadedGamesGetPaidStatus"]
