"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class Execute(VKMethod[dict]):
    """VK API method execute."""

    __returning__ = dict
    __api_method__ = "execute"



REGISTRY: dict[str, type[VKMethod]] = {
    "execute": Execute,
}

__all__ = ["Execute"]
