"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class FaveAddArticle(VKMethod[int]):
    """VK API method fave.addArticle."""

    __returning__ = int
    __api_method__ = "fave.addArticle"

    url: str


class FaveAddLink(VKMethod[int]):
    """Adds a link to user faves."""

    __returning__ = int
    __api_method__ = "fave.addLink"

    link: str


class FaveAddPage(VKMethod[int]):
    """VK API method fave.addPage."""

    __returning__ = int
    __api_method__ = "fave.addPage"

    group_id: int | None = None
    user_id: int | None = None


class FaveAddPost(VKMethod[int]):
    """VK API method fave.addPost."""

    __returning__ = int
    __api_method__ = "fave.addPost"

    id: int
    owner_id: int
    access_key: str | None = None


class FaveAddProduct(VKMethod[int]):
    """VK API method fave.addProduct."""

    __returning__ = int
    __api_method__ = "fave.addProduct"

    id: int
    owner_id: int
    access_key: str | None = None


class FaveAddTag(VKMethod[dict]):
    """VK API method fave.addTag."""

    __returning__ = dict
    __api_method__ = "fave.addTag"

    name: str | None = None
    position: str = 'back'


class FaveAddVideo(VKMethod[int]):
    """VK API method fave.addVideo."""

    __returning__ = int
    __api_method__ = "fave.addVideo"

    id: int
    owner_id: int
    access_key: str | None = None


class FaveEditTag(VKMethod[int]):
    """VK API method fave.editTag."""

    __returning__ = int
    __api_method__ = "fave.editTag"

    id: int
    name: str


class FaveGet(VKMethod[dict]):
    """VK API method fave.get."""

    __returning__ = dict
    __api_method__ = "fave.get"

    count: int = 50
    extended: bool = False
    fields: str | None = None
    is_from_snackbar: bool | None = None
    item_type: str | None = None
    offset: int | None = None
    tag_id: int | None = None


class FaveGetPages(VKMethod[dict]):
    """VK API method fave.getPages."""

    __returning__ = dict
    __api_method__ = "fave.getPages"

    count: int = 50
    fields: list[str] | None = None
    offset: int | None = None
    tag_id: int | None = None
    type: str | None = None


class FaveGetTags(VKMethod[dict]):
    """VK API method fave.getTags."""

    __returning__ = dict
    __api_method__ = "fave.getTags"


class FaveMarkSeen(VKMethod[int]):
    """VK API method fave.markSeen."""

    __returning__ = int
    __api_method__ = "fave.markSeen"


class FaveRemoveArticle(VKMethod[int]):
    """VK API method fave.removeArticle."""

    __returning__ = int
    __api_method__ = "fave.removeArticle"

    article_id: int
    owner_id: int


class FaveRemoveLink(VKMethod[int]):
    """Removes link from the user's faves."""

    __returning__ = int
    __api_method__ = "fave.removeLink"

    link: str | None = None
    link_id: str | None = None


class FaveRemovePage(VKMethod[int]):
    """VK API method fave.removePage."""

    __returning__ = int
    __api_method__ = "fave.removePage"

    group_id: int | None = None
    user_id: int | None = None


class FaveRemovePost(VKMethod[int]):
    """VK API method fave.removePost."""

    __returning__ = int
    __api_method__ = "fave.removePost"

    id: int
    owner_id: int


class FaveRemoveProduct(VKMethod[int]):
    """VK API method fave.removeProduct."""

    __returning__ = int
    __api_method__ = "fave.removeProduct"

    id: int
    owner_id: int


class FaveRemoveTag(VKMethod[int]):
    """VK API method fave.removeTag."""

    __returning__ = int
    __api_method__ = "fave.removeTag"

    id: int


class FaveRemoveVideo(VKMethod[int]):
    """VK API method fave.removeVideo."""

    __returning__ = int
    __api_method__ = "fave.removeVideo"

    id: int
    owner_id: int


class FaveReorderTags(VKMethod[int]):
    """VK API method fave.reorderTags."""

    __returning__ = int
    __api_method__ = "fave.reorderTags"

    ids: list[int]


class FaveSetPageTags(VKMethod[int]):
    """VK API method fave.setPageTags."""

    __returning__ = int
    __api_method__ = "fave.setPageTags"

    group_id: int | None = None
    tag_ids: list[int] | None = None
    user_id: int | None = None


class FaveSetTags(VKMethod[int]):
    """VK API method fave.setTags."""

    __returning__ = int
    __api_method__ = "fave.setTags"

    item_id: int | None = None
    item_owner_id: int | None = None
    item_type: str | None = None
    link_id: str | None = None
    link_url: str | None = None
    tag_ids: list[int] | None = None


class FaveTrackPageInteraction(VKMethod[int]):
    """VK API method fave.trackPageInteraction."""

    __returning__ = int
    __api_method__ = "fave.trackPageInteraction"

    group_id: int | None = None
    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "fave.addArticle": FaveAddArticle,
    "fave.addLink": FaveAddLink,
    "fave.addPage": FaveAddPage,
    "fave.addPost": FaveAddPost,
    "fave.addProduct": FaveAddProduct,
    "fave.addTag": FaveAddTag,
    "fave.addVideo": FaveAddVideo,
    "fave.editTag": FaveEditTag,
    "fave.get": FaveGet,
    "fave.getPages": FaveGetPages,
    "fave.getTags": FaveGetTags,
    "fave.markSeen": FaveMarkSeen,
    "fave.removeArticle": FaveRemoveArticle,
    "fave.removeLink": FaveRemoveLink,
    "fave.removePage": FaveRemovePage,
    "fave.removePost": FaveRemovePost,
    "fave.removeProduct": FaveRemoveProduct,
    "fave.removeTag": FaveRemoveTag,
    "fave.removeVideo": FaveRemoveVideo,
    "fave.reorderTags": FaveReorderTags,
    "fave.setPageTags": FaveSetPageTags,
    "fave.setTags": FaveSetTags,
    "fave.trackPageInteraction": FaveTrackPageInteraction,
}

__all__ = ["FaveAddArticle", "FaveAddLink", "FaveAddPage", "FaveAddPost", "FaveAddProduct", "FaveAddTag", "FaveAddVideo", "FaveEditTag", "FaveGet", "FaveGetPages", "FaveGetTags", "FaveMarkSeen", "FaveRemoveArticle", "FaveRemoveLink", "FaveRemovePage", "FaveRemovePost", "FaveRemoveProduct", "FaveRemoveTag", "FaveRemoveVideo", "FaveReorderTags", "FaveSetPageTags", "FaveSetTags", "FaveTrackPageInteraction"]
