"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class FriendsAdd(VKMethod[int]):
    """Approves or creates a friend request."""

    __returning__ = int
    __api_method__ = "friends.add"

    follow: bool | None = None
    text: str | None = None
    user_id: int | None = None


class FriendsAddList(VKMethod[dict]):
    """Creates a new friend list for the current user."""

    __returning__ = dict
    __api_method__ = "friends.addList"

    name: str
    user_ids: list[int] | None = None


class FriendsAreFriends(VKMethod[list]):
    """Checks the current user's friendship status with other specified users."""

    __returning__ = list
    __api_method__ = "friends.areFriends"

    user_ids: list[int]
    extended: bool | None = None
    need_sign: bool | None = None


class FriendsDelete(VKMethod[dict]):
    """Declines a friend request or deletes a user from the current user's friend list."""

    __returning__ = dict
    __api_method__ = "friends.delete"

    user_id: int | None = None


class FriendsDeleteAllRequests(VKMethod[int]):
    """Marks all incoming friend requests as viewed."""

    __returning__ = int
    __api_method__ = "friends.deleteAllRequests"


class FriendsDeleteList(VKMethod[int]):
    """Deletes a friend list of the current user."""

    __returning__ = int
    __api_method__ = "friends.deleteList"

    list_id: int


class FriendsEdit(VKMethod[int]):
    """Edits the friend lists of the selected user."""

    __returning__ = int
    __api_method__ = "friends.edit"

    user_id: int
    list_ids: list[int] | None = None


class FriendsEditList(VKMethod[int]):
    """Edits a friend list of the current user."""

    __returning__ = int
    __api_method__ = "friends.editList"

    list_id: int
    add_user_ids: list[int] | None = None
    delete_user_ids: list[int] | None = None
    name: str | None = None
    user_ids: list[int] | None = None


class FriendsGet(VKMethod[dict]):
    """Returns a list of user IDs or detailed information about a user's friends."""

    __returning__ = dict
    __api_method__ = "friends.get"

    count: int = 5000
    fields: list[str] | None = None
    list_id: int | None = None
    offset: int | None = None
    order: str | None = None
    ref: str | None = None
    user_id: int | None = None


class FriendsGetAppUsers(VKMethod[list]):
    """Returns a list of IDs of the current user's friends who installed the application."""

    __returning__ = list
    __api_method__ = "friends.getAppUsers"


class FriendsGetLists(VKMethod[dict]):
    """Returns a list of the user's friend lists."""

    __returning__ = dict
    __api_method__ = "friends.getLists"

    return_system: bool | None = None
    user_id: int | None = None


class FriendsGetMutual(VKMethod[list]):
    """Returns a list of user IDs of the mutual friends of two users."""

    __returning__ = list
    __api_method__ = "friends.getMutual"

    count: int | None = None
    need_common_count: bool | None = None
    offset: int | None = None
    order: str | None = None
    source_uid: int | None = None
    target_uid: int | None = None
    target_uids: list[int] | None = None


class FriendsGetOnline(VKMethod[list]):
    """Returns a list of user IDs of a user's friends who are online."""

    __returning__ = list
    __api_method__ = "friends.getOnline"

    count: int | None = None
    list_id: int | None = None
    offset: int | None = None
    online_mobile: bool | None = None
    order: str | None = None
    user_id: int | None = None


class FriendsGetRecent(VKMethod[list]):
    """Returns a list of user IDs of the current user's recently added friends."""

    __returning__ = list
    __api_method__ = "friends.getRecent"

    count: int = 100


class FriendsGetRequests(VKMethod[dict]):
    """Returns information about the current user's incoming and outgoing friend requests."""

    __returning__ = dict
    __api_method__ = "friends.getRequests"

    count: int = 100
    extended: bool | None = None
    fields: list[str] | None = None
    need_mutual: bool | None = None
    need_viewed: bool = False
    offset: int | None = None
    out: bool | None = None
    ref: str | None = None
    sort: int | None = None
    suggested: bool | None = None


class FriendsGetSuggestions(VKMethod[dict]):
    """Returns a list of profiles of users whom the current user may know."""

    __returning__ = dict
    __api_method__ = "friends.getSuggestions"

    count: int = 100
    fields: list[str] | None = None
    filter: list[str] | None = None
    name_case: str | None = None
    offset: int | None = None


class FriendsSearch(VKMethod[dict]):
    """Returns a list of friends matching the search criteria."""

    __returning__ = dict
    __api_method__ = "friends.search"

    count: int = 20
    fields: list[str] | None = None
    name_case: str | None = None
    offset: int | None = None
    q: str | None = None
    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "friends.add": FriendsAdd,
    "friends.addList": FriendsAddList,
    "friends.areFriends": FriendsAreFriends,
    "friends.delete": FriendsDelete,
    "friends.deleteAllRequests": FriendsDeleteAllRequests,
    "friends.deleteList": FriendsDeleteList,
    "friends.edit": FriendsEdit,
    "friends.editList": FriendsEditList,
    "friends.get": FriendsGet,
    "friends.getAppUsers": FriendsGetAppUsers,
    "friends.getLists": FriendsGetLists,
    "friends.getMutual": FriendsGetMutual,
    "friends.getOnline": FriendsGetOnline,
    "friends.getRecent": FriendsGetRecent,
    "friends.getRequests": FriendsGetRequests,
    "friends.getSuggestions": FriendsGetSuggestions,
    "friends.search": FriendsSearch,
}

__all__ = ["FriendsAdd", "FriendsAddList", "FriendsAreFriends", "FriendsDelete", "FriendsDeleteAllRequests", "FriendsDeleteList", "FriendsEdit", "FriendsEditList", "FriendsGet", "FriendsGetAppUsers", "FriendsGetLists", "FriendsGetMutual", "FriendsGetOnline", "FriendsGetRecent", "FriendsGetRequests", "FriendsGetSuggestions", "FriendsSearch"]
