"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class GiftsGet(VKMethod[dict]):
    """Returns a list of user gifts."""

    __returning__ = dict
    __api_method__ = "gifts.get"

    count: int | None = None
    offset: int | None = None
    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "gifts.get": GiftsGet,
}

__all__ = ["GiftsGet"]
