"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class GroupsAddAddress(VKMethod[dict]):
    """VK API method groups.addAddress."""

    __returning__ = dict
    __api_method__ = "groups.addAddress"

    address: str
    city_id: int
    group_id: int
    latitude: float
    longitude: float
    title: str
    additional_address: str | None = None
    is_main_address: bool | None = None
    metro_id: int | None = None
    phone: str | None = None
    timetable: str | None = None
    work_info_status: str = 'no_information'


class GroupsAddCallbackServer(VKMethod[dict]):
    """VK API method groups.addCallbackServer."""

    __returning__ = dict
    __api_method__ = "groups.addCallbackServer"

    group_id: int
    title: str
    url: str
    secret_key: str | None = None


class GroupsAddLink(VKMethod[dict]):
    """Allows to add a link to the community."""

    __returning__ = dict
    __api_method__ = "groups.addLink"

    group_id: int
    link: str
    text: str | None = None


class GroupsApproveRequest(VKMethod[int]):
    """Allows to approve join request to the community."""

    __returning__ = int
    __api_method__ = "groups.approveRequest"

    group_id: int
    user_id: int


class GroupsBan(VKMethod[int]):
    """VK API method groups.ban."""

    __returning__ = int
    __api_method__ = "groups.ban"

    group_id: int
    comment: str | None = None
    comment_visible: bool | None = None
    end_date: int | None = None
    owner_id: int | None = None
    reason: int | None = None


class GroupsCreate(VKMethod[dict]):
    """Creates a new community."""

    __returning__ = dict
    __api_method__ = "groups.create"

    title: str
    description: str | None = None
    public_category: int | None = None
    public_subcategory: int | None = None
    subtype: int | None = None
    type: str = 'group'


class GroupsDeleteAddress(VKMethod[int]):
    """VK API method groups.deleteAddress."""

    __returning__ = int
    __api_method__ = "groups.deleteAddress"

    address_id: int
    group_id: int


class GroupsDeleteCallbackServer(VKMethod[int]):
    """VK API method groups.deleteCallbackServer."""

    __returning__ = int
    __api_method__ = "groups.deleteCallbackServer"

    group_id: int
    server_id: int


class GroupsDeleteLink(VKMethod[int]):
    """Allows to delete a link from the community."""

    __returning__ = int
    __api_method__ = "groups.deleteLink"

    group_id: int
    link_id: int


class GroupsDisableOnline(VKMethod[int]):
    """VK API method groups.disableOnline."""

    __returning__ = int
    __api_method__ = "groups.disableOnline"

    group_id: int


class GroupsEdit(VKMethod[int]):
    """Edits a community."""

    __returning__ = int
    __api_method__ = "groups.edit"

    group_id: int
    access: int | None = None
    addresses: bool | None = None
    age_limits: int | None = None
    articles: bool | None = None
    audio: int | None = None
    city: int | None = None
    contacts: bool | None = None
    country: int | None = None
    description: str | None = None
    disable_replies_from_groups: bool | None = None
    docs: int | None = None
    email: str | None = None
    event_finish_date: int | None = None
    event_group_id: int | None = None
    event_start_date: int | None = None
    events: bool | None = None
    links: bool | None = None
    main_section: int | None = None
    market: bool | None = None
    market_buttons: str | None = None
    market_city: list[int] | None = None
    market_comments: bool | None = None
    market_contact: int | None = None
    market_country: list[int] | None = None
    market_currency: int | None = None
    market_wiki: int | None = None
    messages: bool | None = None
    obscene_filter: bool | None = None
    obscene_stopwords: bool | None = None
    obscene_words: list[str] | None = None
    phone: str | None = None
    photos: int | None = None
    places: bool | None = None
    public_category: int | None = None
    public_date: str | None = None
    public_subcategory: int | None = None
    rss: str | None = None
    screen_name: str | None = None
    secondary_section: int | None = None
    subject: int | None = None
    title: str | None = None
    topics: int | None = None
    toxic_filter: bool | None = None
    video: int | None = None
    wall: int | None = None
    website: str | None = None
    wiki: int | None = None


class GroupsEditAddress(VKMethod[dict]):
    """VK API method groups.editAddress."""

    __returning__ = dict
    __api_method__ = "groups.editAddress"

    address_id: int
    group_id: int
    additional_address: str | None = None
    address: str | None = None
    city_id: int | None = None
    is_main_address: bool | None = None
    latitude: float | None = None
    longitude: float | None = None
    metro_id: int | None = None
    phone: str | None = None
    timetable: str | None = None
    title: str | None = None
    work_info_status: str | None = None


class GroupsEditCallbackServer(VKMethod[int]):
    """VK API method groups.editCallbackServer."""

    __returning__ = int
    __api_method__ = "groups.editCallbackServer"

    group_id: int
    server_id: int
    title: str
    url: str
    secret_key: str | None = None


class GroupsEditLink(VKMethod[int]):
    """Allows to edit a link in the community."""

    __returning__ = int
    __api_method__ = "groups.editLink"

    group_id: int
    link_id: int
    text: str | None = None


class GroupsEditManager(VKMethod[int]):
    """Allows to add, remove or edit the community manager."""

    __returning__ = int
    __api_method__ = "groups.editManager"

    group_id: int
    user_id: int
    contact_email: str | None = None
    contact_phone: str | None = None
    contact_position: str | None = None
    is_call_operator: bool | None = None
    is_contact: bool | None = None
    role: str | None = None


class GroupsEnableOnline(VKMethod[int]):
    """VK API method groups.enableOnline."""

    __returning__ = int
    __api_method__ = "groups.enableOnline"

    group_id: int


class GroupsGet(VKMethod[dict]):
    """Returns a list of the communities to which a user belongs."""

    __returning__ = dict
    __api_method__ = "groups.get"

    count: int | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    filter: list[str] | None = None
    offset: int | None = None
    user_id: int | None = None


class GroupsGetAddresses(VKMethod[dict]):
    """Returns a list of community addresses."""

    __returning__ = dict
    __api_method__ = "groups.getAddresses"

    group_id: int
    address_ids: list[int] | None = None
    count: int = 10
    fields: list[str] | None = None
    latitude: float | None = None
    longitude: float | None = None
    offset: int | None = None


class GroupsGetBanned(VKMethod[dict]):
    """Returns a list of users on a community blacklist."""

    __returning__ = dict
    __api_method__ = "groups.getBanned"

    group_id: int
    count: int = 20
    fields: list[str] | None = None
    offset: int | None = None
    owner_id: int | None = None


class GroupsGetById(VKMethod[dict]):
    """Returns information about communities by their IDs."""

    __returning__ = dict
    __api_method__ = "groups.getById"

    fields: list[str] | None = None
    group_id: int | str | None = None
    group_ids: list[str] | None = None


class GroupsGetCallbackConfirmationCode(VKMethod[dict]):
    """Returns Callback API confirmation code for the community."""

    __returning__ = dict
    __api_method__ = "groups.getCallbackConfirmationCode"

    group_id: int


class GroupsGetCallbackServers(VKMethod[dict]):
    """VK API method groups.getCallbackServers."""

    __returning__ = dict
    __api_method__ = "groups.getCallbackServers"

    group_id: int
    server_ids: list[int] | None = None


class GroupsGetCallbackSettings(VKMethod[dict]):
    """Returns [vk.com/dev/callback_api|Callback API] notifications settings."""

    __returning__ = dict
    __api_method__ = "groups.getCallbackSettings"

    group_id: int
    server_id: int | None = None


class GroupsGetCatalogInfo(VKMethod[dict]):
    """Returns categories list for communities catalog"""

    __returning__ = dict
    __api_method__ = "groups.getCatalogInfo"

    extended: bool = False
    subcategories: bool = False


class GroupsGetInvitedUsers(VKMethod[dict]):
    """Returns invited users list of a community"""

    __returning__ = dict
    __api_method__ = "groups.getInvitedUsers"

    group_id: int
    count: int = 20
    fields: list[str] | None = None
    name_case: str | None = None
    offset: int | None = None


class GroupsGetInvites(VKMethod[dict]):
    """Returns a list of invitations to join communities and events."""

    __returning__ = dict
    __api_method__ = "groups.getInvites"

    count: int = 20
    extended: bool | None = None
    offset: int | None = None


class GroupsGetLongPollServer(VKMethod[dict]):
    """Returns the data needed to query a Long Poll server for events"""

    __returning__ = dict
    __api_method__ = "groups.getLongPollServer"

    group_id: int


class GroupsGetLongPollSettings(VKMethod[dict]):
    """Returns Long Poll notification settings"""

    __returning__ = dict
    __api_method__ = "groups.getLongPollSettings"

    group_id: int


class GroupsGetMembers(VKMethod[dict]):
    """Returns a list of community members."""

    __returning__ = dict
    __api_method__ = "groups.getMembers"

    count: int = 1000
    fields: list[str] | None = None
    filter: str | None = None
    group_id: int | str | None = None
    offset: int | None = None
    sort: str = 'id_asc'


class GroupsGetOnlineStatus(VKMethod[dict]):
    """VK API method groups.getOnlineStatus."""

    __returning__ = dict
    __api_method__ = "groups.getOnlineStatus"

    group_id: int


class GroupsGetRequests(VKMethod[dict]):
    """Returns a list of requests to the community."""

    __returning__ = dict
    __api_method__ = "groups.getRequests"

    group_id: int
    count: int = 20
    fields: list[str] | None = None
    offset: int | None = None


class GroupsGetSettings(VKMethod[dict]):
    """Returns community settings."""

    __returning__ = dict
    __api_method__ = "groups.getSettings"

    group_id: int | str


class GroupsGetTagList(VKMethod[list]):
    """List of group's tags"""

    __returning__ = list
    __api_method__ = "groups.getTagList"

    group_id: int


class GroupsGetTokenPermissions(VKMethod[dict]):
    """VK API method groups.getTokenPermissions."""

    __returning__ = dict
    __api_method__ = "groups.getTokenPermissions"


class GroupsInvite(VKMethod[int]):
    """Allows to invite friends to the community."""

    __returning__ = int
    __api_method__ = "groups.invite"

    group_id: int
    user_id: int | None = None
    user_ids_list: list[int] | None = None


class GroupsIsMember(VKMethod[int]):
    """Returns information specifying whether a user is a member of a community."""

    __returning__ = int
    __api_method__ = "groups.isMember"

    group_id: int | str
    extended: bool | None = None
    user_id: int | None = None
    user_ids: list[int] | None = None


class GroupsJoin(VKMethod[int]):
    """With this method you can join the group or public page, and also confirm your participation in an event."""

    __returning__ = int
    __api_method__ = "groups.join"

    group_id: int
    not_sure: str | None = None


class GroupsLeave(VKMethod[int]):
    """With this method you can leave a group, public page, or event."""

    __returning__ = int
    __api_method__ = "groups.leave"

    group_id: int


class GroupsRemoveUser(VKMethod[int]):
    """Removes a user from the community."""

    __returning__ = int
    __api_method__ = "groups.removeUser"

    group_id: int
    user_id: int


class GroupsReorderLink(VKMethod[int]):
    """Allows to reorder links in the community."""

    __returning__ = int
    __api_method__ = "groups.reorderLink"

    group_id: int
    link_id: int
    after: int | None = None


class GroupsSearch(VKMethod[dict]):
    """Returns a list of communities matching the search criteria."""

    __returning__ = dict
    __api_method__ = "groups.search"

    q: str
    city_id: int | None = None
    count: int = 20
    country_id: int | None = None
    future: bool | None = None
    market: bool | None = None
    offset: int | None = None
    sort: int | None = None
    type: str | None = None


class GroupsSetCallbackSettings(VKMethod[int]):
    """Allow to set notifications settings for group."""

    __returning__ = int
    __api_method__ = "groups.setCallbackSettings"

    group_id: int
    api_version: str | None = None
    audio_new: bool | None = None
    board_post_delete: bool | None = None
    board_post_edit: bool | None = None
    board_post_new: bool | None = None
    board_post_restore: bool | None = None
    donut_money_withdraw: bool | None = None
    donut_money_withdraw_error: bool | None = None
    donut_subscription_cancelled: bool | None = None
    donut_subscription_create: bool | None = None
    donut_subscription_expired: bool | None = None
    donut_subscription_price_changed: bool | None = None
    donut_subscription_prolonged: bool | None = None
    group_change_photo: bool | None = None
    group_change_settings: bool | None = None
    group_join: bool | None = None
    group_leave: bool | None = None
    group_officers_edit: bool | None = None
    lead_forms_new: bool | None = None
    like_add: bool | None = None
    like_remove: bool | None = None
    market_comment_delete: bool | None = None
    market_comment_edit: bool | None = None
    market_comment_new: bool | None = None
    market_comment_restore: bool | None = None
    market_order_edit: bool | None = None
    market_order_new: bool | None = None
    message_allow: bool | None = None
    message_deny: bool | None = None
    message_edit: bool | None = None
    message_event: bool | None = None
    message_new: bool | None = None
    message_reaction_event: bool | None = None
    message_read: bool | None = None
    message_reply: bool | None = None
    message_typing_state: bool | None = None
    photo_comment_delete: bool | None = None
    photo_comment_edit: bool | None = None
    photo_comment_new: bool | None = None
    photo_comment_restore: bool | None = None
    photo_new: bool | None = None
    poll_vote_new: bool | None = None
    server_id: int | None = None
    user_block: bool | None = None
    user_unblock: bool | None = None
    video_comment_delete: bool | None = None
    video_comment_edit: bool | None = None
    video_comment_new: bool | None = None
    video_comment_restore: bool | None = None
    video_new: bool | None = None
    wall_post_new: bool | None = None
    wall_reply_delete: bool | None = None
    wall_reply_edit: bool | None = None
    wall_reply_new: bool | None = None
    wall_reply_restore: bool | None = None
    wall_repost: bool | None = None
    wall_schedule_post_delete: bool | None = None
    wall_schedule_post_new: bool | None = None


class GroupsSetLongPollSettings(VKMethod[int]):
    """Sets Long Poll notification settings"""

    __returning__ = int
    __api_method__ = "groups.setLongPollSettings"

    group_id: int
    api_version: str | None = None
    audio_new: bool | None = None
    board_post_delete: bool | None = None
    board_post_edit: bool | None = None
    board_post_new: bool | None = None
    board_post_restore: bool | None = None
    donut_money_withdraw: bool | None = None
    donut_money_withdraw_error: bool | None = None
    donut_subscription_cancelled: bool | None = None
    donut_subscription_create: bool | None = None
    donut_subscription_expired: bool | None = None
    donut_subscription_price_changed: bool | None = None
    donut_subscription_prolonged: bool | None = None
    enabled: bool | None = None
    group_change_photo: bool | None = None
    group_change_settings: bool | None = None
    group_join: bool | None = None
    group_leave: bool | None = None
    group_officers_edit: bool | None = None
    like_add: bool | None = None
    like_remove: bool | None = None
    market_comment_delete: bool | None = None
    market_comment_edit: bool | None = None
    market_comment_new: bool | None = None
    market_comment_restore: bool | None = None
    message_allow: bool | None = None
    message_deny: bool | None = None
    message_edit: bool | None = None
    message_event: bool | None = None
    message_new: bool | None = None
    message_reaction_event: bool | None = None
    message_read: bool | None = None
    message_reply: bool | None = None
    message_typing_state: bool | None = None
    photo_comment_delete: bool | None = None
    photo_comment_edit: bool | None = None
    photo_comment_new: bool | None = None
    photo_comment_restore: bool | None = None
    photo_new: bool | None = None
    poll_vote_new: bool | None = None
    user_block: bool | None = None
    user_unblock: bool | None = None
    video_comment_delete: bool | None = None
    video_comment_edit: bool | None = None
    video_comment_new: bool | None = None
    video_comment_restore: bool | None = None
    video_new: bool | None = None
    wall_post_new: bool | None = None
    wall_reply_delete: bool | None = None
    wall_reply_edit: bool | None = None
    wall_reply_new: bool | None = None
    wall_reply_restore: bool | None = None
    wall_repost: bool | None = None


class GroupsSetSettings(VKMethod[int]):
    """VK API method groups.setSettings."""

    __returning__ = int
    __api_method__ = "groups.setSettings"

    group_id: int
    bot_online_booking_enabled: bool | None = None
    bots_add_to_chat: bool | None = None
    bots_capabilities: bool | None = None
    bots_start_button: bool | None = None
    messages: bool | None = None


class GroupsSetUserNote(VKMethod[int]):
    """In order to save note about group participant"""

    __returning__ = int
    __api_method__ = "groups.setUserNote"

    group_id: int
    user_id: int
    note: str | None = None


class GroupsTagAdd(VKMethod[int]):
    """Add new group's tag"""

    __returning__ = int
    __api_method__ = "groups.tagAdd"

    group_id: int
    tag_name: str
    tag_color: str | None = None


class GroupsTagBind(VKMethod[int]):
    """Bind or unbind group's tag to user"""

    __returning__ = int
    __api_method__ = "groups.tagBind"

    act: str
    group_id: int
    tag_id: int
    user_id: int


class GroupsTagDelete(VKMethod[int]):
    """Delete group's tag"""

    __returning__ = int
    __api_method__ = "groups.tagDelete"

    group_id: int
    tag_id: int


class GroupsTagUpdate(VKMethod[int]):
    """Update group's tag"""

    __returning__ = int
    __api_method__ = "groups.tagUpdate"

    group_id: int
    tag_id: int
    tag_name: str


class GroupsToggleMarket(VKMethod[int]):
    """VK API method groups.toggleMarket."""

    __returning__ = int
    __api_method__ = "groups.toggleMarket"

    group_id: int
    state: str
    ref: str | None = None


class GroupsUnban(VKMethod[int]):
    """VK API method groups.unban."""

    __returning__ = int
    __api_method__ = "groups.unban"

    group_id: int
    owner_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "groups.addAddress": GroupsAddAddress,
    "groups.addCallbackServer": GroupsAddCallbackServer,
    "groups.addLink": GroupsAddLink,
    "groups.approveRequest": GroupsApproveRequest,
    "groups.ban": GroupsBan,
    "groups.create": GroupsCreate,
    "groups.deleteAddress": GroupsDeleteAddress,
    "groups.deleteCallbackServer": GroupsDeleteCallbackServer,
    "groups.deleteLink": GroupsDeleteLink,
    "groups.disableOnline": GroupsDisableOnline,
    "groups.edit": GroupsEdit,
    "groups.editAddress": GroupsEditAddress,
    "groups.editCallbackServer": GroupsEditCallbackServer,
    "groups.editLink": GroupsEditLink,
    "groups.editManager": GroupsEditManager,
    "groups.enableOnline": GroupsEnableOnline,
    "groups.get": GroupsGet,
    "groups.getAddresses": GroupsGetAddresses,
    "groups.getBanned": GroupsGetBanned,
    "groups.getById": GroupsGetById,
    "groups.getCallbackConfirmationCode": GroupsGetCallbackConfirmationCode,
    "groups.getCallbackServers": GroupsGetCallbackServers,
    "groups.getCallbackSettings": GroupsGetCallbackSettings,
    "groups.getCatalogInfo": GroupsGetCatalogInfo,
    "groups.getInvitedUsers": GroupsGetInvitedUsers,
    "groups.getInvites": GroupsGetInvites,
    "groups.getLongPollServer": GroupsGetLongPollServer,
    "groups.getLongPollSettings": GroupsGetLongPollSettings,
    "groups.getMembers": GroupsGetMembers,
    "groups.getOnlineStatus": GroupsGetOnlineStatus,
    "groups.getRequests": GroupsGetRequests,
    "groups.getSettings": GroupsGetSettings,
    "groups.getTagList": GroupsGetTagList,
    "groups.getTokenPermissions": GroupsGetTokenPermissions,
    "groups.invite": GroupsInvite,
    "groups.isMember": GroupsIsMember,
    "groups.join": GroupsJoin,
    "groups.leave": GroupsLeave,
    "groups.removeUser": GroupsRemoveUser,
    "groups.reorderLink": GroupsReorderLink,
    "groups.search": GroupsSearch,
    "groups.setCallbackSettings": GroupsSetCallbackSettings,
    "groups.setLongPollSettings": GroupsSetLongPollSettings,
    "groups.setSettings": GroupsSetSettings,
    "groups.setUserNote": GroupsSetUserNote,
    "groups.tagAdd": GroupsTagAdd,
    "groups.tagBind": GroupsTagBind,
    "groups.tagDelete": GroupsTagDelete,
    "groups.tagUpdate": GroupsTagUpdate,
    "groups.toggleMarket": GroupsToggleMarket,
    "groups.unban": GroupsUnban,
}

__all__ = ["GroupsAddAddress", "GroupsAddCallbackServer", "GroupsAddLink", "GroupsApproveRequest", "GroupsBan", "GroupsCreate", "GroupsDeleteAddress", "GroupsDeleteCallbackServer", "GroupsDeleteLink", "GroupsDisableOnline", "GroupsEdit", "GroupsEditAddress", "GroupsEditCallbackServer", "GroupsEditLink", "GroupsEditManager", "GroupsEnableOnline", "GroupsGet", "GroupsGetAddresses", "GroupsGetBanned", "GroupsGetById", "GroupsGetCallbackConfirmationCode", "GroupsGetCallbackServers", "GroupsGetCallbackSettings", "GroupsGetCatalogInfo", "GroupsGetInvitedUsers", "GroupsGetInvites", "GroupsGetLongPollServer", "GroupsGetLongPollSettings", "GroupsGetMembers", "GroupsGetOnlineStatus", "GroupsGetRequests", "GroupsGetSettings", "GroupsGetTagList", "GroupsGetTokenPermissions", "GroupsInvite", "GroupsIsMember", "GroupsJoin", "GroupsLeave", "GroupsRemoveUser", "GroupsReorderLink", "GroupsSearch", "GroupsSetCallbackSettings", "GroupsSetLongPollSettings", "GroupsSetSettings", "GroupsSetUserNote", "GroupsTagAdd", "GroupsTagBind", "GroupsTagDelete", "GroupsTagUpdate", "GroupsToggleMarket", "GroupsUnban"]
