"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class LeadFormsCreate(VKMethod[dict]):
    """VK API method leadForms.create."""

    __returning__ = dict
    __api_method__ = "leadForms.create"

    description: str
    group_id: int
    name: str
    policy_link_url: str
    questions: str
    title: str
    active: bool = False
    confirmation: str | None = None
    notify_admins: list[int] | None = None
    notify_emails: list[str] | None = None
    once_per_user: bool = False
    photo: str | None = None
    pixel_code: str | None = None
    site_link_url: str | None = None


class LeadFormsDelete(VKMethod[dict]):
    """VK API method leadForms.delete."""

    __returning__ = dict
    __api_method__ = "leadForms.delete"

    form_id: int
    group_id: int


class LeadFormsGet(VKMethod[dict]):
    """VK API method leadForms.get."""

    __returning__ = dict
    __api_method__ = "leadForms.get"

    form_id: int
    group_id: int


class LeadFormsGetLeads(VKMethod[dict]):
    """VK API method leadForms.getLeads."""

    __returning__ = dict
    __api_method__ = "leadForms.getLeads"

    form_id: int
    group_id: int
    limit: int = 10
    next_page_token: str | None = None


class LeadFormsGetUploadURL(VKMethod[dict]):
    """VK API method leadForms.getUploadURL."""

    __returning__ = dict
    __api_method__ = "leadForms.getUploadURL"


class LeadFormsList(VKMethod[list]):
    """VK API method leadForms.list."""

    __returning__ = list
    __api_method__ = "leadForms.list"

    group_id: int


class LeadFormsUpdate(VKMethod[dict]):
    """VK API method leadForms.update."""

    __returning__ = dict
    __api_method__ = "leadForms.update"

    description: str
    form_id: int
    group_id: int
    name: str
    policy_link_url: str
    questions: str
    title: str
    active: bool = False
    confirmation: str | None = None
    notify_admins: list[int] | None = None
    notify_emails: list[str] | None = None
    once_per_user: bool = False
    photo: str | None = None
    pixel_code: str | None = None
    site_link_url: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "leadForms.create": LeadFormsCreate,
    "leadForms.delete": LeadFormsDelete,
    "leadForms.get": LeadFormsGet,
    "leadForms.getLeads": LeadFormsGetLeads,
    "leadForms.getUploadURL": LeadFormsGetUploadURL,
    "leadForms.list": LeadFormsList,
    "leadForms.update": LeadFormsUpdate,
}

__all__ = ["LeadFormsCreate", "LeadFormsDelete", "LeadFormsGet", "LeadFormsGetLeads", "LeadFormsGetUploadURL", "LeadFormsList", "LeadFormsUpdate"]
