"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class LikesAdd(VKMethod[dict]):
    """Adds the specified object to the 'Likes' list of the current user."""

    __returning__ = dict
    __api_method__ = "likes.add"

    item_id: int
    type: str
    access_key: str | None = None
    from_group: bool | None = None
    owner_id: int | None = None


class LikesDelete(VKMethod[dict]):
    """Deletes the specified object from the 'Likes' list of the current user."""

    __returning__ = dict
    __api_method__ = "likes.delete"

    item_id: int
    type: str
    access_key: str | None = None
    from_group: bool | None = None
    owner_id: int | None = None


class LikesGetList(VKMethod[dict]):
    """Returns a list of IDs of users who added the specified object to their 'Likes' list."""

    __returning__ = dict
    __api_method__ = "likes.getList"

    type: str
    count: int | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    filter: str | None = None
    friends_only: int = 0
    item_id: int | None = None
    offset: int | None = None
    owner_id: int | None = None
    page_url: str | None = None
    skip_own: bool | None = None


class LikesIsLiked(VKMethod[dict]):
    """Checks for the object in the 'Likes' list of the specified user."""

    __returning__ = dict
    __api_method__ = "likes.isLiked"

    item_id: int
    type: str
    owner_id: int | None = None
    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "likes.add": LikesAdd,
    "likes.delete": LikesDelete,
    "likes.getList": LikesGetList,
    "likes.isLiked": LikesIsLiked,
}

__all__ = ["LikesAdd", "LikesDelete", "LikesGetList", "LikesIsLiked"]
