"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class MarketAdd(VKMethod[dict]):
    """Ads a new item to the market."""

    __returning__ = dict
    __api_method__ = "market.add"

    category_id: int
    description: str
    name: str
    owner_id: int
    deleted: bool | None = None
    dimension_height: int | None = None
    dimension_length: int | None = None
    dimension_width: int | None = None
    is_main_variant: bool | None = None
    main_photo_id: int | None = None
    old_price: float | None = None
    photo_ids: list[int] | None = None
    price: float | None = None
    sku: str | None = None
    stock_amount: int | None = None
    url: str | None = None
    variant_ids: list[int] | None = None
    video_ids: list[int] | None = None
    weight: int | None = None


class MarketAddAlbum(VKMethod[dict]):
    """Creates new collection of items"""

    __returning__ = dict
    __api_method__ = "market.addAlbum"

    owner_id: int
    title: str
    is_hidden: bool | None = None
    main_album: bool | None = None
    photo_id: int | None = None


class MarketAddProperty(VKMethod[dict]):
    """Adds property"""

    __returning__ = dict
    __api_method__ = "market.addProperty"

    group_id: int
    title: str


class MarketAddPropertyVariant(VKMethod[dict]):
    """Adds property variant"""

    __returning__ = dict
    __api_method__ = "market.addPropertyVariant"

    group_id: int
    property_id: int
    title: str


class MarketAddToAlbum(VKMethod[dict]):
    """Adds an item to one or multiple collections."""

    __returning__ = dict
    __api_method__ = "market.addToAlbum"

    album_ids: list[int]
    item_ids: list[int]
    owner_id: int


class MarketCreateComment(VKMethod[int]):
    """Creates a new comment for an item."""

    __returning__ = int
    __api_method__ = "market.createComment"

    item_id: int
    owner_id: int
    attachments: list[str] | None = None
    from_group: bool | None = None
    guid: str | None = None
    message: str | None = None
    reply_to_comment: int | None = None
    sticker_id: int | None = None


class MarketDelete(VKMethod[int]):
    """Deletes an item."""

    __returning__ = int
    __api_method__ = "market.delete"

    item_id: int
    owner_id: int


class MarketDeleteAlbum(VKMethod[int]):
    """Deletes a collection of items."""

    __returning__ = int
    __api_method__ = "market.deleteAlbum"

    album_id: int
    owner_id: int


class MarketDeleteComment(VKMethod[int]):
    """Deletes an item's comment"""

    __returning__ = int
    __api_method__ = "market.deleteComment"

    comment_id: int
    owner_id: int


class MarketDeleteProperty(VKMethod[int]):
    """VK API method market.deleteProperty."""

    __returning__ = int
    __api_method__ = "market.deleteProperty"

    group_id: int
    property_id: int


class MarketDeletePropertyVariant(VKMethod[int]):
    """VK API method market.deletePropertyVariant."""

    __returning__ = int
    __api_method__ = "market.deletePropertyVariant"

    group_id: int
    variant_id: int


class MarketEdit(VKMethod[int]):
    """Edits an item."""

    __returning__ = int
    __api_method__ = "market.edit"

    item_id: int
    owner_id: int
    category_id: int | None = None
    deleted: bool | None = None
    description: str | None = None
    dimension_height: int | None = None
    dimension_length: int | None = None
    dimension_width: int | None = None
    is_main_variant: bool | None = None
    main_photo_id: int | None = None
    name: str | None = None
    old_price: float | None = None
    photo_ids: list[int] | None = None
    price: float | None = None
    sku: str | None = None
    stock_amount: int | None = None
    url: str | None = None
    variant_ids: list[int] | None = None
    video_ids: list[int] | None = None
    weight: int | None = None


class MarketEditAlbum(VKMethod[int]):
    """Edits a collection of items"""

    __returning__ = int
    __api_method__ = "market.editAlbum"

    album_id: int
    owner_id: int
    title: str
    is_hidden: bool | None = None
    main_album: bool | None = None
    photo_id: int | None = None


class MarketEditComment(VKMethod[int]):
    """Chages item comment's text"""

    __returning__ = int
    __api_method__ = "market.editComment"

    comment_id: int
    owner_id: int
    attachments: list[str] | None = None
    message: str | None = None


class MarketEditOrder(VKMethod[int]):
    """Edit order"""

    __returning__ = int
    __api_method__ = "market.editOrder"

    order_id: int
    user_id: int
    comment_for_user: str | None = None
    delivery_price: int | None = None
    height: int | None = None
    length: int | None = None
    merchant_comment: str | None = None
    payment_status: str | None = None
    receipt_link: str | None = None
    status: int | None = None
    track_number: str | None = None
    weight: int | None = None
    width: int | None = None


class MarketEditProperty(VKMethod[int]):
    """Adds property"""

    __returning__ = int
    __api_method__ = "market.editProperty"

    group_id: int
    property_id: int
    title: str


class MarketEditPropertyVariant(VKMethod[int]):
    """Edit property variant name"""

    __returning__ = int
    __api_method__ = "market.editPropertyVariant"

    group_id: int
    title: str
    variant_id: int


class MarketFilterCategories(VKMethod[dict]):
    """Returns a filter list of market categories."""

    __returning__ = dict
    __api_method__ = "market.filterCategories"

    category_id: int | None = None
    count: int = 20
    query: str | None = None


class MarketGet(VKMethod[dict]):
    """Returns items list for a community."""

    __returning__ = dict
    __api_method__ = "market.get"

    owner_id: int
    album_id: int = 0
    count: int = 100
    date_from: str | None = None
    date_to: str | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    need_variants: bool | None = None
    offset: int | None = None
    with_disabled: bool | None = None


class MarketGetAlbumById(VKMethod[dict]):
    """Returns items album's data"""

    __returning__ = dict
    __api_method__ = "market.getAlbumById"

    album_ids: list[int]
    owner_id: int


class MarketGetAlbums(VKMethod[dict]):
    """Returns community's market collections list."""

    __returning__ = dict
    __api_method__ = "market.getAlbums"

    owner_id: int
    count: int = 50
    offset: int | None = None


class MarketGetById(VKMethod[dict]):
    """Returns information about market items by their ids."""

    __returning__ = dict
    __api_method__ = "market.getById"

    item_ids: list[str]
    extended: bool | None = None


class MarketGetCategories(VKMethod[dict]):
    """Returns a list of market categories."""

    __returning__ = dict
    __api_method__ = "market.getCategories"

    album_id: int | None = None
    group_id: int | None = None


class MarketGetComments(VKMethod[dict]):
    """Returns comments list for an item."""

    __returning__ = dict
    __api_method__ = "market.getComments"

    item_id: int
    owner_id: int
    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    need_likes: bool | None = None
    offset: int = 0
    sort: str = 'asc'
    start_comment_id: int | None = None


class MarketGetFavesForAttach(VKMethod[dict]):
    """VK API method market.getFavesForAttach."""

    __returning__ = dict
    __api_method__ = "market.getFavesForAttach"

    count: int = 50
    current_group_id: int | None = None
    offset: int | None = None
    public_only: bool = False


class MarketGetGroupOrders(VKMethod[dict]):
    """Get market orders"""

    __returning__ = dict
    __api_method__ = "market.getGroupOrders"

    count: int = 10
    group_id: int | str | None = None
    offset: int = 0


class MarketGetOrderById(VKMethod[dict]):
    """Get order"""

    __returning__ = dict
    __api_method__ = "market.getOrderById"

    order_id: int
    extended: bool | None = None
    user_id: int | None = None


class MarketGetOrderItems(VKMethod[dict]):
    """Get market items in the order"""

    __returning__ = dict
    __api_method__ = "market.getOrderItems"

    order_id: int
    count: int = 50
    offset: int | None = None
    user_id: int | None = None


class MarketGetOrders(VKMethod[dict]):
    """VK API method market.getOrders."""

    __returning__ = dict
    __api_method__ = "market.getOrders"

    count: int = 10
    date_from: str | None = None
    date_to: str | None = None
    extended: bool | None = None
    offset: int = 0


class MarketGetProductPhotoUploadServer(VKMethod[dict]):
    """Returns the server address for market photo upload."""

    __returning__ = dict
    __api_method__ = "market.getProductPhotoUploadServer"

    group_id: int
    bulk: bool = False


class MarketGetProperties(VKMethod[dict]):
    """Get properties"""

    __returning__ = dict
    __api_method__ = "market.getProperties"

    group_id: int


class MarketGroupItems(VKMethod[dict]):
    """VK API method market.groupItems."""

    __returning__ = dict
    __api_method__ = "market.groupItems"

    group_id: int
    item_ids: list[int]
    item_group_id: int | None = None


class MarketRemoveFromAlbum(VKMethod[int]):
    """Removes an item from one or multiple collections."""

    __returning__ = int
    __api_method__ = "market.removeFromAlbum"

    album_ids: list[int]
    item_id: int
    owner_id: int


class MarketReorderAlbums(VKMethod[int]):
    """Reorders the collections list."""

    __returning__ = int
    __api_method__ = "market.reorderAlbums"

    album_id: int
    owner_id: int
    after: int | None = None
    before: int | None = None


class MarketReorderItems(VKMethod[int]):
    """Changes item place in a collection."""

    __returning__ = int
    __api_method__ = "market.reorderItems"

    item_id: int
    owner_id: int
    after: int | None = None
    album_id: int | None = None
    before: int | None = None


class MarketReport(VKMethod[int]):
    """Sends a complaint to the item."""

    __returning__ = int
    __api_method__ = "market.report"

    item_id: int
    owner_id: int
    reason: int = 0


class MarketReportComment(VKMethod[int]):
    """Sends a complaint to the item's comment."""

    __returning__ = int
    __api_method__ = "market.reportComment"

    comment_id: int
    owner_id: int
    reason: int


class MarketRestore(VKMethod[int]):
    """Restores recently deleted item"""

    __returning__ = int
    __api_method__ = "market.restore"

    item_id: int
    owner_id: int


class MarketRestoreComment(VKMethod[int]):
    """Restores a recently deleted comment"""

    __returning__ = int
    __api_method__ = "market.restoreComment"

    comment_id: int
    owner_id: int


class MarketSaveProductPhoto(VKMethod[dict]):
    """Save market photo after upload."""

    __returning__ = dict
    __api_method__ = "market.saveProductPhoto"

    upload_response: str


class MarketSaveProductPhotoBulk(VKMethod[list]):
    """Bulk save market photo after upload."""

    __returning__ = list
    __api_method__ = "market.saveProductPhotoBulk"

    upload_response: str


class MarketSearch(VKMethod[dict]):
    """Searches market items in a community's catalog"""

    __returning__ = dict
    __api_method__ = "market.search"

    owner_id: int
    album_id: int | None = None
    count: int = 20
    extended: bool = False
    need_variants: bool | None = None
    offset: int | None = None
    price_from: int | None = None
    price_to: int | None = None
    q: str | None = None
    rev: int = 1
    sort: int = 0
    status: list[int] | None = None


class MarketSearchItems(VKMethod[dict]):
    """VK API method market.searchItems."""

    __returning__ = dict
    __api_method__ = "market.searchItems"

    q: str
    category_id: int | None = None
    city: int | None = None
    count: int = 30
    country: int | None = None
    offset: int = 0
    price_from: int | None = None
    price_to: int | None = None
    sort_by: int = 3
    sort_direction: int = 1


class MarketSearchItemsBasic(VKMethod[dict]):
    """VK API method market.searchItemsBasic."""

    __returning__ = dict
    __api_method__ = "market.searchItemsBasic"

    q: str
    category_id: int | None = None
    city: int | None = None
    count: int = 30
    country: int | None = None
    offset: int = 0
    only_my_groups: bool | None = None
    price_from: int | None = None
    price_to: int | None = None
    sort_by: int = 3
    sort_direction: int = 0


class MarketUngroupItems(VKMethod[int]):
    """VK API method market.ungroupItems."""

    __returning__ = int
    __api_method__ = "market.ungroupItems"

    group_id: int
    item_group_id: int



REGISTRY: dict[str, type[VKMethod]] = {
    "market.add": MarketAdd,
    "market.addAlbum": MarketAddAlbum,
    "market.addProperty": MarketAddProperty,
    "market.addPropertyVariant": MarketAddPropertyVariant,
    "market.addToAlbum": MarketAddToAlbum,
    "market.createComment": MarketCreateComment,
    "market.delete": MarketDelete,
    "market.deleteAlbum": MarketDeleteAlbum,
    "market.deleteComment": MarketDeleteComment,
    "market.deleteProperty": MarketDeleteProperty,
    "market.deletePropertyVariant": MarketDeletePropertyVariant,
    "market.edit": MarketEdit,
    "market.editAlbum": MarketEditAlbum,
    "market.editComment": MarketEditComment,
    "market.editOrder": MarketEditOrder,
    "market.editProperty": MarketEditProperty,
    "market.editPropertyVariant": MarketEditPropertyVariant,
    "market.filterCategories": MarketFilterCategories,
    "market.get": MarketGet,
    "market.getAlbumById": MarketGetAlbumById,
    "market.getAlbums": MarketGetAlbums,
    "market.getById": MarketGetById,
    "market.getCategories": MarketGetCategories,
    "market.getComments": MarketGetComments,
    "market.getFavesForAttach": MarketGetFavesForAttach,
    "market.getGroupOrders": MarketGetGroupOrders,
    "market.getOrderById": MarketGetOrderById,
    "market.getOrderItems": MarketGetOrderItems,
    "market.getOrders": MarketGetOrders,
    "market.getProductPhotoUploadServer": MarketGetProductPhotoUploadServer,
    "market.getProperties": MarketGetProperties,
    "market.groupItems": MarketGroupItems,
    "market.removeFromAlbum": MarketRemoveFromAlbum,
    "market.reorderAlbums": MarketReorderAlbums,
    "market.reorderItems": MarketReorderItems,
    "market.report": MarketReport,
    "market.reportComment": MarketReportComment,
    "market.restore": MarketRestore,
    "market.restoreComment": MarketRestoreComment,
    "market.saveProductPhoto": MarketSaveProductPhoto,
    "market.saveProductPhotoBulk": MarketSaveProductPhotoBulk,
    "market.search": MarketSearch,
    "market.searchItems": MarketSearchItems,
    "market.searchItemsBasic": MarketSearchItemsBasic,
    "market.ungroupItems": MarketUngroupItems,
}

__all__ = ["MarketAdd", "MarketAddAlbum", "MarketAddProperty", "MarketAddPropertyVariant", "MarketAddToAlbum", "MarketCreateComment", "MarketDelete", "MarketDeleteAlbum", "MarketDeleteComment", "MarketDeleteProperty", "MarketDeletePropertyVariant", "MarketEdit", "MarketEditAlbum", "MarketEditComment", "MarketEditOrder", "MarketEditProperty", "MarketEditPropertyVariant", "MarketFilterCategories", "MarketGet", "MarketGetAlbumById", "MarketGetAlbums", "MarketGetById", "MarketGetCategories", "MarketGetComments", "MarketGetFavesForAttach", "MarketGetGroupOrders", "MarketGetOrderById", "MarketGetOrderItems", "MarketGetOrders", "MarketGetProductPhotoUploadServer", "MarketGetProperties", "MarketGroupItems", "MarketRemoveFromAlbum", "MarketReorderAlbums", "MarketReorderItems", "MarketReport", "MarketReportComment", "MarketRestore", "MarketRestoreComment", "MarketSaveProductPhoto", "MarketSaveProductPhotoBulk", "MarketSearch", "MarketSearchItems", "MarketSearchItemsBasic", "MarketUngroupItems"]
