"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class MessagesAddChatUser(VKMethod[int]):
    """Adds a new user to a chat."""

    __returning__ = int
    __api_method__ = "messages.addChatUser"

    chat_id: int
    user_id: int | None = None
    visible_messages_count: int | None = None


class MessagesAddChatUsers(VKMethod[dict]):
    """Adds new users to a chat."""

    __returning__ = dict
    __api_method__ = "messages.addChatUsers"

    chat_id: int | None = None
    visible_messages_count: int | None = None


class MessagesAllowMessagesFromGroup(VKMethod[int]):
    """Allows sending messages from community to the current user."""

    __returning__ = int
    __api_method__ = "messages.allowMessagesFromGroup"

    group_id: int
    key: str | None = None


class MessagesCreateChat(VKMethod[dict]):
    """Creates a chat with several participants."""

    __returning__ = dict
    __api_method__ = "messages.createChat"

    group_id: int | None = None
    title: str | None = None
    user_ids: list[int] | None = None


class MessagesDelete(VKMethod[list]):
    """Deletes one or more messages."""

    __returning__ = list
    __api_method__ = "messages.delete"

    cmids: list[int] | None = None
    delete_for_all: bool = False
    group_id: int | None = None
    message_ids: list[int] | None = None
    peer_id: int | None = None
    reason: int | None = None
    spam: bool | None = None


class MessagesDeleteChatPhoto(VKMethod[dict]):
    """Deletes a chat's cover picture."""

    __returning__ = dict
    __api_method__ = "messages.deleteChatPhoto"

    chat_id: int
    group_id: int | None = None


class MessagesDeleteConversation(VKMethod[dict]):
    """Deletes all private messages in a conversation."""

    __returning__ = dict
    __api_method__ = "messages.deleteConversation"

    group_id: int | None = None
    peer_id: int | None = None
    user_id: int | None = None


class MessagesDeleteReaction(VKMethod[int]):
    """Delete message reaction"""

    __returning__ = int
    __api_method__ = "messages.deleteReaction"

    cmid: int
    peer_id: int


class MessagesDenyMessagesFromGroup(VKMethod[int]):
    """Denies sending message from community to the current user."""

    __returning__ = int
    __api_method__ = "messages.denyMessagesFromGroup"

    group_id: int


class MessagesEdit(VKMethod[int]):
    """Edits the message."""

    __returning__ = int
    __api_method__ = "messages.edit"

    peer_id: int
    attachment: str | None = None
    cmid: int | None = None
    disable_mentions: bool = False
    dont_parse_links: bool = False
    group_id: int | None = None
    keep_forward_messages: bool | None = None
    keep_snippets: bool | None = None
    keyboard: str | None = None
    lat: float | None = None
    long: float | None = None
    message: str | None = None
    message_id: int | None = None
    template: str | None = None


class MessagesEditChat(VKMethod[int]):
    """Edits the title of a chat."""

    __returning__ = int
    __api_method__ = "messages.editChat"

    chat_id: int
    title: str | None = None


class MessagesGetByConversationMessageId(VKMethod[dict]):
    """Returns messages by their IDs within the conversation."""

    __returning__ = dict
    __api_method__ = "messages.getByConversationMessageId"

    conversation_message_ids: list[int]
    peer_id: int
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None


class MessagesGetById(VKMethod[dict]):
    """Returns messages by their IDs."""

    __returning__ = dict
    __api_method__ = "messages.getById"

    cmids: list[int] | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    message_ids: list[int] | None = None
    peer_id: int | None = None
    preview_length: int = 0


class MessagesGetChat(VKMethod[dict]):
    """Returns information about a chat."""

    __returning__ = dict
    __api_method__ = "messages.getChat"

    chat_id: int | None = None
    chat_ids: list[int] | None = None
    fields: list[str] | None = None
    name_case: str | None = None


class MessagesGetChatPreview(VKMethod[dict]):
    """VK API method messages.getChatPreview."""

    __returning__ = dict
    __api_method__ = "messages.getChatPreview"

    fields: list[str] | None = None
    link: str | None = None
    peer_id: int | None = None


class MessagesGetConversationMembers(VKMethod[dict]):
    """Returns a list of IDs of users participating in a chat."""

    __returning__ = dict
    __api_method__ = "messages.getConversationMembers"

    peer_id: int
    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    member_ids: list[int] | None = None
    offset: int = 0


class MessagesGetConversations(VKMethod[dict]):
    """Returns a list of the current user's conversations."""

    __returning__ = dict
    __api_method__ = "messages.getConversations"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    filter: str = 'all'
    group_id: int | None = None
    offset: int = 0
    start_message_id: int | None = None


class MessagesGetConversationsById(VKMethod[dict]):
    """Returns conversations by their IDs"""

    __returning__ = dict
    __api_method__ = "messages.getConversationsById"

    peer_ids: list[int]
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None


class MessagesGetHistory(VKMethod[dict]):
    """Returns message history for the specified user or group chat."""

    __returning__ = dict
    __api_method__ = "messages.getHistory"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    offset: int | None = None
    peer_id: int | None = None
    rev: int | None = None
    start_message_id: int | None = None
    user_id: int | None = None


class MessagesGetHistoryAttachments(VKMethod[dict]):
    """Returns media files from the dialog or group chat."""

    __returning__ = dict
    __api_method__ = "messages.getHistoryAttachments"

    attachment_position: int | None = None
    attachment_types: list[str] | None = None
    cmid: int | None = None
    count: int = 30
    extended: bool = False
    fields: list[str] | None = None
    group_id: int | None = None
    max_forwards_level: int = 45
    media_type: str = 'photo'
    message_video: bool = False
    offset: int | None = None
    peer_id: int | None = None
    photo_sizes: bool | None = None
    preserve_order: bool | None = None
    start_from: str | None = None


class MessagesGetImportantMessages(VKMethod[dict]):
    """Returns a list of user's important messages."""

    __returning__ = dict
    __api_method__ = "messages.getImportantMessages"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    offset: int | None = None
    preview_length: int | None = None
    start_message_id: int | None = None


class MessagesGetIntentUsers(VKMethod[dict]):
    """VK API method messages.getIntentUsers."""

    __returning__ = dict
    __api_method__ = "messages.getIntentUsers"

    intent: str
    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    name_case: str | None = None
    offset: int = 0
    subscribe_id: int | None = None


class MessagesGetInviteLink(VKMethod[dict]):
    """VK API method messages.getInviteLink."""

    __returning__ = dict
    __api_method__ = "messages.getInviteLink"

    peer_id: int
    group_id: int | None = None
    reset: bool = False


class MessagesGetLastActivity(VKMethod[dict]):
    """Returns a user's current status and date of last activity."""

    __returning__ = dict
    __api_method__ = "messages.getLastActivity"

    user_id: int


class MessagesGetLongPollHistory(VKMethod[dict]):
    """Returns updates in user's private messages."""

    __returning__ = dict
    __api_method__ = "messages.getLongPollHistory"

    credentials: bool | None = None
    events_limit: int = 1000
    extended: bool = False
    fields: list[str] | None = None
    group_id: int | None = None
    last_n: int = 0
    lp_version: int | None = None
    max_msg_id: int | None = None
    msgs_limit: int = 200
    onlines: bool | None = None
    preview_length: int | None = None
    pts: int | None = None
    ts: int | None = None


class MessagesGetLongPollServer(VKMethod[dict]):
    """Returns data required for connection to a Long Poll server."""

    __returning__ = dict
    __api_method__ = "messages.getLongPollServer"

    group_id: int | None = None
    lp_version: int = 0
    need_pts: bool | None = None


class MessagesGetMessagesReactions(VKMethod[dict]):
    """Get reaction counters for message"""

    __returning__ = dict
    __api_method__ = "messages.getMessagesReactions"

    cmids: list[int]
    peer_id: int


class MessagesGetReactedPeers(VKMethod[dict]):
    """Get reacted users and counters for message"""

    __returning__ = dict
    __api_method__ = "messages.getReactedPeers"

    cmid: int
    peer_id: int
    reaction_id: int | None = None


class MessagesGetReactionsAssets(VKMethod[dict]):
    """Get assets to display message reactions"""

    __returning__ = dict
    __api_method__ = "messages.getReactionsAssets"

    client_version: int | None = None


class MessagesIsMessagesFromGroupAllowed(VKMethod[dict]):
    """Returns information whether sending messages from the community to current user is allowed."""

    __returning__ = dict
    __api_method__ = "messages.isMessagesFromGroupAllowed"

    group_id: int
    user_id: int


class MessagesJoinChatByInviteLink(VKMethod[dict]):
    """VK API method messages.joinChatByInviteLink."""

    __returning__ = dict
    __api_method__ = "messages.joinChatByInviteLink"

    link: str


class MessagesMarkAsAnsweredConversation(VKMethod[int]):
    """Marks and unmarks conversations as unanswered."""

    __returning__ = int
    __api_method__ = "messages.markAsAnsweredConversation"

    peer_id: int
    answered: bool = True
    group_id: int | None = None


class MessagesMarkAsImportant(VKMethod[list]):
    """Marks and unmarks messages as important (starred)."""

    __returning__ = list
    __api_method__ = "messages.markAsImportant"

    important: int | None = None
    message_ids: list[int] | None = None


class MessagesMarkAsImportantConversation(VKMethod[int]):
    """Marks and unmarks conversations as important."""

    __returning__ = int
    __api_method__ = "messages.markAsImportantConversation"

    peer_id: int
    group_id: int | None = None
    important: bool = True


class MessagesMarkAsRead(VKMethod[int]):
    """Marks messages as read."""

    __returning__ = int
    __api_method__ = "messages.markAsRead"

    group_id: int | None = None
    mark_conversation_as_read: bool | None = None
    message_ids: list[int] | None = None
    peer_id: int | None = None
    start_message_id: int | None = None
    up_to_cmid: int | None = None


class MessagesMarkReactionsAsRead(VKMethod[int]):
    """Mark messages reactions as read"""

    __returning__ = int
    __api_method__ = "messages.markReactionsAsRead"

    peer_id: int
    cmids: list[int] | None = None


class MessagesMuteChatMentions(VKMethod[int]):
    """VK API method messages.muteChatMentions."""

    __returning__ = int
    __api_method__ = "messages.muteChatMentions"

    mention_status: str
    peer_id: int


class MessagesPin(VKMethod[dict]):
    """Pin a message."""

    __returning__ = dict
    __api_method__ = "messages.pin"

    peer_id: int
    cmid: int | None = None
    message_id: int | None = None


class MessagesRemoveChatUser(VKMethod[int]):
    """Allows the current user to leave a chat or, if the current user started the chat, allows the user to remove another user from the chat."""

    __returning__ = int
    __api_method__ = "messages.removeChatUser"

    chat_id: int
    member_id: int | None = None
    user_id: int | None = None


class MessagesRestore(VKMethod[int]):
    """Restores a deleted message."""

    __returning__ = int
    __api_method__ = "messages.restore"

    cmid: int | None = None
    group_id: int | None = None
    message_id: int | None = None
    peer_id: int | None = None


class MessagesSearch(VKMethod[dict]):
    """Returns a list of the current user's private messages that match search criteria."""

    __returning__ = dict
    __api_method__ = "messages.search"

    count: int = 20
    date: int | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    offset: int = 0
    peer_id: int | None = None
    preview_length: int = 0
    q: str | None = None


class MessagesSearchConversations(VKMethod[dict]):
    """Returns a list of the current user's conversations that match search criteria."""

    __returning__ = dict
    __api_method__ = "messages.searchConversations"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    group_id: int | None = None
    q: str | None = None


class MessagesSend(VKMethod[dict]):
    """Sends a message."""

    __returning__ = dict
    __api_method__ = "messages.send"

    attachment: str | None = None
    chat_id: int | None = None
    content_source: str | None = None
    disable_mentions: bool = False
    domain: str | None = None
    dont_parse_links: bool = False
    forward: str | None = None
    forward_messages: list[int] | None = None
    group_id: int | None = None
    intent: str = 'default'
    keyboard: str | None = None
    lat: float | None = None
    long: float | None = None
    message: str | None = None
    payload: str | None = None
    peer_id: int | None = None
    peer_ids: list[int] | None = None
    random_id: int | None = None
    reply_to: int | None = None
    sticker_id: int | None = None
    subscribe_id: int | None = None
    template: str | None = None
    user_id: int | None = None


class MessagesSendMessageEventAnswer(VKMethod[int]):
    """VK API method messages.sendMessageEventAnswer."""

    __returning__ = int
    __api_method__ = "messages.sendMessageEventAnswer"

    event_id: str
    peer_id: int
    user_id: int
    event_data: str | None = None


class MessagesSendReaction(VKMethod[int]):
    """Send message reaction"""

    __returning__ = int
    __api_method__ = "messages.sendReaction"

    cmid: int
    peer_id: int
    reaction_id: int


class MessagesSetActivity(VKMethod[int]):
    """Changes the status of a user as typing in a conversation."""

    __returning__ = int
    __api_method__ = "messages.setActivity"

    group_id: int | None = None
    peer_id: int | None = None
    type: str | None = None
    user_id: int | None = None


class MessagesSetChatPhoto(VKMethod[dict]):
    """Sets a previously-uploaded picture as the cover picture of a chat."""

    __returning__ = dict
    __api_method__ = "messages.setChatPhoto"

    file: str


class MessagesUnpin(VKMethod[int]):
    """VK API method messages.unpin."""

    __returning__ = int
    __api_method__ = "messages.unpin"

    peer_id: int
    group_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "messages.addChatUser": MessagesAddChatUser,
    "messages.addChatUsers": MessagesAddChatUsers,
    "messages.allowMessagesFromGroup": MessagesAllowMessagesFromGroup,
    "messages.createChat": MessagesCreateChat,
    "messages.delete": MessagesDelete,
    "messages.deleteChatPhoto": MessagesDeleteChatPhoto,
    "messages.deleteConversation": MessagesDeleteConversation,
    "messages.deleteReaction": MessagesDeleteReaction,
    "messages.denyMessagesFromGroup": MessagesDenyMessagesFromGroup,
    "messages.edit": MessagesEdit,
    "messages.editChat": MessagesEditChat,
    "messages.getByConversationMessageId": MessagesGetByConversationMessageId,
    "messages.getById": MessagesGetById,
    "messages.getChat": MessagesGetChat,
    "messages.getChatPreview": MessagesGetChatPreview,
    "messages.getConversationMembers": MessagesGetConversationMembers,
    "messages.getConversations": MessagesGetConversations,
    "messages.getConversationsById": MessagesGetConversationsById,
    "messages.getHistory": MessagesGetHistory,
    "messages.getHistoryAttachments": MessagesGetHistoryAttachments,
    "messages.getImportantMessages": MessagesGetImportantMessages,
    "messages.getIntentUsers": MessagesGetIntentUsers,
    "messages.getInviteLink": MessagesGetInviteLink,
    "messages.getLastActivity": MessagesGetLastActivity,
    "messages.getLongPollHistory": MessagesGetLongPollHistory,
    "messages.getLongPollServer": MessagesGetLongPollServer,
    "messages.getMessagesReactions": MessagesGetMessagesReactions,
    "messages.getReactedPeers": MessagesGetReactedPeers,
    "messages.getReactionsAssets": MessagesGetReactionsAssets,
    "messages.isMessagesFromGroupAllowed": MessagesIsMessagesFromGroupAllowed,
    "messages.joinChatByInviteLink": MessagesJoinChatByInviteLink,
    "messages.markAsAnsweredConversation": MessagesMarkAsAnsweredConversation,
    "messages.markAsImportant": MessagesMarkAsImportant,
    "messages.markAsImportantConversation": MessagesMarkAsImportantConversation,
    "messages.markAsRead": MessagesMarkAsRead,
    "messages.markReactionsAsRead": MessagesMarkReactionsAsRead,
    "messages.muteChatMentions": MessagesMuteChatMentions,
    "messages.pin": MessagesPin,
    "messages.removeChatUser": MessagesRemoveChatUser,
    "messages.restore": MessagesRestore,
    "messages.search": MessagesSearch,
    "messages.searchConversations": MessagesSearchConversations,
    "messages.send": MessagesSend,
    "messages.sendMessageEventAnswer": MessagesSendMessageEventAnswer,
    "messages.sendReaction": MessagesSendReaction,
    "messages.setActivity": MessagesSetActivity,
    "messages.setChatPhoto": MessagesSetChatPhoto,
    "messages.unpin": MessagesUnpin,
}

__all__ = ["MessagesAddChatUser", "MessagesAddChatUsers", "MessagesAllowMessagesFromGroup", "MessagesCreateChat", "MessagesDelete", "MessagesDeleteChatPhoto", "MessagesDeleteConversation", "MessagesDeleteReaction", "MessagesDenyMessagesFromGroup", "MessagesEdit", "MessagesEditChat", "MessagesGetByConversationMessageId", "MessagesGetById", "MessagesGetChat", "MessagesGetChatPreview", "MessagesGetConversationMembers", "MessagesGetConversations", "MessagesGetConversationsById", "MessagesGetHistory", "MessagesGetHistoryAttachments", "MessagesGetImportantMessages", "MessagesGetIntentUsers", "MessagesGetInviteLink", "MessagesGetLastActivity", "MessagesGetLongPollHistory", "MessagesGetLongPollServer", "MessagesGetMessagesReactions", "MessagesGetReactedPeers", "MessagesGetReactionsAssets", "MessagesIsMessagesFromGroupAllowed", "MessagesJoinChatByInviteLink", "MessagesMarkAsAnsweredConversation", "MessagesMarkAsImportant", "MessagesMarkAsImportantConversation", "MessagesMarkAsRead", "MessagesMarkReactionsAsRead", "MessagesMuteChatMentions", "MessagesPin", "MessagesRemoveChatUser", "MessagesRestore", "MessagesSearch", "MessagesSearchConversations", "MessagesSend", "MessagesSendMessageEventAnswer", "MessagesSendReaction", "MessagesSetActivity", "MessagesSetChatPhoto", "MessagesUnpin"]
