"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class NewsfeedAddBan(VKMethod[int]):
    """Prevents news from specified users and communities from appearing in the current user's newsfeed."""

    __returning__ = int
    __api_method__ = "newsfeed.addBan"

    group_ids: list[int] | None = None
    user_ids: list[int] | None = None


class NewsfeedDeleteBan(VKMethod[int]):
    """Allows news from previously banned users and communities to be shown in the current user's newsfeed."""

    __returning__ = int
    __api_method__ = "newsfeed.deleteBan"

    group_ids: list[int] | None = None
    user_ids: list[int] | None = None


class NewsfeedDeleteList(VKMethod[int]):
    """VK API method newsfeed.deleteList."""

    __returning__ = int
    __api_method__ = "newsfeed.deleteList"

    list_id: int


class NewsfeedGet(VKMethod[dict]):
    """Returns data required to show newsfeed for the current user."""

    __returning__ = dict
    __api_method__ = "newsfeed.get"

    count: int | None = None
    end_time: int | None = None
    fields: list[str] | None = None
    filters: list[str] | None = None
    max_photos: int | None = None
    return_banned: bool | None = None
    section: str | None = None
    source_ids: str | None = None
    start_from: str | None = None
    start_time: int | None = None


class NewsfeedGetBanned(VKMethod[dict]):
    """Returns a list of users and communities banned from the current user's newsfeed."""

    __returning__ = dict
    __api_method__ = "newsfeed.getBanned"

    extended: bool | None = None
    fields: list[str] | None = None
    name_case: str | None = None


class NewsfeedGetComments(VKMethod[dict]):
    """Returns a list of comments in the current user's newsfeed."""

    __returning__ = dict
    __api_method__ = "newsfeed.getComments"

    count: int = 30
    end_time: int | None = None
    fields: list[str] | None = None
    filters: list[str] | None = None
    last_comments_count: int = 0
    reposts: str | None = None
    start_from: str | None = None
    start_time: int | None = None


class NewsfeedGetLists(VKMethod[dict]):
    """Returns a list of newsfeeds followed by the current user."""

    __returning__ = dict
    __api_method__ = "newsfeed.getLists"

    extended: bool = False
    list_ids: list[int] | None = None


class NewsfeedGetMentions(VKMethod[dict]):
    """Returns a list of posts on user walls in which the current user is mentioned."""

    __returning__ = dict
    __api_method__ = "newsfeed.getMentions"

    count: int = 20
    end_time: int | None = None
    offset: int | None = None
    owner_id: int | None = None
    start_time: int | None = None


class NewsfeedGetRecommended(VKMethod[dict]):
    """, Returns a list of newsfeeds recommended to the current user."""

    __returning__ = dict
    __api_method__ = "newsfeed.getRecommended"

    count: int | None = None
    end_time: int | None = None
    fields: list[str] | None = None
    max_photos: int | None = None
    start_from: str | None = None
    start_time: int | None = None


class NewsfeedGetSuggestedSources(VKMethod[dict]):
    """Returns communities and users that current user is suggested to follow."""

    __returning__ = dict
    __api_method__ = "newsfeed.getSuggestedSources"

    count: int = 20
    fields: list[str] | None = None
    offset: int | None = None
    shuffle: bool | None = None


class NewsfeedIgnoreItem(VKMethod[dict]):
    """Hides an item from the newsfeed."""

    __returning__ = dict
    __api_method__ = "newsfeed.ignoreItem"

    type: str
    item_id: int = 0
    owner_id: int = 0


class NewsfeedSaveList(VKMethod[int]):
    """Creates and edits user newsfeed lists"""

    __returning__ = int
    __api_method__ = "newsfeed.saveList"

    source_ids: list[int]
    title: str
    list_id: int | None = None
    no_reposts: bool | None = None


class NewsfeedSearch(VKMethod[dict]):
    """Returns search results by statuses."""

    __returning__ = dict
    __api_method__ = "newsfeed.search"

    count: int = 30
    end_time: int | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    latitude: float | None = None
    longitude: float | None = None
    q: str | None = None
    start_from: str | None = None
    start_time: int | None = None


class NewsfeedUnignoreItem(VKMethod[int]):
    """Returns a hidden item to the newsfeed."""

    __returning__ = int
    __api_method__ = "newsfeed.unignoreItem"

    type: str
    item_id: int = 0
    owner_id: int = 0
    track_code: str | None = None


class NewsfeedUnsubscribe(VKMethod[int]):
    """Unsubscribes the current user from specified newsfeeds."""

    __returning__ = int
    __api_method__ = "newsfeed.unsubscribe"

    item_id: int
    type: str
    owner_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "newsfeed.addBan": NewsfeedAddBan,
    "newsfeed.deleteBan": NewsfeedDeleteBan,
    "newsfeed.deleteList": NewsfeedDeleteList,
    "newsfeed.get": NewsfeedGet,
    "newsfeed.getBanned": NewsfeedGetBanned,
    "newsfeed.getComments": NewsfeedGetComments,
    "newsfeed.getLists": NewsfeedGetLists,
    "newsfeed.getMentions": NewsfeedGetMentions,
    "newsfeed.getRecommended": NewsfeedGetRecommended,
    "newsfeed.getSuggestedSources": NewsfeedGetSuggestedSources,
    "newsfeed.ignoreItem": NewsfeedIgnoreItem,
    "newsfeed.saveList": NewsfeedSaveList,
    "newsfeed.search": NewsfeedSearch,
    "newsfeed.unignoreItem": NewsfeedUnignoreItem,
    "newsfeed.unsubscribe": NewsfeedUnsubscribe,
}

__all__ = ["NewsfeedAddBan", "NewsfeedDeleteBan", "NewsfeedDeleteList", "NewsfeedGet", "NewsfeedGetBanned", "NewsfeedGetComments", "NewsfeedGetLists", "NewsfeedGetMentions", "NewsfeedGetRecommended", "NewsfeedGetSuggestedSources", "NewsfeedIgnoreItem", "NewsfeedSaveList", "NewsfeedSearch", "NewsfeedUnignoreItem", "NewsfeedUnsubscribe"]
