"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class NotesAdd(VKMethod[int]):
    """Creates a new note for the current user."""

    __returning__ = int
    __api_method__ = "notes.add"

    text: str
    title: str
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None


class NotesCreateComment(VKMethod[int]):
    """Adds a new comment on a note."""

    __returning__ = int
    __api_method__ = "notes.createComment"

    message: str
    note_id: int
    guid: str | None = None
    owner_id: int | None = None
    reply_to: int | None = None


class NotesDelete(VKMethod[int]):
    """Deletes a note of the current user."""

    __returning__ = int
    __api_method__ = "notes.delete"

    note_id: int


class NotesDeleteComment(VKMethod[int]):
    """Deletes a comment on a note."""

    __returning__ = int
    __api_method__ = "notes.deleteComment"

    comment_id: int
    owner_id: int | None = None


class NotesEdit(VKMethod[int]):
    """Edits a note of the current user."""

    __returning__ = int
    __api_method__ = "notes.edit"

    note_id: int
    text: str
    title: str
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None


class NotesEditComment(VKMethod[int]):
    """Edits a comment on a note."""

    __returning__ = int
    __api_method__ = "notes.editComment"

    comment_id: int
    message: str
    owner_id: int | None = None


class NotesGet(VKMethod[dict]):
    """Returns a list of notes created by a user."""

    __returning__ = dict
    __api_method__ = "notes.get"

    count: int = 20
    note_ids: list[int] | None = None
    offset: int = 0
    sort: int = 0
    user_id: int | None = None


class NotesGetById(VKMethod[dict]):
    """Returns a note by its ID."""

    __returning__ = dict
    __api_method__ = "notes.getById"

    note_id: int
    need_wiki: bool = False
    owner_id: int | None = None


class NotesGetComments(VKMethod[dict]):
    """Returns a list of comments on a note."""

    __returning__ = dict
    __api_method__ = "notes.getComments"

    note_id: int
    count: int = 20
    offset: int = 0
    owner_id: int | None = None
    sort: int = 0


class NotesRestoreComment(VKMethod[int]):
    """Restores a deleted comment on a note."""

    __returning__ = int
    __api_method__ = "notes.restoreComment"

    comment_id: int
    owner_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "notes.add": NotesAdd,
    "notes.createComment": NotesCreateComment,
    "notes.delete": NotesDelete,
    "notes.deleteComment": NotesDeleteComment,
    "notes.edit": NotesEdit,
    "notes.editComment": NotesEditComment,
    "notes.get": NotesGet,
    "notes.getById": NotesGetById,
    "notes.getComments": NotesGetComments,
    "notes.restoreComment": NotesRestoreComment,
}

__all__ = ["NotesAdd", "NotesCreateComment", "NotesDelete", "NotesDeleteComment", "NotesEdit", "NotesEditComment", "NotesGet", "NotesGetById", "NotesGetComments", "NotesRestoreComment"]
