"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class NotificationsGet(VKMethod[dict]):
    """Returns a list of notifications about other users' feedback to the current user's wall posts."""

    __returning__ = dict
    __api_method__ = "notifications.get"

    count: int = 30
    end_time: int | None = None
    filters: list[str] | None = None
    start_from: str | None = None
    start_time: int | None = None


class NotificationsMarkAsViewed(VKMethod[int]):
    """Resets the counter of new notifications about other users' feedback to the current user's wall posts."""

    __returning__ = int
    __api_method__ = "notifications.markAsViewed"


class NotificationsSendMessage(VKMethod[list]):
    """VK API method notifications.sendMessage."""

    __returning__ = list
    __api_method__ = "notifications.sendMessage"

    message: str
    user_ids: list[int]
    fragment: str | None = None
    group_id: int | None = None
    random_id: int | None = None
    sending_mode: str = 'immediately'



REGISTRY: dict[str, type[VKMethod]] = {
    "notifications.get": NotificationsGet,
    "notifications.markAsViewed": NotificationsMarkAsViewed,
    "notifications.sendMessage": NotificationsSendMessage,
}

__all__ = ["NotificationsGet", "NotificationsMarkAsViewed", "NotificationsSendMessage"]
