"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class OrdersCancelSubscription(VKMethod[int]):
    """VK API method orders.cancelSubscription."""

    __returning__ = int
    __api_method__ = "orders.cancelSubscription"

    subscription_id: int
    user_id: int
    pending_cancel: bool = False


class OrdersChangeState(VKMethod[dict]):
    """Changes order status."""

    __returning__ = dict
    __api_method__ = "orders.changeState"

    action: str
    order_id: int
    app_order_id: int | None = None
    test_mode: bool | None = None


class OrdersGet(VKMethod[list]):
    """Returns a list of orders."""

    __returning__ = list
    __api_method__ = "orders.get"

    count: int = 100
    offset: int = 0
    test_mode: bool | None = None


class OrdersGetAmount(VKMethod[list]):
    """VK API method orders.getAmount."""

    __returning__ = list
    __api_method__ = "orders.getAmount"

    user_id: int
    votes: list[str]


class OrdersGetById(VKMethod[list]):
    """Returns information about orders by their IDs."""

    __returning__ = list
    __api_method__ = "orders.getById"

    order_id: int | None = None
    order_ids: list[int] | None = None
    test_mode: bool | None = None


class OrdersGetUserSubscriptionById(VKMethod[dict]):
    """VK API method orders.getUserSubscriptionById."""

    __returning__ = dict
    __api_method__ = "orders.getUserSubscriptionById"

    subscription_id: int
    user_id: int


class OrdersGetUserSubscriptions(VKMethod[dict]):
    """VK API method orders.getUserSubscriptions."""

    __returning__ = dict
    __api_method__ = "orders.getUserSubscriptions"

    user_id: int



REGISTRY: dict[str, type[VKMethod]] = {
    "orders.cancelSubscription": OrdersCancelSubscription,
    "orders.changeState": OrdersChangeState,
    "orders.get": OrdersGet,
    "orders.getAmount": OrdersGetAmount,
    "orders.getById": OrdersGetById,
    "orders.getUserSubscriptionById": OrdersGetUserSubscriptionById,
    "orders.getUserSubscriptions": OrdersGetUserSubscriptions,
}

__all__ = ["OrdersCancelSubscription", "OrdersChangeState", "OrdersGet", "OrdersGetAmount", "OrdersGetById", "OrdersGetUserSubscriptionById", "OrdersGetUserSubscriptions"]
