"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from pydantic import Field

from ..base import VKMethod


class PagesClearCache(VKMethod[int]):
    """Allows to clear the cache of particular 'external' pages which may be attached to VK posts."""

    __returning__ = int
    __api_method__ = "pages.clearCache"

    url: str


class PagesGet(VKMethod[dict]):
    """Returns information about a wiki page."""

    __returning__ = dict
    __api_method__ = "pages.get"

    global_: bool | None = Field(default=None, alias='global')
    need_html: bool | None = None
    need_source: bool | None = None
    owner_id: int | None = None
    page_id: int | None = None
    site_preview: bool | None = None
    title: str | None = None


class PagesGetHistory(VKMethod[list]):
    """Returns a list of all previous versions of a wiki page."""

    __returning__ = list
    __api_method__ = "pages.getHistory"

    page_id: int
    group_id: int | None = None
    user_id: int | None = None


class PagesGetTitles(VKMethod[list]):
    """Returns a list of wiki pages in a group."""

    __returning__ = list
    __api_method__ = "pages.getTitles"

    group_id: int | None = None


class PagesGetVersion(VKMethod[dict]):
    """Returns the text of one of the previous versions of a wiki page."""

    __returning__ = dict
    __api_method__ = "pages.getVersion"

    version_id: int
    group_id: int | None = None
    need_html: bool | None = None
    user_id: int | None = None


class PagesParseWiki(VKMethod[dict]):
    """Returns HTML representation of the wiki markup."""

    __returning__ = dict
    __api_method__ = "pages.parseWiki"

    text: str
    group_id: int | None = None


class PagesSave(VKMethod[int]):
    """Saves the text of a wiki page."""

    __returning__ = int
    __api_method__ = "pages.save"

    group_id: int | None = None
    page_id: int | None = None
    text: str | None = None
    title: str | None = None
    user_id: int | None = None


class PagesSaveAccess(VKMethod[int]):
    """Saves modified read and edit access settings for a wiki page."""

    __returning__ = int
    __api_method__ = "pages.saveAccess"

    page_id: int
    edit: int | None = None
    group_id: int | None = None
    user_id: int | None = None
    view: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "pages.clearCache": PagesClearCache,
    "pages.get": PagesGet,
    "pages.getHistory": PagesGetHistory,
    "pages.getTitles": PagesGetTitles,
    "pages.getVersion": PagesGetVersion,
    "pages.parseWiki": PagesParseWiki,
    "pages.save": PagesSave,
    "pages.saveAccess": PagesSaveAccess,
}

__all__ = ["PagesClearCache", "PagesGet", "PagesGetHistory", "PagesGetTitles", "PagesGetVersion", "PagesParseWiki", "PagesSave", "PagesSaveAccess"]
