"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class PhotosConfirmTag(VKMethod[int]):
    """Confirms a tag on a photo."""

    __returning__ = int
    __api_method__ = "photos.confirmTag"

    photo_id: str
    tag_id: int
    owner_id: int | None = None


class PhotosCopy(VKMethod[int]):
    """Allows to copy a photo to the "Saved photos" album"""

    __returning__ = int
    __api_method__ = "photos.copy"

    owner_id: int
    photo_id: int
    access_key: str | None = None


class PhotosCreateAlbum(VKMethod[dict]):
    """Creates an empty photo album."""

    __returning__ = dict
    __api_method__ = "photos.createAlbum"

    title: str
    comments_disabled: bool | None = None
    description: str | None = None
    group_id: int | None = None
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None
    upload_by_admins_only: bool | None = None


class PhotosCreateComment(VKMethod[int]):
    """Adds a new comment on the photo."""

    __returning__ = int
    __api_method__ = "photos.createComment"

    photo_id: int
    access_key: str | None = None
    attachments: list[str] | None = None
    from_group: bool | None = None
    guid: str | None = None
    message: str | None = None
    owner_id: int | None = None
    reply_to_comment: int | None = None
    sticker_id: int | None = None


class PhotosDelete(VKMethod[int]):
    """Deletes a photo."""

    __returning__ = int
    __api_method__ = "photos.delete"

    owner_id: int | None = None
    photo_id: int | None = None
    photos: list[str] | None = None


class PhotosDeleteAlbum(VKMethod[int]):
    """Deletes a photo album belonging to the current user."""

    __returning__ = int
    __api_method__ = "photos.deleteAlbum"

    album_id: int
    group_id: int | None = None


class PhotosDeleteComment(VKMethod[int]):
    """Deletes a comment on the photo."""

    __returning__ = int
    __api_method__ = "photos.deleteComment"

    comment_id: int
    owner_id: int | None = None


class PhotosEdit(VKMethod[int]):
    """Edits the caption of a photo."""

    __returning__ = int
    __api_method__ = "photos.edit"

    photo_id: int
    caption: str | None = None
    delete_place: bool | None = None
    foursquare_id: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    owner_id: int | None = None
    place_str: str | None = None


class PhotosEditAlbum(VKMethod[int]):
    """Edits information about a photo album."""

    __returning__ = int
    __api_method__ = "photos.editAlbum"

    album_id: int
    comments_disabled: bool | None = None
    description: str | None = None
    owner_id: int | None = None
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None
    title: str | None = None
    upload_by_admins_only: bool | None = None


class PhotosEditComment(VKMethod[int]):
    """Edits a comment on a photo."""

    __returning__ = int
    __api_method__ = "photos.editComment"

    comment_id: int
    attachments: list[str] | None = None
    message: str | None = None
    owner_id: int | None = None


class PhotosGet(VKMethod[dict]):
    """Returns a list of a user's or community's photos."""

    __returning__ = dict
    __api_method__ = "photos.get"

    album_id: str | None = None
    count: int = 50
    extended: bool | None = None
    feed: int | None = None
    feed_type: str | None = None
    offset: int | None = None
    owner_id: int | None = None
    photo_ids: list[str] | None = None
    photo_sizes: bool | None = None
    rev: bool | None = None


class PhotosGetAlbums(VKMethod[dict]):
    """Returns a list of a user's or community's photo albums."""

    __returning__ = dict
    __api_method__ = "photos.getAlbums"

    album_ids: list[int] | None = None
    count: int | None = None
    need_covers: bool | None = None
    need_system: bool | None = None
    offset: int | None = None
    owner_id: int | None = None
    photo_sizes: bool | None = None


class PhotosGetAlbumsCount(VKMethod[int]):
    """Returns the number of photo albums belonging to a user or community."""

    __returning__ = int
    __api_method__ = "photos.getAlbumsCount"

    group_id: int | None = None
    need_system: bool | None = None
    user_id: int | None = None


class PhotosGetAll(VKMethod[dict]):
    """Returns a list of photos belonging to a user or community, in reverse chronological order."""

    __returning__ = dict
    __api_method__ = "photos.getAll"

    count: int = 20
    extended: bool | None = None
    need_hidden: bool | None = None
    no_service_albums: bool | None = None
    offset: int | None = None
    owner_id: int | None = None
    photo_sizes: bool | None = None
    skip_hidden: bool | None = None


class PhotosGetAllComments(VKMethod[dict]):
    """Returns a list of comments on a specific photo album or all albums of the user sorted in reverse chronological order."""

    __returning__ = dict
    __api_method__ = "photos.getAllComments"

    album_id: int | None = None
    count: int | None = None
    need_likes: bool | None = None
    offset: int | None = None
    owner_id: int | None = None


class PhotosGetById(VKMethod[list]):
    """Returns information about photos by their IDs."""

    __returning__ = list
    __api_method__ = "photos.getById"

    photos: list[str]
    extended: bool | None = None
    photo_sizes: bool | None = None


class PhotosGetChatUploadServer(VKMethod[dict]):
    """Returns an upload link for chat cover pictures."""

    __returning__ = dict
    __api_method__ = "photos.getChatUploadServer"

    chat_id: int
    crop_width: int | None = None
    crop_x: int | None = None
    crop_y: int | None = None


class PhotosGetComments(VKMethod[dict]):
    """Returns a list of comments on a photo."""

    __returning__ = dict
    __api_method__ = "photos.getComments"

    photo_id: int
    access_key: str | None = None
    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    need_likes: bool | None = None
    offset: int | None = None
    owner_id: int | None = None
    sort: str | None = None
    start_comment_id: int | None = None


class PhotosGetMarketAlbumUploadServer(VKMethod[dict]):
    """Returns the server address for market album photo upload."""

    __returning__ = dict
    __api_method__ = "photos.getMarketAlbumUploadServer"

    group_id: int


class PhotosGetMessagesUploadServer(VKMethod[dict]):
    """Returns the server address for photo upload in a private message for a user."""

    __returning__ = dict
    __api_method__ = "photos.getMessagesUploadServer"

    peer_id: int | None = None


class PhotosGetNewTags(VKMethod[dict]):
    """Returns a list of photos with tags that have not been viewed."""

    __returning__ = dict
    __api_method__ = "photos.getNewTags"

    count: int = 20
    offset: int | None = None


class PhotosGetOwnerCoverPhotoUploadServer(VKMethod[dict]):
    """Returns the server address for owner cover upload."""

    __returning__ = dict
    __api_method__ = "photos.getOwnerCoverPhotoUploadServer"

    crop_x: int = 0
    crop_x2: int = 795
    crop_y: int = 0
    crop_y2: int = 200
    group_id: int | None = None
    is_video_cover: bool = False


class PhotosGetOwnerPhotoUploadServer(VKMethod[dict]):
    """Returns an upload server address for a profile or community photo."""

    __returning__ = dict
    __api_method__ = "photos.getOwnerPhotoUploadServer"

    owner_id: int | None = None


class PhotosGetTags(VKMethod[list]):
    """Returns a list of tags on a photo."""

    __returning__ = list
    __api_method__ = "photos.getTags"

    photo_id: int
    access_key: str | None = None
    owner_id: int | None = None


class PhotosGetUploadServer(VKMethod[dict]):
    """Returns the server address for photo upload."""

    __returning__ = dict
    __api_method__ = "photos.getUploadServer"

    album_id: int | None = None
    group_id: int | None = None


class PhotosGetUserPhotos(VKMethod[dict]):
    """Returns a list of photos in which a user is tagged."""

    __returning__ = dict
    __api_method__ = "photos.getUserPhotos"

    count: int = 20
    extended: bool | None = None
    offset: int | None = None
    sort: str | None = None
    user_id: int | None = None


class PhotosGetWallUploadServer(VKMethod[dict]):
    """Returns the server address for photo upload onto a user's wall."""

    __returning__ = dict
    __api_method__ = "photos.getWallUploadServer"

    group_id: int | None = None


class PhotosMakeCover(VKMethod[int]):
    """Makes a photo into an album cover."""

    __returning__ = int
    __api_method__ = "photos.makeCover"

    photo_id: int
    album_id: int | None = None
    owner_id: int | None = None


class PhotosMove(VKMethod[int]):
    """Moves a photo from one album to another."""

    __returning__ = int
    __api_method__ = "photos.move"

    photo_ids: list[int]
    target_album_id: int
    owner_id: int | None = None


class PhotosPutTag(VKMethod[int]):
    """Adds a tag on the photo."""

    __returning__ = int
    __api_method__ = "photos.putTag"

    photo_id: int
    user_id: int
    owner_id: int | None = None
    x: float | None = None
    x2: float | None = None
    y: float | None = None
    y2: float | None = None


class PhotosRemoveTag(VKMethod[int]):
    """Removes a tag from a photo."""

    __returning__ = int
    __api_method__ = "photos.removeTag"

    photo_id: int
    tag_id: int
    owner_id: int | None = None


class PhotosReorderAlbums(VKMethod[int]):
    """Reorders the album in the list of user albums."""

    __returning__ = int
    __api_method__ = "photos.reorderAlbums"

    album_id: int
    after: int | None = None
    before: int | None = None
    owner_id: int | None = None


class PhotosReorderPhotos(VKMethod[int]):
    """Reorders the photo in the list of photos of the user album."""

    __returning__ = int
    __api_method__ = "photos.reorderPhotos"

    photo_id: int
    after: int | None = None
    before: int | None = None
    owner_id: int | None = None


class PhotosReport(VKMethod[int]):
    """Reports (submits a complaint about) a photo."""

    __returning__ = int
    __api_method__ = "photos.report"

    owner_id: int
    photo_id: int
    reason: int | None = None


class PhotosReportComment(VKMethod[int]):
    """Reports (submits a complaint about) a comment on a photo."""

    __returning__ = int
    __api_method__ = "photos.reportComment"

    comment_id: int
    owner_id: int
    reason: int | None = None


class PhotosRestore(VKMethod[int]):
    """Restores a deleted photo."""

    __returning__ = int
    __api_method__ = "photos.restore"

    photo_id: int
    owner_id: int | None = None


class PhotosRestoreComment(VKMethod[int]):
    """Restores a deleted comment on a photo."""

    __returning__ = int
    __api_method__ = "photos.restoreComment"

    comment_id: int
    owner_id: int | None = None


class PhotosSave(VKMethod[list]):
    """Saves photos after successful uploading."""

    __returning__ = list
    __api_method__ = "photos.save"

    album_id: int | None = None
    caption: str | None = None
    group_id: int | None = None
    hash: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    photos_list: str | None = None
    server: int | None = None


class PhotosSaveMarketAlbumPhoto(VKMethod[list]):
    """Saves market album photos after successful uploading."""

    __returning__ = list
    __api_method__ = "photos.saveMarketAlbumPhoto"

    group_id: int
    hash: str
    photo: str
    server: int


class PhotosSaveMessagesPhoto(VKMethod[list]):
    """Saves a photo after being successfully uploaded. URL obtained with [vk.com/dev/photos.getMessagesUploadServer|photos.getMessagesUploadServer] method."""

    __returning__ = list
    __api_method__ = "photos.saveMessagesPhoto"

    photo: str
    hash: str | None = None
    server: int | None = None


class PhotosSaveOwnerCoverPhoto(VKMethod[dict]):
    """Saves cover photo after successful uploading."""

    __returning__ = dict
    __api_method__ = "photos.saveOwnerCoverPhoto"

    crop_height: int = 0
    crop_width: int = 0
    crop_x: int = 0
    crop_y: int = 0
    hash: str | None = None
    is_video_cover: bool = False
    photo: str | None = None
    response_json: str | None = None


class PhotosSaveOwnerPhoto(VKMethod[dict]):
    """Saves a profile or community photo. Upload URL can be got with the [vk.com/dev/photos.getOwnerPhotoUploadServer|photos.getOwnerPhotoUploadServer] method."""

    __returning__ = dict
    __api_method__ = "photos.saveOwnerPhoto"

    hash: str | None = None
    photo: str | None = None
    server: str | None = None


class PhotosSaveWallPhoto(VKMethod[list]):
    """Saves a photo to a user's or community's wall after being uploaded."""

    __returning__ = list
    __api_method__ = "photos.saveWallPhoto"

    photo: str
    caption: str | None = None
    group_id: int | None = None
    hash: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    server: int | None = None
    user_id: int | None = None


class PhotosSearch(VKMethod[dict]):
    """Returns a list of photos."""

    __returning__ = dict
    __api_method__ = "photos.search"

    count: int = 100
    end_time: float | None = None
    lat: float | None = None
    long: float | None = None
    offset: int | None = None
    q: str | None = None
    radius: int = 5000
    sort: int | None = None
    start_time: float | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "photos.confirmTag": PhotosConfirmTag,
    "photos.copy": PhotosCopy,
    "photos.createAlbum": PhotosCreateAlbum,
    "photos.createComment": PhotosCreateComment,
    "photos.delete": PhotosDelete,
    "photos.deleteAlbum": PhotosDeleteAlbum,
    "photos.deleteComment": PhotosDeleteComment,
    "photos.edit": PhotosEdit,
    "photos.editAlbum": PhotosEditAlbum,
    "photos.editComment": PhotosEditComment,
    "photos.get": PhotosGet,
    "photos.getAlbums": PhotosGetAlbums,
    "photos.getAlbumsCount": PhotosGetAlbumsCount,
    "photos.getAll": PhotosGetAll,
    "photos.getAllComments": PhotosGetAllComments,
    "photos.getById": PhotosGetById,
    "photos.getChatUploadServer": PhotosGetChatUploadServer,
    "photos.getComments": PhotosGetComments,
    "photos.getMarketAlbumUploadServer": PhotosGetMarketAlbumUploadServer,
    "photos.getMessagesUploadServer": PhotosGetMessagesUploadServer,
    "photos.getNewTags": PhotosGetNewTags,
    "photos.getOwnerCoverPhotoUploadServer": PhotosGetOwnerCoverPhotoUploadServer,
    "photos.getOwnerPhotoUploadServer": PhotosGetOwnerPhotoUploadServer,
    "photos.getTags": PhotosGetTags,
    "photos.getUploadServer": PhotosGetUploadServer,
    "photos.getUserPhotos": PhotosGetUserPhotos,
    "photos.getWallUploadServer": PhotosGetWallUploadServer,
    "photos.makeCover": PhotosMakeCover,
    "photos.move": PhotosMove,
    "photos.putTag": PhotosPutTag,
    "photos.removeTag": PhotosRemoveTag,
    "photos.reorderAlbums": PhotosReorderAlbums,
    "photos.reorderPhotos": PhotosReorderPhotos,
    "photos.report": PhotosReport,
    "photos.reportComment": PhotosReportComment,
    "photos.restore": PhotosRestore,
    "photos.restoreComment": PhotosRestoreComment,
    "photos.save": PhotosSave,
    "photos.saveMarketAlbumPhoto": PhotosSaveMarketAlbumPhoto,
    "photos.saveMessagesPhoto": PhotosSaveMessagesPhoto,
    "photos.saveOwnerCoverPhoto": PhotosSaveOwnerCoverPhoto,
    "photos.saveOwnerPhoto": PhotosSaveOwnerPhoto,
    "photos.saveWallPhoto": PhotosSaveWallPhoto,
    "photos.search": PhotosSearch,
}

__all__ = ["PhotosConfirmTag", "PhotosCopy", "PhotosCreateAlbum", "PhotosCreateComment", "PhotosDelete", "PhotosDeleteAlbum", "PhotosDeleteComment", "PhotosEdit", "PhotosEditAlbum", "PhotosEditComment", "PhotosGet", "PhotosGetAlbums", "PhotosGetAlbumsCount", "PhotosGetAll", "PhotosGetAllComments", "PhotosGetById", "PhotosGetChatUploadServer", "PhotosGetComments", "PhotosGetMarketAlbumUploadServer", "PhotosGetMessagesUploadServer", "PhotosGetNewTags", "PhotosGetOwnerCoverPhotoUploadServer", "PhotosGetOwnerPhotoUploadServer", "PhotosGetTags", "PhotosGetUploadServer", "PhotosGetUserPhotos", "PhotosGetWallUploadServer", "PhotosMakeCover", "PhotosMove", "PhotosPutTag", "PhotosRemoveTag", "PhotosReorderAlbums", "PhotosReorderPhotos", "PhotosReport", "PhotosReportComment", "PhotosRestore", "PhotosRestoreComment", "PhotosSave", "PhotosSaveMarketAlbumPhoto", "PhotosSaveMessagesPhoto", "PhotosSaveOwnerCoverPhoto", "PhotosSaveOwnerPhoto", "PhotosSaveWallPhoto", "PhotosSearch"]
