"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class PodcastsSearchPodcast(VKMethod[dict]):
    """VK API method podcasts.searchPodcast."""

    __returning__ = dict
    __api_method__ = "podcasts.searchPodcast"

    search_string: str
    count: int = 20
    offset: int = 0



REGISTRY: dict[str, type[VKMethod]] = {
    "podcasts.searchPodcast": PodcastsSearchPodcast,
}

__all__ = ["PodcastsSearchPodcast"]
