"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class PollsAddVote(VKMethod[int]):
    """Adds the current user's vote to the selected answer in the poll."""

    __returning__ = int
    __api_method__ = "polls.addVote"

    answer_ids: list[int]
    poll_id: int
    is_board: bool | None = None
    owner_id: int | None = None


class PollsCreate(VKMethod[dict]):
    """Creates polls that can be attached to the users' or communities' posts."""

    __returning__ = dict
    __api_method__ = "polls.create"

    add_answers: str | None = None
    app_id: int | None = None
    background_id: str | None = None
    disable_unvote: bool | None = None
    end_date: int | None = None
    is_anonymous: bool | None = None
    is_multiple: bool | None = None
    owner_id: int | None = None
    photo_id: int | None = None
    question: str | None = None


class PollsDeleteVote(VKMethod[int]):
    """Deletes the current user's vote from the selected answer in the poll."""

    __returning__ = int
    __api_method__ = "polls.deleteVote"

    poll_id: int
    is_board: bool | None = None
    owner_id: int | None = None


class PollsEdit(VKMethod[int]):
    """Edits created polls"""

    __returning__ = int
    __api_method__ = "polls.edit"

    poll_id: int
    add_answers: str | None = None
    background_id: str | None = None
    delete_answers: str | None = None
    edit_answers: str | None = None
    end_date: int | None = None
    owner_id: int | None = None
    photo_id: int | None = None
    question: str | None = None


class PollsGetBackgrounds(VKMethod[list]):
    """VK API method polls.getBackgrounds."""

    __returning__ = list
    __api_method__ = "polls.getBackgrounds"


class PollsGetById(VKMethod[dict]):
    """Returns detailed information about a poll by its ID."""

    __returning__ = dict
    __api_method__ = "polls.getById"

    poll_id: int
    extended: bool | None = None
    fields: list[str] | None = None
    friends_count: int = 3
    is_board: bool | None = None
    name_case: str | None = None
    owner_id: int | None = None


class PollsGetPhotoUploadServer(VKMethod[dict]):
    """VK API method polls.getPhotoUploadServer."""

    __returning__ = dict
    __api_method__ = "polls.getPhotoUploadServer"

    owner_id: int | None = None


class PollsGetVoters(VKMethod[list]):
    """Returns a list of IDs of users who selected specific answers in the poll."""

    __returning__ = list
    __api_method__ = "polls.getVoters"

    answer_ids: list[int]
    poll_id: int
    count: int | None = None
    fields: list[str] | None = None
    friends_only: bool | None = None
    is_board: bool | None = None
    name_case: str | None = None
    offset: int | None = None
    owner_id: int | None = None


class PollsSavePhoto(VKMethod[dict]):
    """VK API method polls.savePhoto."""

    __returning__ = dict
    __api_method__ = "polls.savePhoto"

    hash: str | None = None
    photo: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "polls.addVote": PollsAddVote,
    "polls.create": PollsCreate,
    "polls.deleteVote": PollsDeleteVote,
    "polls.edit": PollsEdit,
    "polls.getBackgrounds": PollsGetBackgrounds,
    "polls.getById": PollsGetById,
    "polls.getPhotoUploadServer": PollsGetPhotoUploadServer,
    "polls.getVoters": PollsGetVoters,
    "polls.savePhoto": PollsSavePhoto,
}

__all__ = ["PollsAddVote", "PollsCreate", "PollsDeleteVote", "PollsEdit", "PollsGetBackgrounds", "PollsGetById", "PollsGetPhotoUploadServer", "PollsGetVoters", "PollsSavePhoto"]
