"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class PrettyCardsCreate(VKMethod[dict]):
    """VK API method prettyCards.create."""

    __returning__ = dict
    __api_method__ = "prettyCards.create"

    link: str
    owner_id: int
    photo: str
    title: str
    button: str | None = None
    price: str | None = None
    price_old: str | None = None


class PrettyCardsDelete(VKMethod[dict]):
    """VK API method prettyCards.delete."""

    __returning__ = dict
    __api_method__ = "prettyCards.delete"

    card_id: int
    owner_id: int


class PrettyCardsEdit(VKMethod[dict]):
    """VK API method prettyCards.edit."""

    __returning__ = dict
    __api_method__ = "prettyCards.edit"

    card_id: int
    owner_id: int
    button: str | None = None
    link: str | None = None
    photo: str | None = None
    price: str | None = None
    price_old: str | None = None
    title: str | None = None


class PrettyCardsGet(VKMethod[dict]):
    """VK API method prettyCards.get."""

    __returning__ = dict
    __api_method__ = "prettyCards.get"

    owner_id: int
    count: int = 10
    offset: int = 0


class PrettyCardsGetById(VKMethod[list]):
    """VK API method prettyCards.getById."""

    __returning__ = list
    __api_method__ = "prettyCards.getById"

    card_ids: list[int]
    owner_id: int


class PrettyCardsGetUploadURL(VKMethod[dict]):
    """VK API method prettyCards.getUploadURL."""

    __returning__ = dict
    __api_method__ = "prettyCards.getUploadURL"



REGISTRY: dict[str, type[VKMethod]] = {
    "prettyCards.create": PrettyCardsCreate,
    "prettyCards.delete": PrettyCardsDelete,
    "prettyCards.edit": PrettyCardsEdit,
    "prettyCards.get": PrettyCardsGet,
    "prettyCards.getById": PrettyCardsGetById,
    "prettyCards.getUploadURL": PrettyCardsGetUploadURL,
}

__all__ = ["PrettyCardsCreate", "PrettyCardsDelete", "PrettyCardsEdit", "PrettyCardsGet", "PrettyCardsGetById", "PrettyCardsGetUploadURL"]
