"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class SearchGetHints(VKMethod[dict]):
    """Allows the programmer to do a quick search for any substring."""

    __returning__ = dict
    __api_method__ = "search.getHints"

    fields: list[str] | None = None
    filters: list[str] | None = None
    limit: int = 9
    offset: int | None = None
    q: str | None = None
    search_global: bool = True



REGISTRY: dict[str, type[VKMethod]] = {
    "search.getHints": SearchGetHints,
}

__all__ = ["SearchGetHints"]
