"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class SecureAddAppEvent(VKMethod[int]):
    """Adds user activity information to an application"""

    __returning__ = int
    __api_method__ = "secure.addAppEvent"

    activity_id: int
    user_id: int | None = None
    value: int | None = None


class SecureCheckToken(VKMethod[dict]):
    """Checks the user authentication in 'IFrame' and 'Flash' apps using the 'access_token' parameter."""

    __returning__ = dict
    __api_method__ = "secure.checkToken"

    ip: str | None = None
    token: str | None = None


class SecureGetAppBalance(VKMethod[int]):
    """Returns payment balance of the application in hundredth of a vote."""

    __returning__ = int
    __api_method__ = "secure.getAppBalance"


class SecureGetSMSHistory(VKMethod[list]):
    """Shows a list of SMS notifications sent by the application using [vk.com/dev/secure.sendSMSNotification|secure.sendSMSNotification] method."""

    __returning__ = list
    __api_method__ = "secure.getSMSHistory"

    date_from: int | None = None
    date_to: int | None = None
    limit: int = 1000
    user_id: int | None = None


class SecureGetTransactionsHistory(VKMethod[list]):
    """Shows history of votes transaction between users and the application."""

    __returning__ = list
    __api_method__ = "secure.getTransactionsHistory"

    date_from: int | None = None
    date_to: int | None = None
    limit: int = 1000
    type: int | None = None
    uid_from: int | None = None
    uid_to: int | None = None


class SecureGetUserLevel(VKMethod[list]):
    """Returns one of the previously set game levels of one or more users in the application."""

    __returning__ = list
    __api_method__ = "secure.getUserLevel"

    user_ids: list[int]


class SecureGiveEventSticker(VKMethod[list]):
    """Opens the game achievement and gives the user a sticker"""

    __returning__ = list
    __api_method__ = "secure.giveEventSticker"

    achievement_id: int
    user_ids: list[int]


class SecureSendNotification(VKMethod[list]):
    """Sends notification to the user."""

    __returning__ = list
    __api_method__ = "secure.sendNotification"

    message: str
    notification_id: int = 0
    promo_id: int = 0
    user_id: int | None = None
    user_ids: list[int] | None = None


class SecureSendSMSNotification(VKMethod[int]):
    """Sends 'SMS' notification to a user's mobile device."""

    __returning__ = int
    __api_method__ = "secure.sendSMSNotification"

    message: str
    user_id: int


class SecureSetCounter(VKMethod[dict]):
    """Sets a counter which is shown to the user in bold in the left menu."""

    __returning__ = dict
    __api_method__ = "secure.setCounter"

    counter: int | None = None
    counters: list[str] | None = None
    increment: bool | None = None
    user_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "secure.addAppEvent": SecureAddAppEvent,
    "secure.checkToken": SecureCheckToken,
    "secure.getAppBalance": SecureGetAppBalance,
    "secure.getSMSHistory": SecureGetSMSHistory,
    "secure.getTransactionsHistory": SecureGetTransactionsHistory,
    "secure.getUserLevel": SecureGetUserLevel,
    "secure.giveEventSticker": SecureGiveEventSticker,
    "secure.sendNotification": SecureSendNotification,
    "secure.sendSMSNotification": SecureSendSMSNotification,
    "secure.setCounter": SecureSetCounter,
}

__all__ = ["SecureAddAppEvent", "SecureCheckToken", "SecureGetAppBalance", "SecureGetSMSHistory", "SecureGetTransactionsHistory", "SecureGetUserLevel", "SecureGiveEventSticker", "SecureSendNotification", "SecureSendSMSNotification", "SecureSetCounter"]
