"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StatusGet(VKMethod[dict]):
    """Returns data required to show the status of a user or community."""

    __returning__ = dict
    __api_method__ = "status.get"

    group_id: int | None = None
    user_id: int | None = None


class StatusSet(VKMethod[int]):
    """Sets a new status for the current user."""

    __returning__ = int
    __api_method__ = "status.set"

    group_id: int | None = None
    text: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "status.get": StatusGet,
    "status.set": StatusSet,
}

__all__ = ["StatusGet", "StatusSet"]
