"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StatsGet(VKMethod[list]):
    """Returns statistics of a community or an application."""

    __returning__ = list
    __api_method__ = "stats.get"

    app_id: int | None = None
    extended: bool = True
    filters: list[str] | None = None
    group_id: int | None = None
    interval: str = 'day'
    intervals_count: int | None = None
    stats_groups: list[str] | None = None
    timestamp_from: float | None = None
    timestamp_to: float | None = None


class StatsGetPostReach(VKMethod[list]):
    """Returns stats for a wall post."""

    __returning__ = list
    __api_method__ = "stats.getPostReach"

    owner_id: int
    post_ids: list[int]


class StatsTrackVisitor(VKMethod[int]):
    """VK API method stats.trackVisitor."""

    __returning__ = int
    __api_method__ = "stats.trackVisitor"

    type: str = 'open'



REGISTRY: dict[str, type[VKMethod]] = {
    "stats.get": StatsGet,
    "stats.getPostReach": StatsGetPostReach,
    "stats.trackVisitor": StatsTrackVisitor,
}

__all__ = ["StatsGet", "StatsGetPostReach", "StatsTrackVisitor"]
