"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StoriesBanOwner(VKMethod[int]):
    """Allows to hide stories from chosen sources from current user's feed."""

    __returning__ = int
    __api_method__ = "stories.banOwner"

    owners_ids: list[int]


class StoriesDelete(VKMethod[int]):
    """Allows to delete story."""

    __returning__ = int
    __api_method__ = "stories.delete"

    owner_id: int | None = None
    stories: list[str] | None = None
    story_id: int | None = None


class StoriesGet(VKMethod[dict]):
    """Returns stories available for current user."""

    __returning__ = dict
    __api_method__ = "stories.get"

    extended: bool = False
    fields: list[str] | None = None
    owner_id: int | None = None


class StoriesGetBanned(VKMethod[dict]):
    """Returns list of sources hidden from current user's feed."""

    __returning__ = dict
    __api_method__ = "stories.getBanned"

    extended: bool | None = None
    fields: list[str] | None = None


class StoriesGetById(VKMethod[dict]):
    """Returns story by its ID."""

    __returning__ = dict
    __api_method__ = "stories.getById"

    stories: list[str]
    extended: bool = False
    fields: list[str] | None = None


class StoriesGetPhotoUploadServer(VKMethod[dict]):
    """Returns URL for uploading a story with photo."""

    __returning__ = dict
    __api_method__ = "stories.getPhotoUploadServer"

    add_to_news: bool | None = None
    clickable_stickers: str | None = None
    group_id: int | None = None
    link_text: str | None = None
    link_url: str | None = None
    reply_to_story: str | None = None
    user_ids: list[int] | None = None


class StoriesGetReplies(VKMethod[dict]):
    """Returns replies to the story."""

    __returning__ = dict
    __api_method__ = "stories.getReplies"

    owner_id: int
    story_id: int
    access_key: str | None = None
    extended: bool = False
    fields: list[str] | None = None


class StoriesGetStats(VKMethod[dict]):
    """Returns stories available for current user."""

    __returning__ = dict
    __api_method__ = "stories.getStats"

    owner_id: int
    story_id: int


class StoriesGetVideoUploadServer(VKMethod[dict]):
    """Allows to receive URL for uploading story with video."""

    __returning__ = dict
    __api_method__ = "stories.getVideoUploadServer"

    add_to_news: bool | None = None
    clickable_stickers: str | None = None
    group_id: int | None = None
    link_text: str | None = None
    link_url: str | None = None
    reply_to_story: str | None = None
    user_ids: list[int] | None = None


class StoriesGetViewers(VKMethod[dict]):
    """Returns a list of story viewers."""

    __returning__ = dict
    __api_method__ = "stories.getViewers"

    story_id: int
    count: int = 100
    extended: bool = False
    fields: list[str] | None = None
    offset: int = 0
    owner_id: int | None = None


class StoriesHideAllReplies(VKMethod[int]):
    """Hides all replies in the last 24 hours from the user to current user's stories."""

    __returning__ = int
    __api_method__ = "stories.hideAllReplies"

    owner_id: int
    group_id: int | None = None


class StoriesHideReply(VKMethod[int]):
    """Hides the reply to the current user's story."""

    __returning__ = int
    __api_method__ = "stories.hideReply"

    owner_id: int
    story_id: int


class StoriesSave(VKMethod[dict]):
    """VK API method stories.save."""

    __returning__ = dict
    __api_method__ = "stories.save"

    extended: bool | None = None
    fields: list[str] | None = None
    upload_results: list[str] | None = None
    upload_results_json: str | None = None


class StoriesSearch(VKMethod[dict]):
    """VK API method stories.search."""

    __returning__ = dict
    __api_method__ = "stories.search"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    latitude: float | None = None
    longitude: float | None = None
    mentioned_id: int | None = None
    place_id: int | None = None
    q: str | None = None
    radius: int | None = None


class StoriesSendInteraction(VKMethod[int]):
    """VK API method stories.sendInteraction."""

    __returning__ = int
    __api_method__ = "stories.sendInteraction"

    access_key: str
    is_anonymous: bool = False
    is_broadcast: bool = False
    message: str | None = None
    unseen_marker: bool = False


class StoriesUnbanOwner(VKMethod[int]):
    """Allows to show stories from hidden sources in current user's feed."""

    __returning__ = int
    __api_method__ = "stories.unbanOwner"

    owners_ids: list[int]



REGISTRY: dict[str, type[VKMethod]] = {
    "stories.banOwner": StoriesBanOwner,
    "stories.delete": StoriesDelete,
    "stories.get": StoriesGet,
    "stories.getBanned": StoriesGetBanned,
    "stories.getById": StoriesGetById,
    "stories.getPhotoUploadServer": StoriesGetPhotoUploadServer,
    "stories.getReplies": StoriesGetReplies,
    "stories.getStats": StoriesGetStats,
    "stories.getVideoUploadServer": StoriesGetVideoUploadServer,
    "stories.getViewers": StoriesGetViewers,
    "stories.hideAllReplies": StoriesHideAllReplies,
    "stories.hideReply": StoriesHideReply,
    "stories.save": StoriesSave,
    "stories.search": StoriesSearch,
    "stories.sendInteraction": StoriesSendInteraction,
    "stories.unbanOwner": StoriesUnbanOwner,
}

__all__ = ["StoriesBanOwner", "StoriesDelete", "StoriesGet", "StoriesGetBanned", "StoriesGetById", "StoriesGetPhotoUploadServer", "StoriesGetReplies", "StoriesGetStats", "StoriesGetVideoUploadServer", "StoriesGetViewers", "StoriesHideAllReplies", "StoriesHideReply", "StoriesSave", "StoriesSearch", "StoriesSendInteraction", "StoriesUnbanOwner"]
