"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StorageGet(VKMethod[list]):
    """Returns a value of variable with the name set by key parameter."""

    __returning__ = list
    __api_method__ = "storage.get"

    key: str | None = None
    keys: list[str] | None = None
    user_id: int | None = None


class StorageGetKeys(VKMethod[list]):
    """Returns the names of all variables."""

    __returning__ = list
    __api_method__ = "storage.getKeys"

    count: int = 100
    offset: int = 0
    user_id: int | None = None


class StorageSet(VKMethod[int]):
    """Saves a value of variable with the name set by 'key' parameter."""

    __returning__ = int
    __api_method__ = "storage.set"

    key: str
    user_id: int | None = None
    value: str | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "storage.get": StorageGet,
    "storage.getKeys": StorageGetKeys,
    "storage.set": StorageSet,
}

__all__ = ["StorageGet", "StorageGetKeys", "StorageSet"]
