"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StoreAddStickersToFavorite(VKMethod[int]):
    """Adds given sticker IDs to the list of user's favorite stickers"""

    __returning__ = int
    __api_method__ = "store.addStickersToFavorite"

    sticker_ids: list[int]


class StoreGetFavoriteStickers(VKMethod[dict]):
    """VK API method store.getFavoriteStickers."""

    __returning__ = dict
    __api_method__ = "store.getFavoriteStickers"


class StoreGetProducts(VKMethod[dict]):
    """VK API method store.getProducts."""

    __returning__ = dict
    __api_method__ = "store.getProducts"

    extended: bool = False
    filters: list[str] | None = None
    merchant: str | None = None
    product_ids: list[int] | None = None
    section: str | None = None
    type: str | None = None


class StoreGetStickersKeywords(VKMethod[dict]):
    """VK API method store.getStickersKeywords."""

    __returning__ = dict
    __api_method__ = "store.getStickersKeywords"

    aliases: bool = True
    all_products: bool | None = None
    need_stickers: bool = True
    products_ids: list[int] | None = None
    stickers_ids: list[int] | None = None
    vmoji_promo: bool | None = None


class StoreRemoveStickersFromFavorite(VKMethod[int]):
    """Removes given sticker IDs from the list of user's favorite stickers"""

    __returning__ = int
    __api_method__ = "store.removeStickersFromFavorite"

    sticker_ids: list[int]



REGISTRY: dict[str, type[VKMethod]] = {
    "store.addStickersToFavorite": StoreAddStickersToFavorite,
    "store.getFavoriteStickers": StoreGetFavoriteStickers,
    "store.getProducts": StoreGetProducts,
    "store.getStickersKeywords": StoreGetStickersKeywords,
    "store.removeStickersFromFavorite": StoreRemoveStickersFromFavorite,
}

__all__ = ["StoreAddStickersToFavorite", "StoreGetFavoriteStickers", "StoreGetProducts", "StoreGetStickersKeywords", "StoreRemoveStickersFromFavorite"]
