"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class StreamingGetServerUrl(VKMethod[dict]):
    """Allows to receive data for the connection to Streaming API."""

    __returning__ = dict
    __api_method__ = "streaming.getServerUrl"


class StreamingGetStats(VKMethod[list]):
    """VK API method streaming.getStats."""

    __returning__ = list
    __api_method__ = "streaming.getStats"

    end_time: int | None = None
    interval: str = '5m'
    start_time: int | None = None
    type: str | None = None


class StreamingGetStem(VKMethod[dict]):
    """VK API method streaming.getStem."""

    __returning__ = dict
    __api_method__ = "streaming.getStem"

    word: str



REGISTRY: dict[str, type[VKMethod]] = {
    "streaming.getServerUrl": StreamingGetServerUrl,
    "streaming.getStats": StreamingGetStats,
    "streaming.getStem": StreamingGetStem,
}

__all__ = ["StreamingGetServerUrl", "StreamingGetStats", "StreamingGetStem"]
