"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class TranslationsTranslate(VKMethod[dict]):
    """VK API method translations.translate."""

    __returning__ = dict
    __api_method__ = "translations.translate"

    texts: list[str]
    translation_language: str



REGISTRY: dict[str, type[VKMethod]] = {
    "translations.translate": TranslationsTranslate,
}

__all__ = ["TranslationsTranslate"]
