"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class UsersGet(VKMethod[list]):
    """Returns detailed information on users."""

    __returning__ = list
    __api_method__ = "users.get"

    fields: list[str] | None = None
    from_group_id: int = 0
    name_case: str | None = None
    user_ids: list[str] | None = None


class UsersGetFollowers(VKMethod[dict]):
    """Returns a list of IDs of followers of the user in question, sorted by date added, most recent first."""

    __returning__ = dict
    __api_method__ = "users.getFollowers"

    count: int = 100
    fields: list[str] | None = None
    name_case: str | None = None
    offset: int | None = None
    user_id: int | None = None


class UsersGetSubscriptions(VKMethod[dict]):
    """Returns a list of IDs of users and communities followed by the user."""

    __returning__ = dict
    __api_method__ = "users.getSubscriptions"

    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    offset: int | None = None
    user_id: int | None = None


class UsersReport(VKMethod[int]):
    """Reports (submits a complain about) a user."""

    __returning__ = int
    __api_method__ = "users.report"

    type: str
    user_id: int
    comment: str | None = None


class UsersSearch(VKMethod[dict]):
    """Returns a list of users matching the search criteria."""

    __returning__ = dict
    __api_method__ = "users.search"

    age_from: int | None = None
    age_to: int | None = None
    birth_day: int | None = None
    birth_month: int | None = None
    birth_year: int | None = None
    city: int | None = None
    city_id: int | None = None
    company: str | None = None
    count: int = 20
    country: int | None = None
    country_id: int | None = None
    fields: list[str] | None = None
    from_group_id: int = 0
    from_list: list[str] | None = None
    group_id: int | None = None
    has_photo: bool | None = None
    hometown: str | None = None
    offset: int | None = None
    online: bool | None = None
    position: str | None = None
    q: str | None = None
    religion: str | None = None
    school: int | None = None
    school_city: int | None = None
    school_class: int | None = None
    school_country: int | None = None
    school_year: int | None = None
    screen_ref: str | None = None
    sex: int | None = None
    sort: int | None = None
    status: int | None = None
    university: int | None = None
    university_chair: int | None = None
    university_country: int | None = None
    university_faculty: int | None = None
    university_year: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "users.get": UsersGet,
    "users.getFollowers": UsersGetFollowers,
    "users.getSubscriptions": UsersGetSubscriptions,
    "users.report": UsersReport,
    "users.search": UsersSearch,
}

__all__ = ["UsersGet", "UsersGetFollowers", "UsersGetSubscriptions", "UsersReport", "UsersSearch"]
