"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class UtilsCheckLink(VKMethod[dict]):
    """Checks whether a link is blocked in VK."""

    __returning__ = dict
    __api_method__ = "utils.checkLink"

    url: str


class UtilsDeleteFromLastShortened(VKMethod[int]):
    """Deletes shortened link from user's list."""

    __returning__ = int
    __api_method__ = "utils.deleteFromLastShortened"

    key: str


class UtilsGetLastShortenedLinks(VKMethod[dict]):
    """Returns a list of user's shortened links."""

    __returning__ = dict
    __api_method__ = "utils.getLastShortenedLinks"

    count: int = 10
    offset: int = 0


class UtilsGetLinkStats(VKMethod[dict]):
    """Returns stats data for shortened link."""

    __returning__ = dict
    __api_method__ = "utils.getLinkStats"

    key: str
    access_key: str | None = None
    extended: bool = False
    interval: str = 'day'
    intervals_count: int = 1
    source: str = 'vk_cc'


class UtilsGetServerTime(VKMethod[int]):
    """Returns the current time of the VK server."""

    __returning__ = int
    __api_method__ = "utils.getServerTime"


class UtilsGetShortLink(VKMethod[dict]):
    """Allows to receive a link shortened via vk.cc."""

    __returning__ = dict
    __api_method__ = "utils.getShortLink"

    url: str
    private: bool = False


class UtilsResolveScreenName(VKMethod[dict]):
    """Detects a type of object (e.g., user, community, application) and its ID by screen name."""

    __returning__ = dict
    __api_method__ = "utils.resolveScreenName"

    screen_name: str



REGISTRY: dict[str, type[VKMethod]] = {
    "utils.checkLink": UtilsCheckLink,
    "utils.deleteFromLastShortened": UtilsDeleteFromLastShortened,
    "utils.getLastShortenedLinks": UtilsGetLastShortenedLinks,
    "utils.getLinkStats": UtilsGetLinkStats,
    "utils.getServerTime": UtilsGetServerTime,
    "utils.getShortLink": UtilsGetShortLink,
    "utils.resolveScreenName": UtilsResolveScreenName,
}

__all__ = ["UtilsCheckLink", "UtilsDeleteFromLastShortened", "UtilsGetLastShortenedLinks", "UtilsGetLinkStats", "UtilsGetServerTime", "UtilsGetShortLink", "UtilsResolveScreenName"]
