"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class VideoAdd(VKMethod[int]):
    """Adds a video to a user or community page."""

    __returning__ = int
    __api_method__ = "video.add"

    owner_id: int
    video_id: int
    target_id: int | None = None


class VideoAddAlbum(VKMethod[dict]):
    """Creates an empty album for videos."""

    __returning__ = dict
    __api_method__ = "video.addAlbum"

    group_id: int | None = None
    privacy: list[str] | None = None
    title: str | None = None


class VideoAddToAlbum(VKMethod[int]):
    """VK API method video.addToAlbum."""

    __returning__ = int
    __api_method__ = "video.addToAlbum"

    owner_id: int
    video_id: int
    album_id: int | None = None
    album_ids: list[int] | None = None
    target_id: int | None = None


class VideoCreateComment(VKMethod[int]):
    """Adds a new comment on a video."""

    __returning__ = int
    __api_method__ = "video.createComment"

    video_id: int
    attachments: list[str] | None = None
    from_group: bool | None = None
    guid: str | None = None
    message: str | None = None
    owner_id: int | None = None
    reply_to_comment: int | None = None
    sticker_id: int | None = None
    track_code: str | None = None


class VideoDelete(VKMethod[int]):
    """Deletes a video from a user or community page."""

    __returning__ = int
    __api_method__ = "video.delete"

    video_id: int
    owner_id: int | None = None
    target_id: int | None = None


class VideoDeleteAlbum(VKMethod[int]):
    """Deletes a video album."""

    __returning__ = int
    __api_method__ = "video.deleteAlbum"

    album_id: int
    group_id: int | None = None
    owner_id: int | None = None


class VideoDeleteComment(VKMethod[int]):
    """Deletes a comment on a video."""

    __returning__ = int
    __api_method__ = "video.deleteComment"

    comment_id: int
    owner_id: int | None = None


class VideoDeleteThread(VKMethod[int]):
    """Deletes a thread on a video."""

    __returning__ = int
    __api_method__ = "video.deleteThread"

    owner_id: int
    thread_id: int


class VideoEdit(VKMethod[dict]):
    """Edits information about a video on a user or community page."""

    __returning__ = dict
    __api_method__ = "video.edit"

    video_id: int
    desc: str | None = None
    name: str | None = None
    no_comments: bool | None = None
    ord_info: str | None = None
    owner_id: int | None = None
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None
    repeat: bool | None = None


class VideoEditAlbum(VKMethod[int]):
    """Edits the title of a video album."""

    __returning__ = int
    __api_method__ = "video.editAlbum"

    album_id: int
    group_id: int | None = None
    owner_id: int | None = None
    privacy: list[str] | None = None
    title: str | None = None


class VideoEditComment(VKMethod[int]):
    """Edits the text of a comment on a video."""

    __returning__ = int
    __api_method__ = "video.editComment"

    comment_id: int
    attachments: list[str] | None = None
    message: str | None = None
    owner_id: int | None = None


class VideoGet(VKMethod[dict]):
    """Returns detailed information about videos."""

    __returning__ = dict
    __api_method__ = "video.get"

    album_id: int | None = None
    count: int = 100
    extended: bool | None = None
    fields: list[str] | None = None
    offset: int | None = None
    owner_id: int = 0
    sort_album: int = 0
    videos: list[str] | None = None


class VideoGetAlbumById(VKMethod[dict]):
    """Returns video album info"""

    __returning__ = dict
    __api_method__ = "video.getAlbumById"

    album_id: int
    owner_id: int | None = None


class VideoGetAlbums(VKMethod[dict]):
    """Returns a list of video albums owned by a user or community."""

    __returning__ = dict
    __api_method__ = "video.getAlbums"

    count: int = 50
    extended: bool | None = None
    need_system: bool = False
    offset: int | None = None
    owner_id: int | None = None


class VideoGetAlbumsByVideo(VKMethod[list]):
    """VK API method video.getAlbumsByVideo."""

    __returning__ = list
    __api_method__ = "video.getAlbumsByVideo"

    owner_id: int
    video_id: int
    extended: bool = False
    target_id: int | None = None


class VideoGetComments(VKMethod[dict]):
    """Returns a list of comments on a video."""

    __returning__ = dict
    __api_method__ = "video.getComments"

    video_id: int
    comment_id: int | None = None
    count: int = 20
    extended: bool | None = None
    fields: list[str] | None = None
    need_likes: bool | None = None
    offset: int | None = None
    owner_id: int | None = None
    sort: str | None = None
    start_comment_id: int | None = None
    thread_items_count: int = 0


class VideoGetLongPollServer(VKMethod[dict]):
    """VK API method video.getLongPollServer."""

    __returning__ = dict
    __api_method__ = "video.getLongPollServer"

    video_id: int
    owner_id: int | None = None


class VideoGetOembed(VKMethod[dict]):
    """Returns oEmbed player to video"""

    __returning__ = dict
    __api_method__ = "video.getOembed"

    url: str
    maxheight: int | None = None
    maxwidth: int | None = None


class VideoGetThumbUploadUrl(VKMethod[dict]):
    """VK API method video.getThumbUploadUrl."""

    __returning__ = dict
    __api_method__ = "video.getThumbUploadUrl"

    owner_id: int


class VideoLiveGetCategories(VKMethod[list]):
    """VK API method video.liveGetCategories."""

    __returning__ = list
    __api_method__ = "video.liveGetCategories"


class VideoRemoveFromAlbum(VKMethod[int]):
    """VK API method video.removeFromAlbum."""

    __returning__ = int
    __api_method__ = "video.removeFromAlbum"

    owner_id: int
    video_id: int
    album_id: int | None = None
    album_ids: list[int] | None = None
    target_id: int | None = None


class VideoReorderAlbums(VKMethod[int]):
    """Reorders the album in the list of user video albums."""

    __returning__ = int
    __api_method__ = "video.reorderAlbums"

    album_id: int
    after: int | None = None
    before: int | None = None
    owner_id: int | None = None


class VideoReorderVideos(VKMethod[int]):
    """Reorders the video in the video album."""

    __returning__ = int
    __api_method__ = "video.reorderVideos"

    owner_id: int
    video_id: int
    after_owner_id: int | None = None
    after_video_id: int | None = None
    album_id: int = -2
    before_owner_id: int | None = None
    before_video_id: int | None = None
    target_id: int | None = None


class VideoReport(VKMethod[int]):
    """Reports (submits a complaint about) a video."""

    __returning__ = int
    __api_method__ = "video.report"

    owner_id: int
    video_id: int
    comment: str | None = None
    reason: int | None = None
    search_query: str | None = None


class VideoReportComment(VKMethod[int]):
    """Reports (submits a complaint about) a comment on a video."""

    __returning__ = int
    __api_method__ = "video.reportComment"

    comment_id: int
    owner_id: int
    reason: int | None = None


class VideoRestore(VKMethod[int]):
    """Restores a previously deleted video."""

    __returning__ = int
    __api_method__ = "video.restore"

    video_id: int
    owner_id: int | None = None


class VideoRestoreComment(VKMethod[int]):
    """Restores a previously deleted comment on a video."""

    __returning__ = int
    __api_method__ = "video.restoreComment"

    comment_id: int
    owner_id: int | None = None


class VideoRestoreThread(VKMethod[int]):
    """Restores a deleted thread on a video."""

    __returning__ = int
    __api_method__ = "video.restoreThread"

    owner_id: int
    thread_id: int


class VideoSave(VKMethod[dict]):
    """Returns a server address (required for upload) and video data."""

    __returning__ = dict
    __api_method__ = "video.save"

    album_id: int | None = None
    auto_publish: bool | None = None
    compression: bool | None = None
    description: str | None = None
    group_id: int | None = None
    is_private: bool | None = None
    link: str | None = None
    name: str | None = None
    no_comments: bool | None = None
    ord_info: str | None = None
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None
    repeat: bool | None = None
    wallpost: bool | None = None


class VideoSaveUploadedThumb(VKMethod[dict]):
    """VK API method video.saveUploadedThumb."""

    __returning__ = dict
    __api_method__ = "video.saveUploadedThumb"

    owner_id: int
    thumb_json: str
    random_tag: str | None = None
    set_thumb: bool | None = None
    thumb_size: str | None = None
    video_id: int | None = None


class VideoSearch(VKMethod[dict]):
    """Returns a list of videos under the set search criterion."""

    __returning__ = dict
    __api_method__ = "video.search"

    adult: bool | None = None
    count: int = 20
    extended: bool = False
    fields: list[str] | None = None
    filters: list[str] | None = None
    hd: int | None = None
    live: bool | None = None
    longer: int | None = None
    offset: int | None = None
    owner_id: int | None = None
    q: str | None = None
    search_own: bool | None = None
    shorter: int | None = None
    sort: int | None = None


class VideoStartStreaming(VKMethod[dict]):
    """VK API method video.startStreaming."""

    __returning__ = dict
    __api_method__ = "video.startStreaming"

    category_id: int | None = None
    description: str | None = None
    group_id: int | None = None
    name: str | None = None
    no_comments: bool | None = None
    privacy_comment: list[str] | None = None
    privacy_view: list[str] | None = None
    publish: bool | None = None
    video_id: int | None = None
    wallpost: bool | None = None


class VideoStopStreaming(VKMethod[dict]):
    """VK API method video.stopStreaming."""

    __returning__ = dict
    __api_method__ = "video.stopStreaming"

    group_id: int | None = None
    video_id: int | None = None


class VideoUnpinComment(VKMethod[int]):
    """Unpin comment of a video."""

    __returning__ = int
    __api_method__ = "video.unpinComment"

    comment_id: int
    owner_id: int



REGISTRY: dict[str, type[VKMethod]] = {
    "video.add": VideoAdd,
    "video.addAlbum": VideoAddAlbum,
    "video.addToAlbum": VideoAddToAlbum,
    "video.createComment": VideoCreateComment,
    "video.delete": VideoDelete,
    "video.deleteAlbum": VideoDeleteAlbum,
    "video.deleteComment": VideoDeleteComment,
    "video.deleteThread": VideoDeleteThread,
    "video.edit": VideoEdit,
    "video.editAlbum": VideoEditAlbum,
    "video.editComment": VideoEditComment,
    "video.get": VideoGet,
    "video.getAlbumById": VideoGetAlbumById,
    "video.getAlbums": VideoGetAlbums,
    "video.getAlbumsByVideo": VideoGetAlbumsByVideo,
    "video.getComments": VideoGetComments,
    "video.getLongPollServer": VideoGetLongPollServer,
    "video.getOembed": VideoGetOembed,
    "video.getThumbUploadUrl": VideoGetThumbUploadUrl,
    "video.liveGetCategories": VideoLiveGetCategories,
    "video.removeFromAlbum": VideoRemoveFromAlbum,
    "video.reorderAlbums": VideoReorderAlbums,
    "video.reorderVideos": VideoReorderVideos,
    "video.report": VideoReport,
    "video.reportComment": VideoReportComment,
    "video.restore": VideoRestore,
    "video.restoreComment": VideoRestoreComment,
    "video.restoreThread": VideoRestoreThread,
    "video.save": VideoSave,
    "video.saveUploadedThumb": VideoSaveUploadedThumb,
    "video.search": VideoSearch,
    "video.startStreaming": VideoStartStreaming,
    "video.stopStreaming": VideoStopStreaming,
    "video.unpinComment": VideoUnpinComment,
}

__all__ = ["VideoAdd", "VideoAddAlbum", "VideoAddToAlbum", "VideoCreateComment", "VideoDelete", "VideoDeleteAlbum", "VideoDeleteComment", "VideoDeleteThread", "VideoEdit", "VideoEditAlbum", "VideoEditComment", "VideoGet", "VideoGetAlbumById", "VideoGetAlbums", "VideoGetAlbumsByVideo", "VideoGetComments", "VideoGetLongPollServer", "VideoGetOembed", "VideoGetThumbUploadUrl", "VideoLiveGetCategories", "VideoRemoveFromAlbum", "VideoReorderAlbums", "VideoReorderVideos", "VideoReport", "VideoReportComment", "VideoRestore", "VideoRestoreComment", "VideoRestoreThread", "VideoSave", "VideoSaveUploadedThumb", "VideoSearch", "VideoStartStreaming", "VideoStopStreaming", "VideoUnpinComment"]
