"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class WallCheckCopyrightLink(VKMethod[int]):
    """VK API method wall.checkCopyrightLink."""

    __returning__ = int
    __api_method__ = "wall.checkCopyrightLink"

    link: str


class WallCloseComments(VKMethod[int]):
    """VK API method wall.closeComments."""

    __returning__ = int
    __api_method__ = "wall.closeComments"

    owner_id: int
    post_id: int


class WallCreateComment(VKMethod[dict]):
    """Adds a comment to a post on a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.createComment"

    post_id: int
    attachments: list[str] | None = None
    from_group: int | None = None
    guid: str | None = None
    message: str | None = None
    owner_id: int | None = None
    reply_to_comment: int | None = None
    sticker_id: int | None = None


class WallDelete(VKMethod[int]):
    """Deletes a post from a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.delete"

    owner_id: int | None = None
    post_id: int | None = None


class WallDeleteComment(VKMethod[int]):
    """Deletes a comment on a post on a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.deleteComment"

    comment_id: int
    owner_id: int | None = None
    post_id: int | None = None


class WallEdit(VKMethod[dict]):
    """Edits a post on a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.edit"

    post_id: int
    attachments: list[str] | None = None
    close_comments: bool | None = None
    copyright: str | None = None
    donut_paid_duration: int | None = None
    friends_only: bool | None = None
    lat: float | None = None
    long: float | None = None
    mark_as_ads: bool | None = None
    message: str | None = None
    owner_id: int | None = None
    place_id: int | None = None
    poster_bkg_access_hash: str | None = None
    poster_bkg_id: int | None = None
    poster_bkg_owner_id: int | None = None
    publish_date: int | None = None
    services: str | None = None
    signed: bool | None = None
    topic_id: int | None = None


class WallEditAdsStealth(VKMethod[int]):
    """Allows to edit hidden post."""

    __returning__ = int
    __api_method__ = "wall.editAdsStealth"

    post_id: int
    attachments: list[str] | None = None
    lat: float | None = None
    link_button: str | None = None
    link_image: str | None = None
    link_title: str | None = None
    link_video: str | None = None
    long: float | None = None
    message: str | None = None
    owner_id: int | None = None
    place_id: int | None = None
    signed: bool | None = None


class WallEditComment(VKMethod[int]):
    """Edits a comment on a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.editComment"

    comment_id: int
    attachments: list[str] | None = None
    message: str | None = None
    owner_id: int | None = None
    post_id: int | None = None


class WallGet(VKMethod[dict]):
    """Returns a list of posts on a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.get"

    count: int | None = None
    domain: int | str | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    filter: str | None = None
    offset: int | None = None


class WallGetById(VKMethod[dict]):
    """Returns a list of posts from user or community walls by their IDs."""

    __returning__ = dict
    __api_method__ = "wall.getById"

    posts: list[str]
    copy_history_depth: int = 2
    extended: bool | None = None
    fields: list[str] | None = None


class WallGetComment(VKMethod[dict]):
    """Returns a comment on a post on a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.getComment"

    comment_id: int
    extended: bool | None = None
    fields: list[str] | None = None
    owner_id: int | None = None


class WallGetComments(VKMethod[dict]):
    """Returns a list of comments on a post on a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.getComments"

    comment_id: int | None = None
    count: int | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    need_likes: bool | None = None
    offset: int | None = None
    owner_id: int | None = None
    post_id: int | None = None
    preview_length: int | None = None
    sort: str | None = None
    start_comment_id: int | None = None
    thread_items_count: int = 0


class WallGetReposts(VKMethod[dict]):
    """Returns information about reposts of a post on user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.getReposts"

    count: int = 20
    offset: int | None = None
    owner_id: int | None = None
    post_id: int | None = None


class WallOpenComments(VKMethod[int]):
    """VK API method wall.openComments."""

    __returning__ = int
    __api_method__ = "wall.openComments"

    owner_id: int
    post_id: int


class WallParseAttachedLink(VKMethod[dict]):
    """VK API method wall.parseAttachedLink."""

    __returning__ = dict
    __api_method__ = "wall.parseAttachedLink"

    links: str
    extended: bool = False
    fields: list[str] | None = None
    name_case: str | None = None


class WallPin(VKMethod[int]):
    """Pins the post on wall."""

    __returning__ = int
    __api_method__ = "wall.pin"

    post_id: int
    owner_id: int | None = None


class WallPost(VKMethod[dict]):
    """Adds a new post on a user wall or community wall. Can also be used to publish suggested or scheduled posts."""

    __returning__ = dict
    __api_method__ = "wall.post"

    attachments: list[str] | None = None
    close_comments: bool | None = None
    copyright: str | None = None
    donut_paid_duration: int | None = None
    friends_only: bool | None = None
    from_group: bool | None = None
    guid: str | None = None
    lat: float | None = None
    link_photo_id: str | None = None
    link_title: str | None = None
    long: float | None = None
    mark_as_ads: bool = False
    message: str | None = None
    mute_notifications: bool | None = None
    owner_id: int | None = None
    place_id: int | None = None
    post_id: int | None = None
    publish_date: int | None = None
    services: str | None = None
    signed: bool | None = None


class WallPostAdsStealth(VKMethod[dict]):
    """Allows to create hidden post which will not be shown on the community's wall and can be used for creating an ad with type "Community post"."""

    __returning__ = dict
    __api_method__ = "wall.postAdsStealth"

    owner_id: int
    attachments: list[str] | None = None
    guid: str | None = None
    lat: float | None = None
    link_button: str | None = None
    link_image: str | None = None
    link_title: str | None = None
    link_video: str | None = None
    long: float | None = None
    message: str | None = None
    place_id: int | None = None
    signed: bool | None = None


class WallReportComment(VKMethod[int]):
    """Reports (submits a complaint about) a comment on a post on a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.reportComment"

    comment_id: int
    owner_id: int
    reason: int


class WallReportPost(VKMethod[int]):
    """Reports (submits a complaint about) a post on a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.reportPost"

    owner_id: int
    post_id: int
    reason: int


class WallRepost(VKMethod[dict]):
    """Reposts (copies) an object to a user wall or community wall."""

    __returning__ = dict
    __api_method__ = "wall.repost"

    object: str
    group_id: int | None = None
    mark_as_ads: bool = False
    message: str | None = None
    mute_notifications: bool | None = None


class WallRestore(VKMethod[int]):
    """Restores a post deleted from a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.restore"

    owner_id: int | None = None
    post_id: int | None = None


class WallRestoreComment(VKMethod[int]):
    """Restores a comment deleted from a user wall or community wall."""

    __returning__ = int
    __api_method__ = "wall.restoreComment"

    comment_id: int
    owner_id: int | None = None


class WallSearch(VKMethod[dict]):
    """Allows to search posts on user or community walls."""

    __returning__ = dict
    __api_method__ = "wall.search"

    count: int = 20
    domain: int | str | None = None
    extended: bool | None = None
    fields: list[str] | None = None
    offset: int = 0
    owners_only: bool | None = None
    query: str | None = None


class WallUnpin(VKMethod[int]):
    """Unpins the post on wall."""

    __returning__ = int
    __api_method__ = "wall.unpin"

    post_id: int
    owner_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "wall.checkCopyrightLink": WallCheckCopyrightLink,
    "wall.closeComments": WallCloseComments,
    "wall.createComment": WallCreateComment,
    "wall.delete": WallDelete,
    "wall.deleteComment": WallDeleteComment,
    "wall.edit": WallEdit,
    "wall.editAdsStealth": WallEditAdsStealth,
    "wall.editComment": WallEditComment,
    "wall.get": WallGet,
    "wall.getById": WallGetById,
    "wall.getComment": WallGetComment,
    "wall.getComments": WallGetComments,
    "wall.getReposts": WallGetReposts,
    "wall.openComments": WallOpenComments,
    "wall.parseAttachedLink": WallParseAttachedLink,
    "wall.pin": WallPin,
    "wall.post": WallPost,
    "wall.postAdsStealth": WallPostAdsStealth,
    "wall.reportComment": WallReportComment,
    "wall.reportPost": WallReportPost,
    "wall.repost": WallRepost,
    "wall.restore": WallRestore,
    "wall.restoreComment": WallRestoreComment,
    "wall.search": WallSearch,
    "wall.unpin": WallUnpin,
}

__all__ = ["WallCheckCopyrightLink", "WallCloseComments", "WallCreateComment", "WallDelete", "WallDeleteComment", "WallEdit", "WallEditAdsStealth", "WallEditComment", "WallGet", "WallGetById", "WallGetComment", "WallGetComments", "WallGetReposts", "WallOpenComments", "WallParseAttachedLink", "WallPin", "WallPost", "WallPostAdsStealth", "WallReportComment", "WallReportPost", "WallRepost", "WallRestore", "WallRestoreComment", "WallSearch", "WallUnpin"]
