"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.

Regenerate with::

    python scripts/gen_methods.py
"""
from __future__ import annotations

from ..base import VKMethod


class WidgetsGetComments(VKMethod[dict]):
    """Gets a list of comments for the page added through the [vk.com/dev/Comments|Comments widget]."""

    __returning__ = dict
    __api_method__ = "widgets.getComments"

    count: int = 10
    fields: list[str] | None = None
    offset: int = 0
    order: str = 'date'
    page_id: str | None = None
    url: str | None = None
    widget_api_id: int | None = None


class WidgetsGetPages(VKMethod[dict]):
    """Gets a list of application/site pages where the [vk.com/dev/Comments|Comments widget] or [vk.com/dev/Like|Like widget] is installed."""

    __returning__ = dict
    __api_method__ = "widgets.getPages"

    count: int = 10
    offset: int = 0
    order: str = 'friend_likes'
    period: str = 'week'
    widget_api_id: int | None = None



REGISTRY: dict[str, type[VKMethod]] = {
    "widgets.getComments": WidgetsGetComments,
    "widgets.getPages": WidgetsGetPages,
}

__all__ = ["WidgetsGetComments", "WidgetsGetPages"]
