#!/usr/bin/env python
"""Generate typed ``VKMethod`` classes from the official VK API schema.

Usage
-----
    python scripts/gen_methods.py [--schema DIR] [--out DIR]

``--schema`` points at a checkout of https://github.com/VKCOM/vk-api-schema
(the per-namespace layout, i.e. ``<schema>/messages/methods.json`` etc.).
By default it uses ``scripts/vendor/schema``.

Output goes to ``fastvk/methods/_generated/`` — one module per namespace plus
an ``__init__`` that exposes ``GENERATED_REGISTRY`` (VK method string -> class).

The generated classes are permissive: every parameter is optional unless the
schema marks it ``required`` with no default. ``model_config`` inherits
``extra="allow"`` from :class:`fastvk.methods.base.VKMethod`, so unknown
parameters still pass straight through.
"""
from __future__ import annotations

import argparse
import io
import json
import keyword
import re
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SCHEMA = ROOT / "scripts" / "vendor" / "schema"
DEFAULT_OUT = ROOT / "fastvk" / "methods" / "_generated"

# Pinned to the VK API version this framework targets (see fastvk/__meta__.py).
SCHEMA_TAG = "v5.199.99"
SCHEMA_URL = (
    f"https://github.com/VKCOM/vk-api-schema/archive/refs/tags/{SCHEMA_TAG}.tar.gz"
)


def _download_schema(dest: Path) -> None:
    print(f"downloading VK API schema {SCHEMA_TAG} …")
    with urllib.request.urlopen(SCHEMA_URL, timeout=60) as resp:  # noqa: S310
        raw = resp.read()
    dest.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:gz") as tar:
        for member in tar.getmembers():
            rel = member.name.split("/", 1)
            if len(rel) != 2 or not rel[1].endswith(".json"):
                continue
            member.name = rel[1]
            try:
                tar.extract(member, dest, filter="data")  # noqa: S202
            except TypeError:  # Python < 3.12 has no `filter=`
                tar.extract(member, dest)  # noqa: S202

# field names that would shadow a pydantic BaseModel attribute
_SHADOW = {
    "copy", "dict", "json", "schema", "validate", "construct",
    "model_config", "model_fields", "model_extra", "model_fields_set",
    "model_computed_fields", "model_post_init",
}

_HEADER = (
    '"""AUTO-GENERATED by scripts/gen_methods.py — do not edit by hand.\n\n'
    "Regenerate with::\n\n"
    "    python scripts/gen_methods.py\n"
    '"""\n'
    "from __future__ import annotations\n\n"
)


def _load_defs(schema_dir: Path) -> dict[str, dict]:
    """Merge every ``definitions`` block from responses.json / objects.json."""
    defs: dict[str, dict] = {}
    for pattern in ("*/responses.json", "*/objects.json"):
        for path in sorted(schema_dir.glob(pattern)):
            try:
                data = json.loads(path.read_text("utf-8"))
            except json.JSONDecodeError:
                continue
            for name, body in (data.get("definitions") or {}).items():
                defs.setdefault(name, body)
    return defs


def _ref_name(ref: str) -> str:
    return ref.split("/")[-1]


def _resolve_kind(node: dict, defs: dict[str, dict], depth: int = 0) -> str:
    """Return one of ``'list' | 'int' | 'dict'`` for a response/definition node."""
    if depth > 6 or not isinstance(node, dict):
        return "dict"
    if "$ref" in node:
        target = defs.get(_ref_name(node["$ref"]))
        return _resolve_kind(target, defs, depth + 1) if target else "dict"
    node_type = node.get("type")
    if node_type == "array":
        return "list"
    if node_type in ("integer", "number", "boolean"):
        return "int"
    props = node.get("properties") or {}
    if "response" in props:
        return _resolve_kind(props["response"], defs, depth + 1)
    if "oneOf" in node or "allOf" in node:
        return "dict"
    return "dict"


def _return_kind(method: dict, defs: dict[str, dict]) -> str:
    resp = (method.get("responses") or {}).get("response")
    if not isinstance(resp, dict):
        return "dict"
    return _resolve_kind(resp, defs)


def _class_name(method_name: str) -> str:
    parts = re.split(r"[._]", method_name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _scalar_type(t: str) -> str:
    return {
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "string": "str",
    }.get(t, "str")


def _param_annotation(param: dict) -> str:
    t = param.get("type")
    if isinstance(t, list):
        inner = " | ".join(dict.fromkeys(_scalar_type(x) for x in t))
        return inner or "str"
    if t == "array":
        item = param.get("items") or {}
        it = item.get("type")
        return f"list[{_scalar_type(it) if isinstance(it, str) else 'str'}]"
    if isinstance(t, str):
        return _scalar_type(t)
    if "enum" in param:
        values = param["enum"]
        if values and all(isinstance(v, int) for v in values):
            return "int"
        return "str"
    return "str"  # $ref / untyped -> pass through as string


def _format_default(param: dict, annotation: str) -> str | None:
    if "default" not in param:
        return None
    raw = param["default"]
    if annotation == "bool":
        if isinstance(raw, str):
            raw = raw.strip().lower() not in ("", "0", "false")
        return repr(bool(raw))
    if annotation == "int":
        try:
            return repr(int(raw))
        except (TypeError, ValueError):
            return None
    if annotation == "float":
        try:
            return repr(float(raw))
        except (TypeError, ValueError):
            return None
    if annotation == "str":
        return repr(str(raw))
    return None


def _field_line(param: dict) -> tuple[str, bool]:
    """Return ``(source_line, uses_Field)`` for one parameter."""
    raw_name = param["name"]
    annotation = _param_annotation(param)
    safe = raw_name
    alias = None
    if keyword.iskeyword(raw_name) or raw_name in _SHADOW or raw_name.startswith("model_"):
        safe = f"{raw_name}_"
        alias = raw_name
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", safe):
        safe = re.sub(r"\W", "_", safe)
        alias = raw_name

    default = _format_default(param, annotation)
    required = bool(param.get("required")) and default is None

    if alias:
        if required:
            return f"    {safe}: {annotation} = Field(alias={alias!r})", True
        d = default if default is not None else "None"
        ann = annotation if default is not None else f"{annotation} | None"
        return f"    {safe}: {ann} = Field(default={d}, alias={alias!r})", True

    if required:
        return f"    {safe}: {annotation}", False
    if default is not None:
        return f"    {safe}: {annotation} = {default}", False
    return f"    {safe}: {annotation} | None = None", False


_GENERIC = {"list": "list", "int": "int", "dict": "dict"}


def _render_class(
    method: dict, defs: dict[str, dict]
) -> tuple[str, str, str, bool]:
    """Return ``(class_name, vk_method, source, uses_Field)``."""
    name = method["name"]
    cls = _class_name(name)
    kind = _return_kind(method, defs)
    generic = _GENERIC[kind]

    seen: set[str] = set()
    lines: list[str] = []
    uses_field = False
    # required first so "no-default after default" never happens
    params = sorted(
        method.get("parameters") or [],
        key=lambda p: (not (p.get("required") and "default" not in p), p["name"]),
    )
    for param in params:
        if param["name"] in seen:
            continue
        seen.add(param["name"])
        line, f = _field_line(param)
        uses_field = uses_field or f
        lines.append(line)

    doc = (method.get("description") or "").strip().replace("\\", "\\\\").replace('"""', "'''")
    doc = re.sub(r"\s+", " ", doc) or f"VK API method {name}."
    if doc.endswith('"'):
        doc += " "

    body = f'class {cls}(VKMethod[{generic}]):\n    """{doc}"""\n\n'
    body += f'    __returning__ = {generic}\n'
    body += f'    __api_method__ = "{name}"\n'
    if lines:
        body += "\n" + "\n".join(lines) + "\n"
    return cls, name, body, uses_field


def generate(schema_dir: Path, out_dir: Path) -> None:
    defs = _load_defs(schema_dir)
    by_ns: dict[str, list] = {}
    for path in sorted(schema_dir.glob("*/methods.json")):
        data = json.loads(path.read_text("utf-8"))
        for method in data.get("methods", []):
            ns = method["name"].split(".")[0]
            by_ns.setdefault(ns, []).append(method)

    out_dir.mkdir(parents=True, exist_ok=True)
    for existing in out_dir.glob("*.py"):
        existing.unlink()

    ns_names = sorted(by_ns)
    total = 0
    for ns in ns_names:
        methods = sorted(by_ns[ns], key=lambda m: m["name"])
        rendered = [_render_class(m, defs) for m in methods]
        uses_field = any(r[3] for r in rendered)

        chunks = [_HEADER]
        if uses_field:
            chunks.append("from pydantic import Field\n\n")
        chunks.append("from ..base import VKMethod\n\n\n")
        chunks.append("\n\n".join(r[2] for r in rendered))
        chunks.append("\n\n\n")
        registry = ",\n".join(f'    "{r[1]}": {r[0]}' for r in rendered)
        chunks.append("REGISTRY: dict[str, type[VKMethod]] = {\n" + registry + ",\n}\n\n")
        all_names = ", ".join(f'"{r[0]}"' for r in rendered)
        chunks.append(f"__all__ = [{all_names}]\n")
        (out_dir / f"{ns}.py").write_text("".join(chunks), "utf-8")
        total += len(methods)

    init = [_HEADER]
    for ns in ns_names:
        init.append(f"from . import {ns} as {ns}\n")
    init.append("\n")
    init.append("GENERATED_REGISTRY: dict[str, type] = {}\n")
    for ns in ns_names:
        init.append(f"GENERATED_REGISTRY.update({ns}.REGISTRY)\n")
    init.append("\n")
    init.append("GENERATED_NAMESPACES = (\n")
    for ns in ns_names:
        init.append(f'    "{ns}",\n')
    init.append(")\n\n")
    init.append("__all__ = [\n")
    for ns in ns_names:
        init.append(f'    "{ns}",\n')
    init.append('    "GENERATED_REGISTRY",\n    "GENERATED_NAMESPACES",\n]\n')
    (out_dir / "__init__.py").write_text("".join(init), "utf-8")

    print(f"generated {total} methods across {len(ns_names)} namespaces -> {out_dir}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    if not (args.schema / "messages" / "methods.json").exists():
        if args.schema == DEFAULT_SCHEMA:
            _download_schema(args.schema)
        else:
            raise SystemExit(f"schema not found at {args.schema}")
    generate(args.schema, args.out)


if __name__ == "__main__":
    main()
